### ISSUE TITLE
Publish as PyPI package

### ISSUE THREAD

**Issue by kgadek** [vgrem/Office365-REST-Python-Client#10]
Hi.

Did you consider publishing the code here as PyPI package? It works for my use case, which is exceptional! Being able to `pip install office365-rest-client` would be terrific.

I can help with this by providing PR with proper metadata. I also volunteer to maintain the package if you don't mind (the examples are bit outdated, but easy to fix).

**Comment by vgrem** [comment]
Greetings,

sounds great and welcome! :)
Regarding PyPI package, your assistance and guidance would be much appreciated.
