### ISSUE TITLE
status code

### ISSUE THREAD

**Issue by rmurray1** [vgrem/Office365-REST-Python-Client#101]
I'm able to authenticate and upload a file to SharePoint Online; however, I haven't figured out how to get a status code of the post.  How can I get the status code from the returned object target_file see my code below.

def upload_file(self, ctx, listTitle, filepath):
        """ upload file to SharePoint """
        self.logger.info("Reading file content: %s",filepath)
        with open(filepath, 'rb') as content_file:
            filecontent = content_file.read()
        debug(" file content ")
        # debug(filecontent)
        # get just the name c:\data.txt   name= data.txt
        name = os.path.basename(filepath)
        target_library = ctx.web.lists.get_by_title(listTitle)
        context = target_library.context
        info = FileCreationInformation()
        info.content = filecontent
        info.url = name
        info.overwrite = True
        target_file = None
        target_file = target_library.root_folder.files.add(info)
        context.execute_query()
        print("add -> ", target_file)
        return target_file

**Comment by vgrem** [comment]
Greetings!

the underlying response object could be accessed via `ClientRuntime.get_pending_request` method, the following example demonstrates how to print status code once the file is downloaded:


```
def get_response_details(response):
    print(response.status_code)


with open(download_path, "wb") as local_file:
    source_file = ctx.web.get_file_by_server_relative_url(file_url)
    source_file.download(local_file)
    ctx.get_pending_request().afterExecute += get_response_details
    ctx.execute_query()

```
