### ISSUE TITLE
[Sharepoint] How to move the file from one folder to another folder?

### ISSUE THREAD

**Issue by lihtiandxc** [vgrem/Office365-REST-Python-Client#103]
I was looking how to move the file from one place to another place. Currently the method that i used is to File.Open_binary(sharepoint Source folder) and File.Save_binary(sharepoint Destination folder). It is still involved the action to open the file -> Save it -> finally, delete file from source folder. 

@vgrem

**Comment by lihtiandxc** [comment]
I had implemented this with MoveTo REST API method. Thanks.

**Comment by mukeshk1986** [comment]
I am trying with:
from office365.sharepoint.file import File
from_file="/sites/forecast/Test/Aug212019.xlsx"
dest_path="/sites/forecast/Test/Archive/Aug212019_archive.xlsx"
self._ctx = ClientContext(self.url, self._ctx_auth)

# defination is moveto(self, new_relative_url, flag)
resp1 = File.moveto(self._ctx, from_file, dest_path)
I am trying to figure out how to pass the parameter.
