### ISSUE TITLE
how to integrate with Python's API for fetching and saving/sending e-mail

### ISSUE THREAD

**Issue by maitra** [vgrem/Office365-REST-Python-Client#104]
Are there examples on how to integrate this package with the Python's email facility? I am interested in using it to download mail to local folders and also to send it using a MUA? Some pointers would be helpful. THanks.

**Comment by vgrem** [comment]
One option to consider:

- download a message in MIME format and save them in files with the `.EML` extension as demonstated in [this example](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/outlook/messages/download.py)
- and send it via [SMTP client](https://docs.python.org/3/library/smtplib.html), for example:

```python
with open(eml_fname) as f:
        msg = f.read()
 smtp = smtplib.SMTP(server, port)
 smtp.sendmail(fromaddr, toaddrs, msg)
```
