### ISSUE TITLE
ACS discontinued - how to go about it?

### ISSUE THREAD

**Issue by Bachatero** [vgrem/Office365-REST-Python-Client#107]
Hi, 

I've just learned about ACS being retired from February, 2019 I'm kind of worried if my app using client_id/client_secret authentication is suddenly going to stop working or the ACS retirement does not affect app ACS authentication?

More about ACS retirement here: https://azure.microsoft.com/en-us/blog/one-month-retirement-notice-access-control-service/

```
context_auth = AuthenticationContext(url=myUrl)

if context_auth.acquire_token_for_app(client_id=settings[mySite]['client_id'], client_secret=settings[mySite]['client_secret']):
```

Thank you,

Marcel

**Comment by vgrem** [comment]
Greetings!

true, but the good news according to [SharePoint customers](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-acs-migration#sharepoint-customers) section:

> This retirement does **not** impact the SharePoint Add-in model, which uses the https://accounts.accesscontrol.windows.net hostname (which is not impacted by this retirement). For more information, see [Impact of Azure Access Control retirement for SharePoint Add-ins](https://dev.office.com/blogs/impact-of-azure-access-control-deprecation-for-sharepoint-add-ins).

**Comment by lihtiandxc** [comment]
I am using Sharepoint Add-in model, it is working fine.

**Comment by Bachatero** [comment]
Hi, 

that's a relief, thank you for the information.

Have a nice day.

Marcel
