### ISSUE TITLE
403 Error when authenticating with app password

### ISSUE THREAD

**Issue by JohnL1926** [vgrem/Office365-REST-Python-Client#108]
Hello, I've been using this library with great success, but I can't seem to get it working with a client ID and client secret (using `acquire_token_for_app`). 

The code will successfully acquire the token, but when I try to do any operations (such as `get_folder_by_server_relative_url`) I immediately get a 403 Client error:
```
office365.runtime.client_request_exception.ClientRequestException: ('-2147024891, System.UnauthorizedAccessException', 'Access denied. You do not have permission to perform this action or access this resource.'
, "403 Client Error: Forbidden for url: https://my-company.sharepoint.com/sites/my-site/_api/Web/getfolderbyserverrelativeurl('Shared%20Documents')")
```

I've given my API the Sites.FullControl.All SharePoint permission on the Azure Portal (and granted Admin Consent). Is there something else that I need to enable to get this working? I haven't run into any similar errors with user authentication.

Thanks.

**Comment by vgrem** [comment]
Greetings!

since you've registered application via Azure AD, [certificates credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials) could be utilized to interact with SharePoint Online API

> Note: 
> Since SharePoint Add-ins uses the [low-trust authorization system](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization), client secrets flow trust  is not supported,  certificate app only trust needs to be utilized instead.




Here is an example


```
app_settings = {
    'url': 'https://contoso.sharepoint.com/',  #SharePoint site url  
    'client_id': '--The OAuth client id of the calling application ---', 
    'thumbprint': "-- encoded thumbprint of the certificate --",
    'certificate_path': '-- path to a PEM encoded certificate private key --'
}

ctx = ClientContext.connect_with_certificate(app_settings['url'],
                                             app_settings['client_id'],
                                             app_settings['thumbprint'],
                                             app_settings['certificate_path'])

current_web = ctx.web
ctx.load(current_web)
ctx.execute_query()
print("{0}".format(current_web.url))

```
