### ISSUE TITLE
File.open_binary(context, "/Shared Documents/dir1/captain_america.jpg") throwing error

### ISSUE THREAD

**Issue by chaitanyavolkaji** [vgrem/Office365-REST-Python-Client#109]
> b'<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2147024809, System.ArgumentException</m:code><m:message xml:lang="en-US">Server relative urls must start with SPWeb.ServerRelativeUrl</m:message></m:error>'

**Comment by chaitanyavolkaji** [comment]
In File.open_binary implementation, I see that you are using URL 

`"https://my.sharepoint.com/sites/mysite/_api/web/GetFileByServerRelativeUrl('Shared Documents/dir1/captain-america-chris-evans.jpg')/$value"`


But if I use alternate URL `"https://my.sharepoint.com/sites/mysite/_api/web/GetFolderByServerRelativeUrl('Shared Documents/dir1')/Files('captain-america-chris-evans.jpg')/$value" `as specified in Microsoft SharePoint Rest Service docs [Working with folders and files with REST](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest) download is working fine.

**Comment by vgrem** [comment]
The provided message  

> Server relative urls must start with SPWeb.ServerRelativeUrl

basically explains why this error occurs. `File.GetFileByServerRelativeUrl` method expects a server relative url to a file in the following format:

`/{site-path}/{folder-url}/{file-name}`

for example:

```
file = ctx.web.get_file_by_server_relative_url("/sites/site/Shared Documents/sample.docx")
ctx.load(file)
ctx.execute_query() 
```
