### ISSUE TITLE
Queries on sub sites yield wrong results

### ISSUE THREAD

**Issue by Aisbergg** [vgrem/Office365-REST-Python-Client#115]
This has been fixed in #111 before and got reintroduced again in the latest commits. The problem is the same as before. A `lists` query on a Sub `Web` object will yield the results of the Root Web. For example a site like this:

```plaintext
Root Web: [List 1, List 2, List 3]
└── Sub Web: [List 4, List 5]
```

The query `lists = sub_web.lists` will yield `[List 1, List 2, List 3]`, which is wrong.

Queries are created with URL from the context, which serves as a base URL. So basically the URL is created as follows: `query_url = context.url + "/_api/lists"`. Because the `context` never changes the `context.url` will be incorrect for queries on sub sites. Therefore I created a new context for every sub site in #111 to circumvent this issue. This got removed in the latest commits.

To print the sub sites recursively you added the parameter `parent_web_url` to `WebCollection` and it works on this type of collection:

https://github.com/vgrem/Office365-REST-Python-Client/blob/2a8b13c70c3294c597e7466570354ee66898c6a9/office365/sharepoint/web_collection.py#L7-L11

But all other types of collection do not have this kind of parameter and will therefore yield the wrong results. 

What do you think is the best approach for this? Creating a new context for sub sites or passing the parent web URL into the collections?

**Comment by vgrem** [comment]
Greetings!

i propose to close it since web context should be properly determined now, for example

```
https://{tenant}.sharepoint.com/{web_path}/_api/web/lists$top=2&$orderby=name
_________________________________________________/ __________/ __________________/
               |                                     |                  |
         service root URL                    resource path        query options

```
