### ISSUE TITLE
web.py package not working for python 3.6

### ISSUE THREAD

**Issue by pacodiaz2020** [vgrem/Office365-REST-Python-Client#122]
ModuleNotFoundError: No module named 'web'.

i am getting the above error using your api to access an excel file via SharePoint online.
can you please help? it looks like web.py is not in p3

**Comment by vgrem** [comment]
Greetings,
could you please elaborate, for instance, demonstrate how  file is get addressed?

**Comment by vgrem** [comment]
Propose to close since it could not be reproduced any longer.
