### ISSUE TITLE
500 Server Error in file_options.py

### ISSUE THREAD

**Issue by kristian-huber** [vgrem/Office365-REST-Python-Client#128]
I tried the code to change "Modified By" and I am getting a 500 Server Error.

![image](https://user-images.githubusercontent.com/22565648/66274253-9239db80-e84a-11e9-884d-2aca406de241.png)

**Comment by vgrem** [comment]
Greetings!

I'm afraid this scenario is **not** supported by _design_. The point is `Editor` along with some another fields, is considered as so called a _system metadata_, meaning it is not supposed to be updated directly. 

Having said that, the following approach still could be considered (but I cannot guarantee whether it succeed):

- set field `ReadOnlyField` attribute  to `False`
- update field value
- restore field `ReadOnlyField` attribute to original value  

**Example**

        # load field schema
        field_editor = list_item.parent_list.fields.get_by_internal_name_or_title("Modified By")
        ctx.load(field_editor)
        ctx.execute_query()

        # set read-only attribute to False
        if field_editor.properties['ReadOnlyField']:
            field_editor.set_property('ReadOnlyField', False)
            field_editor.update()
            ctx.execute_query()

        # update ModifiedBy field value
        list_item.set_property("EditorId", user_id)  
        list_item.update()
        ctx.execute_query()
