### ISSUE TITLE
How to create a folder in sharepoint?

### ISSUE THREAD

**Issue by SamiSipila** [vgrem/Office365-REST-Python-Client#129]
I looked through the examples but didn't see anything related to creating a folder. If you try to upload a file to non existent folder it errors, so I assume you have to create the folder first, but how?

**Comment by vgrem** [comment]
Greetings!

That's right, folder needs to be explicitly created first, here is an example on how to upload a file into a folder:   

    path = "../data/SharePoint User Guide.docx"
    # create file upload request
    file_info = FileCreationInformation()
    with open(path, 'rb') as content_file:
       file_info.content = content_file.read()
    file_info.url = os.path.basename(path)
    file_info.overwrite = True
    # submit a request to create a folder in a Library
    target_list = ctx.web.lists.get_by_title("Documents")
    target_folder = target_list.root_folder.folders.add("Archive_")
    ctx.execute_query()
    # submit upload request (e.g. upload a file into a folder)
    target_file = target_folder.files.add(file_info)
    ctx.execute_query()

Another operations with folder are also supported and covered in [`test_sharepoint_folder.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/tests/test_sharepoint_folder.py)

**Comment by bobroro** [comment]
I'm also trying to upload to a newly created folder and the only way I can achieve this is with the following but I don't understand why I can't use the `archive_folder` directly without calling `get_folder_by_server_relative_url` a second time:
`
temp_folder = ctx.web.get_folder_by_server_relative_url("Temp")
archive_folder = temp_folder.folders.add("Archive_")
ctx.execute_query()

target_folder = ctx.web.get_folder_by_server_relative_url("Temp/Archive_")
target_file = target_folder.upload_file(name, file_content)
ctx.execute_query()
`
