### ISSUE TITLE
Filter files based on params

### ISSUE THREAD

**Issue by domdinicola** [vgrem/Office365-REST-Python-Client#131]
Do you think is possible given a folder, to get all file matching some filters?
I saw is possible to filter Items (Related to PR https://github.com/vgrem/Office365-REST-Python-Client/issues/100), but would be great to filter Files as well.

something like:
```
filters = (('filter_name', 'operator', 'value'),)
folder.files(filters)
```

**Comment by vgrem** [comment]
Greetings,

positive, filtering is supported for collections including files collection, for example:

`files = ctx.web.get_folder_by_server_relative_url("{folder-url}").files.filter("Name eq 'Guide.docx'")`

where the filter  expression  follows the syntax of  OData `$filter` option (refer [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#odata-query-operators-supported-in-the-sharepoint-rest-service) for a more details)


Here is an example on how to _filter files by file name_:

```
file_name = "Book.xlsx"
files = ctx.web.get_folder_by_server_relative_url("/Shared Documents").files.filter("Name eq '{0}'".format(file_name))
ctx.load(files)
ctx.execute_query()
for file in files:
   print(file.properties["Name"])
```

**Comment by domdinicola** [comment]
Thanks for you answer!

I still have an issue... when filtering items I'm able to filter on "custom" columns (column I added in the DL) instead I'm not able to do that when filtering files... am I doing anything wrong or this functionality is not available?
 
```
        # FILES FROM LIST ITEM IMPLEMENTATION
        list_object = self.context.web.lists.get_by_title(list_title)
        files = list_object.get_items().filter(querystring)

        # FILES FROM FOLDER IMPLEMENTATION
        folder = self.get_folder(list_title)
        files = folder.files.filter(querystring)
```

**Comment by domdinicola** [comment]
@vgrem any update on this?

**Comment by vgrem** [comment]
@domdinicola , it depends on a few factors: 
    -   via what endpoint file collection  is retrieved
    -   whether metadata (for which filter is applied) is associated with `ListItem` or `File`/`Folder` entity
