### ISSUE TITLE
No list item delete (sharepoint)?

### ISSUE THREAD

**Issue by revelation1** [vgrem/Office365-REST-Python-Client#133]
I see SharePoint List class has delete_object() but I think that deletes the whole list?  How do I delete a list item?

Thanks for any help on this.

**Comment by vgrem** [comment]
Sorry for the late response,  `ListItem` resource could be deleted like this:

```
target_list = ctx.web.lists.get_by_title("Contacts_Large")
item_to_delete = target_list.get_item_by_id(item_id)
item_to_delete.delete_object()
ctx.execute_query()

```
