### ISSUE TITLE
Question: Get SharePoint user id

### ISSUE THREAD

**Issue by Karthickraju2690** [vgrem/Office365-REST-Python-Client#136]
I have the below rest api query to fetch SharePoint online's  user id, but not sure how can I execute with the library. 

https://url/sites/list/_api/Web/siteusers#?$filter=substringof('|userloginname',LoginName) eq true

Can you share example on how to run above REST api query?

**Comment by vgrem** [comment]
Surely, `$filter` along with [another OData query operations](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)  are supported. 
Here is an example:

```
client = ClientContext(url, ctx_auth)
user_name = user.properties['UserPrincipalName']
users = client.web.site_users\
            .filter("substringof('|{0}',LoginName) eq true".format(user_name))
client.load(users)
client.execute_query()

```

**Comment by Karthickraju2690** [comment]
May I know how did you read **user** object? I tried to read it by iterating through Group object, but does not look correct. Can you share how you read user?

**Comment by Karthickraju2690** [comment]
Thank you Vadim. I could read the details now. Have used your code like below:

        client = ClientContext(url, context_auth)
        users = client.web.site_users\
                    .filter("substringof('|{0}',LoginName) eq true".format('LoginName'))
        client.load(users)
        client.execute_query()
        for user in users:
            print('User : {0}, Id: {1}'.format(user.properties["Title"], user.properties["Id"]))

Again, thanks much for your help

**Comment by sachinez731** [comment]
Hello, I tried to use above code. Two errors,
1) 

  File "C:\Users\ez731\Documents\_hopper\Tracker_prefill.py", line 87, in <module>
    users = client.web.site_users\

AttributeError: 'Web' object has no attribute 'site_users'

2) When I uncommented -- from office365.runtime.utilities.request_options import RequestOptions


  File "C:\Users\ez731\Documents\_hopper\Tracker_prefill.py", line 16, in <module>
    from office365.runtime.utilities.request_options import RequestOptions

ModuleNotFoundError: No module named 'office365.runtime.utilities.request_options'

Can you please guide me

**Comment by iglimanaj** [comment]
Regarding the first point, try `siteUsers` instead of `site_users`

**Comment by sachinez731** [comment]
Yeap That helps! Thanks
