### ISSUE TITLE
Question: SharePoint online - How to update Multichoice field of list item? 

### ISSUE THREAD

**Issue by Karthickraju2690** [vgrem/Office365-REST-Python-Client#137]
I am able to create list item on **SharePoint online**. But, I couldn't update Multichoice item. 

Per requirement, Multichoice field values should not be passed while creating list item. so, did not check whether it's working while creating list item.

Below is the code developed with the help of library documentation:

            app_settings = {
                'url': 'url',
                'client_id': 'clientid',
                'client_secret': 'clientsecret'
             }

             context_auth = AuthenticationContext(url=app_settings['url'])
             context_auth.acquire_token_for_app(client_id=app_settings['client_id'], client_secret=app_settings['client_secret'])
             context = ClientContext(app_settings['url'], context_auth)
            
             request = ClientRequest(context)
             print(request)
             options = RequestOptions("{0}/web/lists/getbyTitle('{1}')/items({2})".format(url, list_title, item_id))
             options.set_header('Accept', 'application/json; odata=verbose')
             options.set_header('Content-Type ', 'application/json; odata=verbose') 
             options.set_header('IF-MATCH', '*')
             options.set_header('X-HTTP-Method', 'MERGE')
             options.data = {'__metadata': { 'type': 'SP.Data.MyListItem' },
                               'MultiChoiceField':{
                                   '__metadata' : {'type' : 'Collection(Edm.String)' },
                                   'results': ['value1', 'value2']
                                   }}
             options.method = HttpMethod.Post
             print("Updating list item...")
             request.execute_request_direct(options)
             print("Task has been successfully [updated]")

Code runs fine and says Task has been successfully updated, but values are not selected for the list item. 

I also tried with below code, but couldn't be successful:

             # Passing fetched item by id and add properties to it.
             item = target_list.get_item_by_id(item_id)
             item.properties.update({
                               'MultiChoiceField':{
                                  '__metadata' : {'type' : 'Collection(Edm.String)' },
                                  'results': ['value1', 'value2']}
                                       })
             item.update()
             ctx.execute_query()

Can you share the example on how to update the Multichoice field of list item? 

Thanks in advance.

**Comment by vgrem** [comment]
Greetings,

the latest version ( [`2.1.10`](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.1.10) or above)  introduces a support (no need to manually construct  field payload)  for SharePoint built-in fields, the following example demonstrates how to update list item and set multi choice value:


```
multi_choice_value = FieldMultiChoiceValue(["In Progress"])
item_to_update.set_property("TaskStatuses", multi_choice_value)
item_to_update.update()

```
