### ISSUE TITLE
howto create a library in sharepoint

### ISSUE THREAD

**Issue by niconil** [vgrem/Office365-REST-Python-Client#145]
i would like to create a library:

i tried the two lines below (my locale is french to explain the string 'Contenu du site'):

ctx.web.lists.get_by_title("Contenu du site").root_folder
target_library = ctx.web.folders.add("myNewLibrary")

but it's not working ...

i've found here (https://sharepoint.stackexchange.com/questions/137560/create-a-document-libary-with-sharepoint-rest-api) a low level request. But howto do it with office365-REST-Python-Client ?

url: http://site url/_api/web/lists
method: POST
body: { '__metadata': { 'type': 'SP.List' }, 'AllowContentTypes': true, 'BaseTemplate': 101,
 'ContentTypesEnabled': true, 'Description': 'My doc. lib. description', 'Title': 'Test' }
Headers: 
    Authorization: "Bearer " + accessToken
    X-RequestDigest: form digest value
    accept: "application/json;odata=verbose"
    content-type: "application/json;odata=verbose"
    content-length:length of post body

**Comment by niconil** [comment]
my low_level solution (using ClientRequest)
[but i would like to have the good answer in two lines using ctx.web ....]

```
        body = {
            '__metadata': { 'type': 'SP.List' },
            'AllowContentTypes': True,
            'BaseTemplate': 101,
            'ContentTypesEnabled': True,
            'OnQuickLaunch': True,
            'Description': library,
            'Title': library
        }

        request = ClientRequest(ctx)
        options = RequestOptions("{0}/_api/web/lists".format(url_site))
        options.set_header('Accept', 'application/json; odata=verbose')
        options.set_header('Content-Type', 'application/json;odata=verbose')
        options.data = body
        options.method = HttpMethod.Post
        rep = request.execute_request_direct(options)
```

**Comment by vgrem** [comment]
Greetings!

List (and library) creation is also supported. 

In your  example

ctx.web.lists.get_by_title("Contenu du site").root_folder
target_library = ctx.web.folders.add("myNewLibrary")

the folder is getting created. The following example demonstrates how to _create a library_ :

```
list_properties = ListCreationInformation()
list_properties.AllowContentTypes = True
list_properties.BaseTemplate = ListTemplateType.DocumentLibrary
list_properties.Title = "--library title goes here--"
list_to_create = ctx.web.lists.add(list_properties)
ctx.execute_query()
```

Refer [`test_sharepoint_list.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/tests/test_sharepoint_list.py) for a more details on how to perform CRUD operations against `List `
