### ISSUE TITLE
Is it possible to add a user to a group?

### ISSUE THREAD

**Issue by kristian-huber** [vgrem/Office365-REST-Python-Client#147]
I see creating groups and printing off the users. How would I add or remove a user from a group?

**Comment by kristian-huber** [comment]
I was able to make a post request to add someone to a group with the following lines of code:

![image](https://user-images.githubusercontent.com/22565648/69981272-02d63f00-1500-11ea-974d-dbe92dcd59c0.png)

However I get a 403 FORBIDDEN error now

**Comment by vgrem** [comment]
Greetings,

your approach  looks correct, at least i cant spot anything which points to provided error, maybe non existent group id is specified?   

                
Anyway it is supported now (_latest commit_) to add user into a group as demonstrated below:

```
test_login_name = "i:0#.f|membership|mdoe@mediadev8.onmicrosoft.com"
target_group = self.context.web.site_groups.get_by_name("Communication site Visitors")
user = target_group.users.add_user(test_login_name)
self.context.execute_query()
```

Refer [`test_sharepoint_group.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/tests/test_sharepoint_group.py) for a details
