### ISSUE TITLE
can not set metadata for a file in sharepoint

### ISSUE THREAD

**Issue by Simplici** [vgrem/Office365-REST-Python-Client#150]
I try to set metadata to a file in sharepoint, but i can not make it work.

`list_item = file.listitem_allfields  # get associated listItem
list_item.set_property("EditorId", user_id)  # update ModifiedBy field value 
list_item.update()
ctx.execute_query()`

and list_item.properties returns {} which seems unnormal.

this code runs without error, but the metadata of the file is not updated neither.

**Comment by SmartScanCloud** [comment]
Hi @Simplici,

You can try with this snipped:

```
        list_item = file_new.listitem_allfields
        ctx.load(list_item)
        ctx.execute_query()
        list_item.set_property('FIELD_NAME', 'FIELD_VALUE')
        list_item.update()
        ctx.execute_query()
```

Note: The field names usually follow the internal names convention for Sharepoint (spaces are encoded as well): https://abstractspaces.wordpress.com/2008/05/07/sharepoint-column-names-internal-name-mappings-for-non-alphabet/

**Comment by ivang1811** [comment]
This doesnt seem to work for me what does file. refer to is it a file object as thats what im trying with and its giving me an error that a
