### ISSUE TITLE
Can not install on windows by Office365-REST-Python-Client==2.1.4

### ISSUE THREAD

**Issue by 549982170** [vgrem/Office365-REST-Python-Client#151]
Can not install on windows by Office365-REST-Python-Client==2.1.4

**Comment by 549982170** [comment]
change
 with open("README.md", "r") as fh:
to：
with open("README.md", "r", encoding='UTF-8') as fh:  
on setup.py line 8.

**Comment by vgrem** [comment]
Greetings,

thanks for catching this one, it has been resolved in [`2.1.6` release](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.1.6)
