### ISSUE TITLE
Unable to import office365 package

### ISSUE THREAD

**Issue by Mark531** [vgrem/Office365-REST-Python-Client#155]
Hello,

I have successfully installed Office365-REST-Python-Client on python 3.6.5 but cannot import the office365 package:

> (env36) C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts>pip install Office365-REST-Python-Client
> Requirement already satisfied: Office365-REST-Python-Client in c:\users\me\appdata\local\continuum\anaconda3\lib\site-packages (2.1.4)
> Requirement already satisfied: requests in c:\users\me\appdata\local\continuum\anaconda3\lib\site-packages (from Office365-REST-Python-Client) (2.22.0)
> ...
> Requirement already satisfied: pycparser in c:\users\me\appdata\local\continuum\anaconda3\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=1.1.0->adal->Office365-REST-Python-Client) (2.19)
> 
> (env36) C:\Users\me\AppData\Local\Continuum\anaconda3\Scripts>python
> Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import office365
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'office365'

What can be the problem?

Regards,
Mark

**Comment by beliaev-maksim** [comment]
@Mark531 
can you check that package was properly installed to the required version?

I would explicitly call:
`python -m pip install Office365-REST-Python-Client`

**Comment by Mark531** [comment]
Sorry, this post dates from 2019... Since I didn't receive any reply, I used another library.
