### ISSUE TITLE
Bug in File.py in sharepoint module

### ISSUE THREAD

**Issue by asukumar91** [vgrem/Office365-REST-Python-Client#162]
Inside CopyTo def which belongs to File
![Corrected code snippet](https://user-images.githubusercontent.com/60119814/72765705-ea51ed80-3c41-11ea-8472-02135e966718.png)

.py of Sharepoint package has some bug. 

For copyto postmethod the parameter should be "strNewUrl" instead of "newUrl". 

I.e In line #67 - "newurl" must be replaced with "strNewUrl" for the copyto funtion to work.

**Comment by vgrem** [comment]
Thanks for catching this bug, it has been resolved
