### ISSUE TITLE
An error occurred while retrieving token: AADSTS50126: Error validating credentials due to invalid username or password.

### ISSUE THREAD

**Issue by bansalpulkit** [vgrem/Office365-REST-Python-Client#170]
Hi

i am running the below code and get an error for invalid credentials:
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext

site_url = 'url'
username = 'my-user@domain.com'
password = 'Password'

ctx_auth = AuthenticationContext(url = site_url)
if ctx_auth.acquire_token_for_user(username, password):
    ctx = ClientContext(site_url, ctx_auth)
else:
  print(ctx_auth.get_last_error())

I believe this might be due to my organization using SSO with Okta for SharePoint authentication, is there a way to fix the issue. 

Thanks
Pulkit

**Comment by vgrem** [comment]
Greetings!

The support for SAML-based federated authentication with SharePoint Online has been added (version `2.1.7` or above) meaning it should work as expected now with Okta identity provider.
If not, please report back.  


> Note:  since the new version  has not yet been released to PyPi, it needs to be installed from GitHub  instead at the moment, for example:
> 
> `pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`
> 

Vadim
