### ISSUE TITLE
404 error retrieving file property from list

### ISSUE THREAD

**Issue by JohnAdders** [vgrem/Office365-REST-Python-Client#177]
I've had some working code with version 2.1.3 that breaks with version 2.1.5 and up.

The code pulls down data from some sharepoint lists using 

ctx.web.lists.get_by_title(list_name)

then iterates over items and the iterates over properties.

For the file properties I'm calling ctx.load and ctx.execute to fill out the File object..

With 2.13 during this filling for the File properties I get urls like 
/sites/XXXX/_api/Web/Lists(guid'YYYYYY')/Items(ZZZ)/ParentList/getItemById(ZZZ)/File
which work OK.

With 2.1.5 I get urls like
/sites/XXXX/_api/Web/lists/GetByTitle('ListName')/items/getItemById(ZZZ)/File
which gives a 404 with "Cannot find resource for the request getItemById."

Am I using the wrong calls somewhere?

Thanks for nay help.

**Comment by vgrem** [comment]
Greetings!

thank you for catching this bug,  it has been resolved.

Vadim
