### ISSUE TITLE
Create Share point team site instead of communication site

### ISSUE THREAD

**Issue by vamsivks** [vgrem/Office365-REST-Python-Client#178]
I just want to know how to create team site using rest-python-client

whenever I'm creating a site using WebCreationInformation it's creating communication site in Sharepoint . can anyone give me a suggestion?

**Comment by vamsivks** [comment]
Along with above can you provide some example for a document library and folder creation inside team site with file upload?

**Comment by vgrem** [comment]
Greetings,

the support for provisioning of modern has been introduced in the [latest change](https://github.com/vgrem/Office365-REST-Python-Client/commit/4b32bf0a7fce3fa246c820e75832394e087551fe)


**Methods**

- create Team site:  `GroupSiteManager.create_group_ex(display_name, alias, is_public, optional_params)`

- create Communication site:  `SPSiteManager.create(request)`  where `request` is of `SPSiteCreationRequest` type





**Examples**


Create a [Team Site ](https://support.office.com/en-us/article/create-a-team-site-in-sharepoint-ef10c1e7-15f3-42a3-98aa-b5972711777d)

```
client = ClientContext(url, ctx_auth)
site_manager = GroupSiteManager(client)
info = site_manager.create_group_ex("Team Site", "teamsite", True, None)
client.execute_query()
```



Create a [Communication site ](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest)


```
client = ClientContext(url, ctx_auth)
site_manager = SPSiteManager(client)
request = SPSiteCreationRequest("CommSite", "https://contoso.sharepoint.com/sites/commsite")
response = site_manager.create(request)
client.execute_query()

```

**Comment by vamsivks** [comment]
Hi,

isn't updated in pip package?

**Comment by vamsivks** [comment]
@vgrem Can you give me example for a document library, folder and file upload? because of old code not working

**Comment by vgrem** [comment]
@vamsivks , not yet, but planned to be released this week.
Meanwhile, the latest version could be installed from GitHub:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`
