### ISSUE TITLE
Create Document library, folders and upload file in Team sites in sharepoint instead of communication site?

### ISSUE THREAD

**Issue by vamsivks** [vgrem/Office365-REST-Python-Client#179]
@vgrem Can you give me an example for a document library, folder and file upload in team site rather than communication site? because of old code only supporting communication site

**Comment by vgrem** [comment]
That's pretty much the same, operations stays the same no matter whether is a modern team site or classic one. Once the client is initialized against a modern site:

```
ctx = ClientContext.connect_with_credentials("https://contoso.sharepoint.com/sites/teamSite",
                                             UserCredential(username,password))
```


a _document library_ could be created like this:

```
properties = ListCreationInformation()
properties.BaseTemplate = ListTemplateType.DocumentLibrary
properties.Title = "Team Documents"
target_lib = ctx.web.lists.add(properties)
ctx.execute_query()

```


There is a plenty of examples for another operations.
