### ISSUE TITLE
When I pip install, FieldType.py and view_create_information.py aren't installed

### ISSUE THREAD

**Issue by StephYurk** [vgrem/Office365-REST-Python-Client#181]

**Comment by vgrem** [comment]
Greetings!

the support for those resources has been introduced recently and the latest release (`v2.1.8`) is not yet available via pip.

Meanwhile, the [latest version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.1.8) could be installed from GitHub:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`
