### ISSUE TITLE
Sharepoint List get_items() errors itterating past 100 items

### ISSUE THREAD

**Issue by revelation1** [vgrem/Office365-REST-Python-Client#187]
```
items = list.get_items()
 ctx.load(items)
 ctx.execute_query()
```

This works: 
`items[99].properties["ID"]`

This errors:
`items[100].properties["ID"]`

Error:

>   File "\office365\runtime\client_object_collection.py", line 48, in __iter__
>     self.__next_query_url = payload["next"]
> TypeError: 'NoneType' object is not subscriptable

**Comment by revelation1** [comment]
reverted to 2.1.5 from 2.1.7 and now it works.

**Comment by vgrem** [comment]
Greetings!

thanks for catching this bug, starting from `2.1.8`  _lazy loading support for collections_ has been fixed & refactored but this release has not been published yet in PyPI (working on get it published at the moment)  

Meanwhile the latest version could be grabbed from GitHub:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`

**Comment by professor042** [comment]
Hasn't been published at this point where it can be installed from pip to a certain version or is it unavailable still? I downloaded the most recent version from pip (2.3.16) and I had the same error trying to go past 100 items.
