### ISSUE TITLE
Bad request for url error

### ISSUE THREAD

**Issue by kelifine** [vgrem/Office365-REST-Python-Client#188]
Hi,

I'm getting the following error while trying to move a file into another folder. 

Here's my code:

`folder = ctx.web.get_folder_by_server_relative_url('folder_name')
file = folder.files
ctx.load(files)
ctx.execute_query()
for f in files:
file_url = f.properties['ServerRelativeUrl']
path, filename = os.path.split(file_url)
new_url = '/'.join([path, 'New_Folder', file_name])
f.moveto(new_url, 1)
ctx.execute_query()
`
Here's the error:

ClientRequestException: None, None, "400 Client Error: Bad Request for url:...", 

The code worked once but has since stopped working. Can you help?

**Comment by vgrem** [comment]
Greetings,

seems to be working as expected against the latest version (`2.1.8`), as demonstrated below where file is moved under sub folder `Archive`:

```
file = ctx.web.get_file_by_server_relative_url("/sites/team/Shared Documents/sample.xlsx")
ctx.load(file)
ctx.execute_query()

file_url = file.properties['ServerRelativeUrl']
file.moveto('/sites/team/Shared Documents/Archive/sample.xlsx', 1)
ctx.execute_query()

```

Please make sure the target folder exist and a _server relative url_ is provided for `File.moveTo` method

**Comment by vgrem** [comment]
Considered as resolved and propose to close this one
