### ISSUE TITLE
Version history

### ISSUE THREAD

**Issue by florinmihut** [vgrem/Office365-REST-Python-Client#193]
Hi,

I was looking to for a way to:
a. Look at the history of an item (or get the history - aka version control - of a list of items) 
b. iterate over the history and if I find a specific version download it.

I saw that the API is there:
https://my.sharepoint.com/sites/mysite/_api/Web/lists/GetByTitle('My AwesomeList')/items(22)/versions

But I did not find the respective functions in the python client. 

You get back the list of the stored versions in the version control with the respective metainformation. That is what I am interested in.
Is this possible?

Best regards,
Florin

**Comment by vgrem** [comment]
Since in the latest version `FileVersion` resource has been introduced, file versions could be retrieved like this:


```
file = ctx.web.lists.get_by_title(list_title).get_item_by_id(item_id).file
file_with_versions = file.expand(["Versions"])  #retrieve file along with versions
ctx.load(file_with_versions)
ctx.execute_query()
for v in file_with_versions.versions:
    print(v.url)  # print version url
```

**Comment by sant3e** [comment]
I am having this issue as well. The block provided above does not return anythin.
I need to get the history for each id (after i get that i will 'filter" for a only a change in a particular column in the list)
