### ISSUE TITLE
Getting list of all files modified recently

### ISSUE THREAD

**Issue by brake21** [vgrem/Office365-REST-Python-Client#194]
@vgrem Can I use the library to get the list of all files modified last few minutes ? If so, could you please guide me.

Thanks

**Comment by vgrem** [comment]
Greetings,

for that matter you could consider the following options to filter collection of items based on the specified query:  

- via [`List.GetItems` method](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee539544%28v%3doffice.14%29) along with `CamlQuery` provided

- via ` $filter` query option, refer [Select items to return](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#select-items-to-return) for a details



The following example demonstrates how to retrieve items modified for the last 15 minutes: 

```
lib = ctx.web.lists.get_by_title(list_title)

# construct a query
caml_query = CamlQuery()
offset = datetime.datetime.now() - datetime.timedelta(minutes=15)
caml_query.ViewXml = """<View Scope='RecursiveAll'>
    <Query>
        <Where>
            <Geq>
                <FieldRef Name='Modified' />
                <Value IncludeTimeValue='True' StorageTZ='TRUE' Type='DateTime'>{0}</Value>
            </Geq>
        </Where>
    </Query>
    <RowLimit>5000</RowLimit>
</View>""".format(offset.isoformat() + 'Z')

items = lib.get_items(caml_query)
ctx.load(lib)
ctx.execute_query()
```

**Comment by brake21** [comment]
Thanks for the reply. Was helpful.
