### ISSUE TITLE
Caml query builder examples

### ISSUE THREAD

**Issue by vpaterno** [vgrem/Office365-REST-Python-Client#196]
Any docs on how to use the Caml query builder class in camlquery_builder.py? Specifically looking for multiple and/or contains nodes for the same or multiple fields in a list. Thanks!

**Comment by domdinicola** [comment]
@vpaterno you can look here: https://github.com/vgrem/Office365-REST-Python-Client/pull/228/files

**Comment by vgrem** [comment]
Closing this one since Caml query builder is no longer part of the library, only standard API is covered by the library.

**Comment by domdinicola** [comment]
@vpaterno that has been moved to https://github.com/domdinicola/sharepoint-rest-api

**Comment by fabrice-chezeaux** [comment]
I'm attempting to write a [simple library](https://github.com/fabrice-chezeaux/caml-query-builder) to build a Caml query to cover common use cases and only with standard API.

**Comment by domdinicola** [comment]
@fabrice-chezeaux we can talk to check if we can use one project or make your a dependency of mine!

**Comment by fabrice-chezeaux** [comment]
We can talk, of course ! Feel free to contact me.
