### ISSUE TITLE
possible to disbale versioning in sharepoint library

### ISSUE THREAD

**Issue by niconil** [vgrem/Office365-REST-Python-Client#199]
i ask you (in #145) how to create a library with your library. it works fine thank you.
Is it possible to disable the versioning as an option for this library ?

when i search over forums i found this powershell script
https://answers.microsoft.com/en-us/msoffice/forum/all/disable-versioning-in-sharepoint-online-library/fd30057c-3103-4091-9676-71633641f100
that let me hope is it possible ...

**Comment by vgrem** [comment]
Per [documentation](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj244795(v%3Doffice.15)):

> `List.enableVersioning` property - Gets or sets a value that specifies whether historical versions of list items and documents can be created in the list.


Here you go:

```
lib = ctx.web.lists.get_by_title(library_title)
lib.set_property('EnableVersioning', False)
lib.update()
ctx.execute_query()

```
