### ISSUE TITLE
sharepoint.client_context: Removing queries from a ClientContext

### ISSUE THREAD

**Issue by stardust85** [vgrem/Office365-REST-Python-Client#204]
Hello @vgrem et al.,

I found a cornercase using sharepoint's ClientContext. When I add there some queries via various methods of various classes and then call execute_query() and it raises an error, I cannot use that instance of ClientContext anymore. Because it is then not removed from the query queue. 

A workaround is to create a new ClientContext, but looks a bit unnatural to me.

Proposed ways how to fix it:  adding a method remove_queries, that will remove all queries from the context

What do you think about that?

an example code:
```python3
...

client_context = ClientContext(self._site_url, ctx_auth)
file: File = self.get_some_file()
try:
   file.checkout()
   client_context.execute_query()
except ClientRequestException:
   if ignore = True:
      logger.warning('ignoring checkout fail as instructed')
   else:
      raise
file.write(content=new_content)
file.checkin(comment='', checkin_type=1)   
file.execute_query()     # here checkout is called again
```

**Comment by vgrem** [comment]
Grettings @stardust85 

indeed, i would say instantiating another `ClientContext` should be generally avoided. 

> Maybe except some specific cases, e.g.  when _different site collections_ needs to be targeted at the same time within a tenant and for that matter we have `ClientContext.clone(from_site_url)` method    

The good news, your scenario is supported and if you prefer manipulate internal `queries` queue, the following example demonstrates how to accomplish it: 


```
ctx = ClientContext.connect_with_credentials(url, UserCredential(username, password))

# 1.lets build a query
current_user = ctx.web.current_user
ctx.load(current_user)

# 2. and lets remove the query 
request = ctx.get_pending_request()  # get underlying request class
qry = request.queries.pop()   #removes the query 

# note, no "get current user" query will be submitted to the server here 
file.execute_query()
```


> Since `ClientRequest.queries` is a `list` structure, all  inbuilt functions are supported
