### ISSUE TITLE
Download the files listed using a query

### ISSUE THREAD

**Issue by brake21** [vgrem/Office365-REST-Python-Client#205]
My Use-case is to list the items modified last 15 minutes and then download them to the local folder. I have already raised a question about listing the items modified. Could you please help me  #downloading the files to the local folder ?

**Comment by brake21** [comment]
https://github.com/vgrem/Office365-REST-Python-Client/issues/194

**Comment by pobs93** [comment]
Morning

I just GetDocumentById how to do it.

I posted and example here #212 

I hope it helps.

**Comment by vgrem** [comment]
Propose to close this one since it was mentioned as resolved.
