### ISSUE TITLE
Unable to conect to Sharepoint(acquire_authentication_cookie error if federated)

### ISSUE THREAD

**Issue by liuliqiu** [vgrem/Office365-REST-Python-Client#210]
I have been been trying connect with some special Sharepoint account use the 2.1.9 version release.

```
from office365.runtime.auth.authentication_context import AuthenticationContext
ctx_auth = AuthenticationContext(url)
ctx_auth.acquire_token_for_user(account, password)
```
It fails with log
```
[17/Jun/2020 05:20:19] DEBUG [none] [urllib3.connectionpool:_make_request:428] https://somehost.sharepoint.com:443 "HEAD /_vti_bin/idcrl.svc HTTP/1.1" 401 0
[17/Jun/2020 05:20:19] ERROR [none] [office365.runtime.auth.saml_token_provider.SamlTokenProvider.acquire_authentication_cookie:acquire_authentication_cookie:214] An error occurred while retrieving auth cookies from https://somehost.sharepoint.com/_vti_bin/idcrl.svc
```

Then i try the account with PowerShell.
```
$Context = New-Object Microsoft.SharePoint.Client.ClientContext($SiteURL)
$SitePassword = ConvertTo-SecureString $SitePassword -AsPlainText -Force
$Creds = New-Object Microsoft.SharePoint.Client.SharePointOnlineCredentials($SiteUser,$SitePassword)
$Context.Credentials = $Creds
$web = $Context.Web
$Context.Load($web)
$Context.ExecuteQuery()
```
And i find the request like

```
GET https://somehost.sharepoint.com/_vti_bin/idcrl.svc/ HTTP/1.1
Authorization: BPOSIDCRL t=EwDoAk6hBwA...gC&p=
X-IDCRL_ACCEPTED: t
Host: somehost.sharepoint.com
```

It's use `GET` not `HEAD`, and url endswith `/`, and header not contains "Content-Type".
so i modify the python source code, and it works.
and i find a reply on https://sharepoint.stackexchange.com/questions/222917/rest-authentication-to-online-sharepoint use GET.

**Comment by liuliqiu** [comment]
I modify the code in the branch
https://github.com/liuliqiu/Office365-REST-Python-Client/tree/fix-bug-acquire-authentication-cookie-error
base on tag 2.1.9

**Comment by vgrem** [comment]
Greetings @liuliqiu, 

thank you for tracking it down and for the PR, looks solid!

Indeed, `_vti_bin/idcrl.svc`  endpoint expects the presence of `BPOSIDCRL` header if federated account is involved.

**Comment by vgrem** [comment]
The change has been applied in the latest commit
