### ISSUE TITLE
Unable to connect to sharepoint via appid / client_secret

### ISSUE THREAD

**Issue by plooff** [vgrem/Office365-REST-Python-Client#213]
Hi,
It looks like the current version on git is unable to login to sharepoint via appid / client_secret
I get the following error when I call : 
`ctx_auth = AuthenticationContext(siteUrl)
 if ctx_auth.acquire_token_for_app(appid, client_secret):`

`dictionary keys changed during iteration`

> $ python --version
> Python 3.8.3
> $ pip list | grep Office
> Office365-REST-Python-Client   2.1.9

Please note that I installed Office365-REST-Python-Client via 
`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`
If I use the 'regular' `pip install Office365-REST-Python-Client` and the previous version (2.7 I believe) the above code works fine

**Comment by vgrem** [comment]
Greetings!

Thanks for catching it, `AuthenticationContext.acquire_token_for_app` return type annotation has been changed, which caused this behavior.
But in the latest commit it has been restored for backward compatibility.


Btw, in the latest version, authenticated client could be instantiated like this (no need to resort to `AuthenticationContext`):

```
client_credentials = ClientCredential(client_id="--client id goes here--",
                                      client_secret="-- client secret goes here--")

ctx = ClientContext(site_url).with_credentials(client_credentials)
```

or if you prefer to validate whether authentication was successful beforehand:

```
ctx = ClientContext.connect_with_credentials(site_url, client_credentials) 
if not ctx.authentication_context.acquire_token():
     print ("Authentication failed")
```
