### ISSUE TITLE
FederatedSAML.xml not found in 2.1.10

### ISSUE THREAD

**Issue by liuliqiu** [vgrem/Office365-REST-Python-Client#216]
I try version 2.1.10, raise Exception
```
[Errno 2] No such file or directory: '.../runtime/auth/providers/templates/FederatedSAML.xml'
```
and I found in setup.py
```
    package_data={
        'office365': ["runtime/auth/SAML.xml", "runtime/auth/RST2.xml", "runtime/auth/FederatedSAML.xml"]
    }
```
and i think here need move into directory "providers/templates"

**Comment by vgrem** [comment]
Thanks for catching it, precisely the case, PR has been merged.

**Comment by Simplici** [comment]
@vgrem when can this correction be released? may you make a minor release to correct this issue?

**Comment by vgrem** [comment]
@Simplici, here you go: [`v 2.1.10.1`](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.1.10.1)

**Comment by domdinicola** [comment]
@Simplici  updated package is in pypi as well https://pypi.org/project/office365-rest-client/

**Comment by liuliqiu** [comment]
> @Simplici updated package is in pypi as well https://pypi.org/project/office365-rest-client/

office365-rest-client==2.1.10.1 will raise Exception

```
>>> from office365.runtime.auth.authentication_context import AuthenticationContext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liuliqiu/.pyenv/versions/test/lib/python3.8/site-packages/office365/runtime/auth/authentication_context.py", line 1, in <module>
    from office365.runtime.auth.clientCredential import ClientCredential
ModuleNotFoundError: No module named 'office365.runtime.auth.clientCredential'
```
I find files `ClientCredential.py` and `UserCredential.py` under directory `/office365/runtime/auth/` not `clientCredential.py`

**Comment by domdinicola** [comment]
@liuliqiu please check v2.1.10.2

**Comment by liuliqiu** [comment]
> @liuliqiu please check v2.1.10.2

It's OK, thank you!
