### ISSUE TITLE
New releases on pypi

### ISSUE THREAD

**Issue by pingunaut** [vgrem/Office365-REST-Python-Client#218]
Thanks a lot for this great library!
Latest release on pypi seems to be 2.1.7.post1, however a lot of new stuff is already implemented and released since then here on Github.
Will these releases also be published to pypi?

**Comment by pingunaut** [comment]
Ah, sorry... found #75 and can answer the quesion my self :)

**Comment by vgrem** [comment]
Affirmative, this is the only reason why why pypi has not been updated yet.

**Comment by domdinicola** [comment]
https://pypi.org/project/office365-rest-client/ is "for now" giving the chance to use the updated version until pypi transfer ownership is completed
