### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kgadek** [vgrem/Office365-REST-Python-Client#22]
I want to discuss adding logging to the system.

## Use-case
The script I have failed once. Stacktrace points at `saml_token_provider.py` suggesting that the cookie from sharepoint was incorrect. I'd love to see more logs about this.

## Proposal
- use `logging` module throughout the library to trace variables and function calls,
- function calls get `logging.INFO` level, while internal variables `logging.debug` unless they contain any secrets,
- register new logging level `logging.DEBUG_SECRETS=5` to log variables containing secrets. Very useful e.g. to inspect the cookies / SAML protocol.

**Comment by kgadek** [comment]
To expand proposal, I've put logging into `saml_token_provider` in my fork [[1](https://github.com/kgadek/Office365-REST-Python-Client/commit/3f1286b165d6ae1623d8a404232f9b884b376a8f)]. The code tries to behave as nicely as possible, e.g.
- there is no module-level import [[2](https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/#do-not-get-logger-at-the-module-level-unless-disableexistingloggers-is-false)],
- it doesn't register the new level (this shall be the responsibility of the caller).

I will expand `README` to include logging guide a bit later.

Does this look okay?

**Comment by vgrem** [comment]
Greetings,

this is indeed a good idea!  And totally support the idea of utilizing[ logging module](https://docs.python.org/2/library/logging.html)  


Regarding the implementation i have a few suggestions:

1) maybe it make sense to introduce a Logger class to hide all the logger related implementation details such as `LOGGING_SECRET_LVL` and etc., similar to [this ](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/84adff4b2b2ebb9a2e6849802e507037a28c341d/adal/log.py)


2) another one concerns the usage, in particular how the logger is getting utilized, for example compare the following two examples:  

a)

```
def get_authentication_cookie(self):
          """Generate Auth Cookie"""
        logger = self.inst_logger.getChild('get_authentication_cookie')
        logger.log(LOGGING_SECRET_LVL, 'self.FedAuth: %s', self.FedAuth)
        logger.log(LOGGING_SECRET_LVL, 'self.rtFa: %s', self.rtFa)
        return 'FedAuth=' + self.FedAuth + '; rtFa=' + self.rtFa
```

b)

```
def get_authentication_cookie(self):
          """Generate Auth Cookie"""
        self._logger.debug( 'self.FedAuth: %s  self.rtFa: %s', self.FedAuth, self.rtFa)
        return 'FedAuth=' + self.FedAuth + '; rtFa=' + self.rtFa
```
In my opinion the second one looks a bit "cleaner"?

Best,
Vadim

**Comment by kgadek** [comment]
- Ad 1. Agreed!
- Ad 2. I'm not sure what do you mean.
  - If you mean using `self._logger` instead of `self._logger.getChild(…)` — hmm, not sure. The latter gives a bit more details. In other words: the logs will come from `client.office365.runtime.auth.saml_token_provider.SamlTokenProvider` vs `client.office365.runtime.auth.saml_token_provider.SamlTokenProvider.get_authentication_cookie`. The latter is IMHO more informative. I've also used that namespace name to grep through logs.
  - If you mean using multiple vs single logger call — hmmm don't have strong opinion here. `FedAuth` is nearly 1000 chars long, rtFa nearly `400`. For me, it's easier to read logs if there's single value per line. But yeah, that's me. Multi-values per line? Okay for me as well. If you want that depending on the value (like `request.content` in dedicated line, but `rtFa` may be mixed) then I don't have good rule to propose when to use which.

**Comment by vgrem** [comment]
I think got your point about:

> The latter is IMHO more informative. I've also used that namespace name to grep through logs.

In that case how about to introduce a method in `Logger` class that accepts a `category ` optional parameter: 

```
def info(self, msg, category=None):
        current_logger =  self._logger(OFFICE365CLIENT_LOGGER_NAME)    #root logger
        if category:
              current_logger = self._logger.getChild(category)
        
        self._logger.info(msg,)
```


In that case we could replace

        logger = self._logger.getChild('get_authentication_cookie')
        logger.log(LOGGING_SECRET_LVL, 'self.FedAuth: %s', self.FedAuth)


with 

       logger.info('get_authentication_cookie', 'self.FedAuth: %s', self.FedAuth)



Regarding multiple vs single logger calls, indeed it's a matter of habit, my intention is to prevent the method to grow due to logger calls.

**Comment by kgadek** [comment]
I tried to get a fully bloat-free version using `inspection` and some hacking, but I couldn't retrieve class–method association from frame pointers reliably.

On the other design space spectrum, initialising logger at module-level induces little bloat. But it comes at the cost of requiring the client to set `disable_existing_loggers=False` when configuring logging. I don't think such client-side obligation is a good idea.

Currently I have this code. It's not completely bloat-free, but it's probably okay… or is it?

```python
def ensure_logging_debug_secrets():
    if 'debug_secrets' not in logging.Logger.__dict__:
        def _log_secrets(self, *args, **kwargs):
            self.log(LOGGING_SECRET_LVL, *args, **kwargs)
        
        logging.Logger.debug_secrets = _log_secrets

class LoggableClass:
    """Superclass for all classes that require namespaced logger."""
    _logger = None

    @classmethod
    def logger(cls, method=None):
        if cls._logger is None:
            logger_name = '.'.join([cls.__module__, cls.__name__])
            cls._logger = logging.getLogger(logger_name)

        if method is not None:
            return cls._logger.getChild(method)
        return cls._logger


# Actual usage:

ensure_logging_debug_secrets()  # call in every module using debug_secrets :(


class SamlTokenProvider(BaseTokenProvider, LoggableClass):
    # ...
    def acquire_token(self):
        logger = self.logger(self.acquire_token.__name__)
        logger.debug("debug")
        logger.debug_secrets("debug secrets")
```

1. I'm using `self.logger(self.acquire_token.__name__)` instead of `self.logger(acquire_token)`. This way it's harder for the code to display wrong information after refactoring. Furthermore, code renaming in IDEs should just work.
2. There is a problem with libraries having no obvious entry-point. As a result, it's quite non-trivial to ensure that this `logging.Logger.debug_secrets = _log_secrets` will be called exactly once. Therefore, I made this call idempotent and wrapped into method, which shall be called from every module that uses `logging.debug_secrets()`.
  - other possible solution would be to call `ensure_logging_debug_secrets()` in the same file as `LoggableClass` as they are _usually_ used together. However, if one would like only to use `debug_secrets`, then one will be required to import that module for side-effects only. And PyCharm would be quick to spot that this import is unused and will propose to remove it…

**Comment by kgadek** [comment]
I don't want to prematurely create PR, unless you'd rather have it. The solution implemented looks like this: https://github.com/vgrem/Office365-REST-Python-Client/compare/master...kgadek:upstream-issue-22-logging

I've dropped all doubled, subsequent logger calls.
