### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:741)

### ISSUE THREAD

**Issue by darljed** [vgrem/Office365-REST-Python-Client#220]
Help, I am having this error when running office 365 module in 2.7.15 python version. I use SharePoint Add-in client-id and client secret as authentication. Is there anyway to resolve this?

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:741)

I'm using this query

    request = ClientRequest(context)
    options = RequestOptions(
        settings.settings[configEntry]['url']+"/_api/web/lists/getbyTitle('{0}')/items({1})".format(list_title, item_id))
    options.set_header('Accept', 'application/json; odata=nometadata')  # JSON Light nometadata mode!
    options.set_header('IF-MATCH', '*')
    options.set_header('X-HTTP-Method', 'MERGE')
    options.set_header('verify', 'false')
    options.data = {field2update: updateValue}
    options.method = HttpMethod.Post
    
    request.verify = False
    data = request.execute_request_direct(options)

**Comment by rajeabhilash** [comment]
I'm getting this error while Uploading and Downloading the Data from SharePoint. I Tried `request.Verify = False` but it didn't work still throwing SSL Verify Exception.
Please do Bypass SSL Handshake in the Code or Help me to Bypass otherwise.
