### ISSUE TITLE
Creating a new item in a list

### ISSUE THREAD

**Issue by milkahut** [vgrem/Office365-REST-Python-Client#224]
I'm trying to create a new item for a list called user_list as follows: 
from office365.sharepoint.listitem import ListItem
from office365.sharepoint.listitem_creation_information import ListItemCreationInformation

info = ListItemCreationInformation()
new_item = user_list.add_item(info)

but get an attribute error: 
AttributeError: 'ListItemCreationInformation' object has no attribute 'items'

am I missing something?

**Comment by vgrem** [comment]
Greetings!

you are right, it appears to be a bug with passing `ListItemCreationInformation` object into `List.add_item` method. 

From another hand, if you are after _creating a list item_, would suggest  to **avoid** passing  `ListItemCreationInformation` object at all, the only benefits of utilizing **ListItemCreationInformation** comes in specific case, e.g. list item needs to be created a a folder facet.    

So,  when creating a `ListItem` resource , its properties could be passed via `dict `object as demonstrated below: 

```
item_properties = {'Title': item_title}
new_item = target_list.add_item(item_properties)
client.execute_query() 

```
