### ISSUE TITLE
Release latest version to pypi?

### ISSUE THREAD

**Issue by minsis** [vgrem/Office365-REST-Python-Client#225]
The version of this library I need isn't released to pypi. Are there plans to release the newer version of it?

**Comment by vgrem** [comment]
Greetings! 

Affirmative, the plans to release as soon as we have a chance. Hoping to hear from the @kgadek soon, who kindly maintains this project.
 
For now, the _latest_ version could be installed from [alternative index URL](https://pypi.org/project/office365-rest-client/)

**Comment by vgrem** [comment]
Closing this one as a duplicate of #75
