### ISSUE TITLE
Hitting 30 minute credential timeout

### ISSUE THREAD

**Issue by jaaydub42** [vgrem/Office365-REST-Python-Client#234]
I have a large Sharepoint upload that is taking over 30 minutes, and the access credential is expiring.

I am handling the upload in chucks using the start_upload, continue_upload, and finish_upload functions. That part appears to be working fine. But before completion I am hitting a token timeout.

It appears that in the adal library there is a acquire_token_with_refresh_token function, but I am not seeing this implemented.

Is there a method of refreshing my client credential token using your library that I am missing?

**Comment by flariut** [comment]
Hi, I'm getting the same issue trying to upload a large file (~4GB, with 10Mb upload speed) using the example for Sharepoint large files (https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/files/upload_large_file.py). After 30 minutes, download is stopped and I get a 403 response with "The security validation for this page has timed out". Is there any way to circumvent this limitation until the token refresh is implemented? How can I upload a file that big currently? Thank you.

**Comment by vgrem** [comment]
Staring from [`2.3.9` version ](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.9) SharePoint client introduces support to determine if security validation expired. If it gets expired, it refresh it automatically to prevent the exception: _The security validation for this page has timed out_ to occur.
