### ISSUE TITLE
Question:  Can a list field of type "Person or Group" be updated via the API?

### ISSUE THREAD

**Issue by lw1959** [vgrem/Office365-REST-Python-Client#236]
I have tried to set the value of a "Person or Group" list field in a number of manners:

```
- new_item.set_property("field_name", "email.address")
- new_item.set_property("field_name", FiledUserValue("upn"))
- new_item.set_property("field_name", FieldMultiChoiceValue("upn"))
```
none of the methods work for me.

I cannot figure out how to set or update this type of field.

Can you provide an example of how to set this type of field?

Thank you

**Comment by scraja** [comment]
I am interested in this too. I have the same problem but dont know what works.

**Comment by nefariousOne** [comment]
I'm looking for a solution to updating a People/Group (multi-value) column as well have yet to figure it. Any pointers appreciated!

**Comment by vgrem** [comment]
Greetings!

@lw1959, @scraja , here we go, the below example demonstrates how to _set multi choice field value_:

```
multi_choice_value = FieldMultiChoiceValue(["In Progress"])
item_to_update.set_property(multi_choice_field_name, multi_choice_value)
item_to_update.update().execute_query()  

```
 
and _set user field value_: 


```
current_user = client.web.current_user
user_value = FieldUserValue.from_user(current_user)
item_to_update.set_property(user_field_name, user_value).update().execute_query()

```


@nefariousOne, here we go, the example demonstrates how to create a list item and set  _People/Group (multi-value) column_ value

```
current_user = ctx.web.current_user.get().execute_query()
multi_user_value = FieldMultiUserValue()
multi_user_value.add(FieldUserValue.from_user(current_user))

item_to_create = tasks_list.add_item({
    "Title": "New Task",
    "AssignedTo": multi_user_value
}).execute_query() 

```

or 

```
multi_user_value_alt = FieldMultiUserValue()
multi_user_value_alt.add(FieldUserValue(current_user.id))

item_to_create_alt = tasks_list.add_item({
    "Title": "New Task 2",
    "AssignedTo": multi_user_value_alt
}).execute_query()
```


For examples could be [found here](tests/sharepoint/test_field_value.py).

**Comment by nefariousOne** [comment]
@vgrem Thank you very much for these examples! I guess one follow up question I have is: This method requires that the user exists within sites' User Information List or site context, correct? Can I get a User object based off of an email string of a user who has yet to access the site? 

I can explain what I'm trying to achieve and there may be a better way of doing so.  We are programmatically trying to archive documents to an SPO Doc Library in a site which no staff have access to. When adding the doc and associated metadata (including a "contributors" field) I need to add multiple user values for users that have not accessed the site so they do not exist within the UIL.

Any thoughts or recommendations?

**Comment by nefariousOne** [comment]
@vgrem, Got it figured out! I was missing the ctx.web.ensure_user(user_account_name).execute_query(). I was under the impression this would only pull out of the web's UIL where the users do not exist for us. But it does ultimately check the User Profile Service so my code is all set. 

Thanks again!
