### ISSUE TITLE
Getting error while Creating new list item 

### ISSUE THREAD

**Issue by shavas23** [vgrem/Office365-REST-Python-Client#237]
Hi Team,

I am trying  to create a new List Item in share point list called  "Test1"  

am i did any mistake here? could you please help me to fix it.

Thanks for you support in advance 

Python script: 

Sp_list = ctx.web.lists.get_by_title("Test1")
itemcreateInfo = {'Title':'5657849301','Dummy1':'6543210987','Dummy2':'50','Dummy3':'Open'}
new_it = Sp_list.add_item(itemcreateInfo)
    # new_it.update()
    # ctx.load(new_it)
ctx.execute_query()

getting following error : 

raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: ('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', 'The parameter Dummy1 does not exist in method GetByTitle.', "400 Client Error: Bad Request for url:

**Comment by dfish88** [comment]
I think you will need to load the list first before adding to it:

Sp_list = ctx.web.lists.get_by_title("Test1")
**ctx.load(Sp_list)**
**ctx.execute_query()**
itemcreateInfo = {'Title':'5657849301','Dummy1':'6543210987','Dummy2':'50','Dummy3':'Open'}
new_it = Sp_list.add_item(itemcreateInfo)
# new_it.update()
# ctx.load(new_it)
ctx.execute_query()

**Comment by shavas23** [comment]
Thank you so much **dfish88** now scripts working perfectly again than thank for the support.
 such a great library thank you and much appreciated  **vgrem** and **dfish88**
