### ISSUE TITLE
How to update multiple list items in Sharepoint using Python

### ISSUE THREAD

**Issue by VyronB** [vgrem/Office365-REST-Python-Client#242]
I have a list in sharepoint online: ListA

This list has 1500 items and 7 columns. 4 of them are populated while 3 are not.

I also have a dataframe with 3 columns, to be used for populating: Status, Week, Delivery

I would like to update all the items, so that all 7 columns are populated.

 df = pd.DataFrame({'Status': pd.Series(range(1,1500)), 'Week': pd.Series(range(1,1500)), 'Delivery': 
                     pd.Series(range(1,1500))})
I am fully authenticated.

I followed this example to update one list item:

# Open list object from portal
ctx_auth = AuthenticationContext(url=sharepoint_site_url)
ctx = ClientContext(sharepoint_site_url, ctx_auth)
target_list = ctx.web.lists.get_by_title('ListA')

# Fetch list item object by id and set it's properties
item = target_list.get_item_by_id(item_id)
item.set_property('Status', '1')
item.set_property('Week', '1')
item.set_property('Delivery', '1')

# Update list item object and send request back to portal
item.update()
ctx.execute_query()
But I have 1500 items.

Is there a way to do this more efficiently?

**Comment by VyronB** [comment]
Ok, trial and error produced this:

for index, row in Item_df.iterrows():
    print(row['Week'])
    app_settings3 = {
    'url': site_url,
    'client_id': client_id',
    'client_secret': client_secret
    }

    context_auth3 = AuthenticationContext(url=app_settings3['url'])
    context_auth3.acquire_token_for_app(client_id=app_settings3['client_id'], client_secret=app_settings3['client_secret'])
    ctx3 = ClientContext(app_settings3['url'], context_auth3)

    paras_list = ctx3.web.lists.get_by_title('ListA')
    
    # get the ID ofthe list, on order to match them
    item_p = paras_list.get_item_by_id(row['ID'])
    ctx3.load(item_p)
    ctx3.execute_query()
    item_p.properties
    item_p.set_property('Week', row['Week'])
    item_p.update()
    ctx3.execute_query()



And this works.

However!!!!

It is considerably slow
Feedback is appreciated!

**Comment by vgrem** [comment]
Greetings!

That's right, here is the _generic_ pattern on how to update list item:

```
list_item.set_property(<field_name>, <field-value>)
list_item.update()
ctx.execute_query()
```

In your example update operation is _submitted to server per every list item_, although  all update operations could be _batched and submitted as a single request_. From performance perspective this is the way how to improve  performance dramatically.

Regarding the library support for batch requests, currently it is supported in _experimental_ mode, will provide you the example how to update list items via batch mode later today.

**Comment by vgrem** [comment]
In [version `2.2.0`](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.2.0)  has been introduced `ClientContext.execute_batch` method which constructs a batch request by grouping multiple operations and submits it as a single request. 

The following example demonstrates how to update list items in a single request to the server:


```
# 1. Load list items
list_tasks = ctx.web.lists.get_by_title("Tasks")
items = list_tasks.items
ctx.load(items)
ctx.execute_query()
# 2. Update list items via batch request
for task_id, item in enumerate(items):
    item.set_property("Title", f"Task d000{task_id}")
    item.update()
ctx.execute_batch()
```

**Comment by yosephmi** [comment]
how would you do it if we dont have reference to the item. 
Like in the case shown where we have the items properties stored in a dataframe

**Comment by gsanchz** [comment]
I can't update Sharepoint list in the way you did:

```
def get_context(username, password, site_url):
    try:
        ctx_auth = AuthenticationContext(site_url)
        ctx_auth.acquire_token_for_user(username,password)
        return ClientContext(site_url, ctx_auth)
    except Exception as e:
        logging.error(f"SharePoint context error: {e}")

def update_list_record(ctx,new_properties_df,item):
    idx = item.properties["Title"]
    new_properties = dict(new_properties_df.loc[idx])
    for propertie, value in new_properties.items():
        ctx.load(item).execute_query()
        item.set_property(propertie,value).update()
    ctx.execute_batch()

ctx = get_context(username,password,url)
list_object = ctx.web.lists.get_by_title(list_title)
items = list_object.items.get().execute_query()

for item in items:
    try:
        update_list_record(ctx,input_data,item)
    except Exception as e:
        print(str(e))
```

I can retrieve items from Sharepoint list but when I try to update I get this error: "'-1, Microsoft.SharePoint.Client.InvalidClientQueryException', "A collection was found without the 'results' property. In OData, each collection must be represented as a JSON object with a property 'results'.", '400 Client Error: None for url: None'"

How can i fix it?
