### ISSUE TITLE
Adding column to SharePoint List

### ISSUE THREAD

**Issue by SwethaSrilakshmi** [vgrem/Office365-REST-Python-Client#249]
Hi,

Recently I have started working on SharePoint using Python. I am unable to add a column to an existing list using python. Can someone please help me in adding a column to existing list or create a new list with custom columns in SharePoint site using python?

Thanks in advance

**Comment by lalondesteve** [comment]
I managed to do it this way:
(unfortunately, I yet have to discover how to update the view to make it visible.)

```
from office365.sharepoint.fields.field_creation_information import FieldCreationInformation
from office365.sharepoint.fields.field_type import FieldType
f_info = FieldCreationInformation('ApiCreated', FieldType.Text)

ctx.web.lists.get_by_title('ListTitle').fields.add(f_info)
<office365.sharepoint.fields.field.Field object at 0x111568640>
s.execute()
```

**Comment by vgrem** [comment]
As @lalondesteve  correctly pointed out, creating a custom field for a list is supported, here is a generic example  

```
from office365.sharepoint.fields.field_type import FieldType

field_info = FieldCreationInformation('{field-name}', FieldType.Text)
existing_list = client.web.lists.get_by_title("{list-title}")
existing_list.fields.add(field_info)
client.execute_query()
```


Propose to close it as resolved.

**Comment by yosephmi** [comment]
i cannot seem to create a column with FielType choice. 
Here is what i am trying:
```
field_info = FieldCreationInformation(column_name, FieldType.Choice, choices=["Choice 1", "Choice 2"])
list.fields.add(field_info)
ctx.execute_query()
```

And the error i am receiving:
```office365.runtime.client_request_exception.ClientRequestException: ('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', "A node of type 'StartArray' was read from the JSON reader when trying to read a value of a property; however, a 'PrimitiveValue' or 'StartObject' node was expected.", "400 Client Error: Bad Request for url: https://intel.sharepoint.com/sites/site_name/_api/Web/lists/GetByTitle('list_name')/Fields")```
