### ISSUE TITLE
 ModuleNotFoundError: No module named 'office365.sharepoint.files'

### ISSUE THREAD

**Issue by kkarthik21** [vgrem/Office365-REST-Python-Client#250]
When i use the latest v2.1.7 installed using pip, i got the following error ModuleNotFoundError: No module named 'office365.sharepoint.files'. Any help would be greatly appreciated.

**Comment by vgrem** [comment]
Greetings, 

`v2.1.7` is already outdated,  recommend to switch to the latest one (`2.1.10.1` at the moment), it could be downloaded via GitHub:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`

or from an [alternative index](https://pypi.org/project/office365-rest-client/)
