### ISSUE TITLE
Create Document Set or manipulate ContentTypeId 

### ISSUE THREAD

**Issue by cfuentealba** [vgrem/Office365-REST-Python-Client#254]
I need to create a Document Set in Sharepoint Online. I haven't seen something specific for this, so far I was able to create a folder.  Is there a way to do this with create folder and update ContentTypeId some way, also how could I add metadata?

**Comment by vgrem** [comment]
Greetings,

the support for `DocumentSet` has been introduced () and the following example demonstrates how to create a document set:

```python
lib = client.web.lists.get_by_title("Documents")
name = "DocSet"
doc_set = DocumentSet.create(client, lib.rootFolder, name)
client.execute_query()
```


> Note:  it require the version (`2.2.2` above, which is not released yet), meanwhile it is available from the latest version  which could be installed via GitHub.
