### ISSUE TITLE
No module named 'office365.runtime.auth.client_credential'

### ISSUE THREAD

**Issue by marioem** [vgrem/Office365-REST-Python-Client#255]
Installed this client with pip, otherwise using Anaconda to manage my environments.
But for some reason I'm not able to run any single example. Basically nothing from office365.runtime.auth.* loads.
I'm on python 3.7.6, Win10, Anaconda 3.

BTW, I couldn't find anywhere settings module, so I was intending to try python_settings instead (just a blind try).

```
      3 from python_settings import settings
      4 from office365.sharepoint.client_context import ClientContext
----> 5 from office365.runtime.auth.client_credential import ClientCredential
      6 site_url = settings.get('url') + "/sites/team"

ModuleNotFoundError: No module named 'office365.runtime.auth.client_credential'
```

Any hints. Am I missing something or is there a bug in the distribution or somewhere else?

Cheers,

Mariusz

**Comment by bobroro** [comment]
Likewise on Python 3.6.9 using venv using Ubuntu in WSL. Installed via:
`pip3 install Office365-REST-Python-Client`
Thoughts here?

**Comment by vgrem** [comment]
Greetings,

you are installing the package from default index, right? 

`pip install Office365-REST-Python-Client`

Unfortunately at the moment the contact with PyPi package owner has been lost and  we cant get it updated to the _latest_ version  (here are a few more details #75 and related issues #218, #250 and #225)

My recommendation to _uninstall_  the package  (version `2.1.7`)  and install the _latest_ version (`2.2.0`) from alternative package instead:

`pip install office365-rest-client`

or from GitHub:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`


Once installed,  the error 

> No module named 'office365.runtime.auth.client_credential'

should no longer occur.
