### ISSUE TITLE
ModuleNotFoundError: No module named 'office365.runtime.auth.UserCredential'

### ISSUE THREAD

**Issue by rjb7731** [vgrem/Office365-REST-Python-Client#257]
I'm getting the above error message. I have installed through pip on the newer pypi link (one in lower case) uninstalled and tried direct from git. 

Any ideas as to why this is? 

All the other imports work fine but it does not work on this line:
from office365.runtime.auth.UserCredential import UserCredential

**Comment by venraju** [comment]
@rjb7731 import the module as given below
from office365.runtime.auth.**user_credential** import UserCredential

**Comment by rjb7731** [comment]
> @rjb7731 import the module as given below
> from office365.runtime.auth.**user_credential** import UserCredential

Thanks that fixed the error -is there typo in the examples shown on the main page? Now that have solved this issue i am getting 'Cannot get binary security token for from https://login.microsoftonline.com/extSTS.srf'. Will try to figure out why haha

**Comment by vgrem** [comment]
Closing this one since mentioned as resolved.
