### ISSUE TITLE
Sharepoint getChanges how to

### ISSUE THREAD

**Issue by lalondesteve** [vgrem/Office365-REST-Python-Client#259]
Hello, I'm creating a syncing client between sharepoint and another app. Everything is mostly working, but I can't figure out the usage of ChangeCollection. 
```
events_list = ctx.web.lists.get_by_title('Events')
ctx.load(events_list)
ctx.execute_query()

changes = events_list.get_changes(query=ChangeQuery(list_=True))
ctx.execute_query()

>>> changes
<office365.sharepoint.changes.changeCollection.ChangeCollection object at 0x105608cd0>
>>> changes.properties
{}

```

I can't figure out where to go from there through introspection or going through the source code. 
Most of my actions end up with 
`requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?`
upon the next execute_query(). 

Is there any way to extract the change token or get changes in any form?

**Comment by vgrem** [comment]
Thanks for catching it, Changes API has been improved (remaining bugs fixed) in the subsequent versions and the provided error should no longer occur.
