### ISSUE TITLE
Single quote in file names is causing problems if trying to download file 

### ISSUE THREAD

**Issue by florinmihut** [vgrem/Office365-REST-Python-Client#266]
Hi,

It seems that I am getting an error if I am trying to download a file with a name containing single quote(s).

office365.runtime.client_request_exception.ClientRequestException: ('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', 'The expression "Web/getFileByServerRelativeUrl(\'/sites/mysite/mypath/Update Q1\'2020.pptx\')/$value" is not valid.', "400 Client Error: Bad Request for url: https://tennant.sharepoint.com/sites/mysite/_api/Web/getFileByServerRelativeUrl('/sites/mysite/Shared%20Documents/mypath/Update%20Q1'2020.pptx')/%5C$value")

It seems that the single quote is not escaped here: %27 instead of '. 
It works for all other files, this is the only one which is causing an error. Renaming the file seems to fix it, but it needs to be fixed here I would assume.

**Comment by kraptor** [comment]
Fixed un #300

**Comment by kraptor** [comment]
@vgrem remember to close this bug, as this is fixed in #300 :)

**Comment by vgrem** [comment]
@kraptor we will, as long the new version will be released, thanks for the fix!

**Comment by vgrem** [comment]
@florinmihut  and @kraptor thank you for catching this issue and resolving it.  

It should no longer occur in [the latest release](https://pypi.org/project/Office365-REST-Python-Client/).
