### ISSUE TITLE
Download a file from a Sharepoint list's attachment column

### ISSUE THREAD

**Issue by libora6** [vgrem/Office365-REST-Python-Client#273]
Hey!
I am looking for a way to download the attachment from each row of a Sharepoint list (like pictures explain below).
<img width="779" alt="sp_attachment" src="https://user-images.githubusercontent.com/22372945/95086643-1d1c1300-06f7-11eb-86cf-148c284f827a.png">
Here is the attachment, I can see its URL and name but I need to access it programatically to donwload it.
<img width="804" alt="sp_pointing_attachment" src="https://user-images.githubusercontent.com/22372945/95087001-87cd4e80-06f7-11eb-8fc6-bc20927a87d8.png">

I see the files in 'Attachment' column, but I was not able to get their URL using the code in the method below.

```
def download_file_from_sharepoint_list(self, listname):
        
        download_folder = r'C:\Desktop\sharepoint_attachments'
        list_items = self.ctx.web.lists.get_by_title(listname)
        items = list_items.get_items()
        print(f"Connected to {listname} table inside Sharepoint.")
        items.queryOptions.select = ["ID", "UniqueId", "FileRef", "LinkFilename", "Title"]
        self.ctx.load(items)
        self.ctx.execute_query()
        
        for item in items: 
            file = item.file
            self.ctx.load(file)
            self.ctx.execute_query()
            file_name = "{0}".format(file.properties["Name"])
            download_path = download_folder + '//' + file_name
            with open(download_path, "wb") as local_file:
                file.download(local_file)
                ctx.execute_query()
                print("[Ok] file has been downloaded: {0}".format(download_path))

        return
```

Can somebody help? I already saw similar resolved Issues like the one below but they return errors. 
The method above was used using [Issue 190](https://github.com/vgrem/Office365-REST-Python-Client/issues/190) I got the error below:
`AttributeError: 'ListItemCollection' object has no attribute 'queryOptions'`

My connections are correct and working properly for other methods that I've done, the only issue here is to download the attachments.

THANKS

**Comment by libora6** [comment]
@vgrem I saw the [Issue 222](https://github.com/vgrem/Office365-REST-Python-Client/issues/222) and tried to use that but it is giving the error `TypeError: Object of type CamlQuery is not JSON serializable`;

```
    def download_file_from_sharepoint_list(self, list_title):
        
        download_path = r'C:\Users\user_name\Desktop\sharepoint_files'
        list_obj = self.ctx.web.lists.get_by_title(list_title)
        items = list_obj.get_items(CamlQuery.create_all_items_query())
        self.ctx.execute_query()
        for item in items:
            if item.properties['Attachments']:  # 1. determine whether ListItem contains attachments
                # 2. Explicitly load attachments for ListItem     
                attachment_files = item.attachmentFiles
                self.ctx.load(attachment_files)
                self.ctx.execute_query()
                # 3. Enumerate and save attachments
                for attachment_file in attachment_files:
                    download_file_name = os.path.join(download_path, os.path.basename(attachment_file.properties["FileName"]))
                    with open(download_file_name, 'wb') as fh:
                        content = attachment_file.read()
                        fh.write(content)
```

**Comment by vgrem** [comment]
Greetings @libora6,

you were close, it appears the API syntax is not that intuitive as expected, let me clarify it a bit: 

```python
items = list_items.get_items()  #<- since this corresponds to function call,  items collection gets initialized once execute_query method is  invoked
items.queryOptions.select = ["ID", "UniqueId", "FileRef", "LinkFilename", "Title"]
self.ctx.load(items)  #<- calling load method is redundant here (since it is used  when addressing entities rather than with function calls)
```

So you could consider initialize list items collection either via _function call_ :

```python
items = list_obj.get_items()
ctx.execute_query()

```

or by _addressing list item collection_: 

```python
items = list_obj.items   
ctx.load(items, ["ID", "UniqueId", "FileRef", "LinkFilename", "Title", "Attachments"])  
ctx.execute_query()
```



Here is a complete example (has been verified against the latest version of library:  )


```python

list_obj = ctx.web.lists.get_by_title(list_title)
items = list_obj.items
ctx.load(items, ["ID", "UniqueId", "FileRef", "LinkFilename", "Title", "Attachments"])
ctx.execute_query()
for item in items:
    if item.properties['Attachments']:  # 1. determine whether ListItem contains attachments
        # 2. Explicitly load attachments for ListItem
        attachment_files = item.attachmentFiles
        ctx.load(attachment_files)
        ctx.execute_query()
        # 3. Enumerate and save attachments
        for attachment_file in attachment_files:
            download_file_name = os.path.join(download_path, os.path.basename(attachment_file.properties["FileName"]))
            with open(download_file_name, 'wb') as fh:
                content = attachment_file.read()
                fh.write(content)
                print(f"{attachment_file.server_relative_url} has been downloaded")


```

**Comment by libora6** [comment]
@vgrem tks a lot buddy!

**Comment by hard-mood** [comment]
Same here. Also can't access the attachmentFiles object. 
Using SharePoint in Microsoft 365.

**Comment by mickmill54** [comment]
The above example is missing:   item.attachment_files.get().execute_query()

The for loop more like this:
--------------------------------
`for item in items:  # type: ListItem
    if item.properties['Attachments']:  # 1. determine whether ListItem contains attachments
        # 2. Explicitly load attachments for ListItem
        attachment_files = item.attachment_files.get().execute_query()
        # 3. Enumerate and save attachments
        for attachment_file in attachment_files:  # type: AttachmentFile
            download_file_name = os.path.join(download_path, os.path.basename(attachment_file.file_name))
            with open(download_file_name, 'wb') as fh:
                attachment_file.download(fh).execute_query()
            print(f"{attachment_file.server_relative_url} has been downloaded into {download_file_name}")
`
