### ISSUE TITLE
Syntax Error Python 2.7

### ISSUE THREAD

**Issue by lucafabbri365** [vgrem/Office365-REST-Python-Client#275]
Hello,
I was trying to use Office365-REST-Python-Client v2.2.1 (latest released version) with Python 2.7 (it should be still supported), but I get a SyntaxError:

```
python test300.py

Traceback (most recent call last):
  File "test300.py", line 3, in <module>
    from office365.sharepoint.client_context import ClientContext
  File "/usr/local/lib/python2.7/dist-packages/office365/sharepoint/client_context.py", line 14, in <module>
    from office365.runtime.odata.odata_batch_request import ODataBatchRequest
  File "/usr/local/lib/python2.7/dist-packages/office365/runtime/odata/odata_batch_request.py", line 105
    *headers_raw, content = lines[1:]
    ^
SyntaxError: invalid syntax
```

With an older version of Office365-REST-Python-Client (v2.1.7 for example) and Python 2.7 I have no errors.

Any help would be much appreciated.

Thank you,
Luca

**Comment by vgrem** [comment]
Greetings!

in version  v2.2.1 was introduced a few changes, incompatible with Python 2.7, sorry about inconvinenence. 
[Version `2.3.5`](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.5) is finally backward compatible with Python `2.7` again.
