### ISSUE TITLE
OneDrive - deep subfolders reading issue

### ISSUE THREAD

**Issue by gniemiec** [vgrem/Office365-REST-Python-Client#276]
I used the code from example:
https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/onedrive/print_folders_and_files.py
And I'm getting an error in line:
client.execute_query()

('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', 'Expression drive/**items/items**/043C3X6M13FPIQDC14VGJ7Q77ZXXAEER/children is incorrect.', '400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/users/user@domain.com/drive/**items/items**/043C3X6M13FPIQDC14VGJ7Q77ZXXAEER/children')

Apparently ResourcePath.to_url builds incorrect url for subfolders deeper than 1 in a drive.

**Comment by mxplusb** [comment]
I also hit this issue trying to walk a file tree.

**Comment by vgrem** [comment]
Thank you for catching this bug,  the addressing of drive items has been improved in [`2.3.5` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.5)  and the provided error should no longer occur.
