### ISSUE TITLE
Special Characters in Password

### ISSUE THREAD

**Issue by kwebster2019** [vgrem/Office365-REST-Python-Client#278]
Yeah if the password has special characters
then in file office365.runtime.auth.providers.saml_token_provider.py,
(line 246) data = data.replace('{' + key + '}', str(params[key]))
the params[key] should have a replace with xml special characters 
"   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;

**Comment by vgrem** [comment]
Greetings,

the provided error should no longer occur, make sure to update to the _latest version_ ([`2.2.2`](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.2.2) at the moment) which resolves the issue with escaping special characters in xml
