### ISSUE TITLE
How to navigate a site instead of root  ?

### ISSUE THREAD

**Issue by Vel-San** [vgrem/Office365-REST-Python-Client#280]
Hey!

I've successfully connected to my site with UserCredential, and i can print the Title. However i do not want to work with my root, instead i want to work with my /site/XXX. Is there a proper way to do so ?

I tried appending the /site/XXX to the site_url but authentication failes once that is done. I want to download some files from the site, so i tried this

`    site_url = "https://XXX.sharepoint.com/"
    ctx = ClientContext(site_url).with_credentials(UserCredential("XXX", "XXX"))

    file_url = 'sites/XXX/Shared Documents/XYZ.xlsx'
    download_path = "./XYZ.xlsx"  # Till here, the code works just fine
    with open(download_path, "wb") as local_file:
        file = ctx.web.get_file_by_server_relative_url(file_url).download(local_file).execute_query() # Empty file is created, and I get an error that the file doesn't exist.
    LOG.debug("[Ok] file has been downloaded: {0}".format(download_path))`

Part of the error code message:

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://XXXX.sharepoint.com/_api/Web/getFileByServerRelativeUrl('sites%2FXXX%2FShared%20Documents%2FXYZ.xlsx')?$select=ServerRelativeUrl`

`office365.runtime.client_request_exception.ClientRequestException: ('-2147024809, System.ArgumentException', 'serverRelativeUrl\r\nParameter name: Specified value is not supported for the serverRelativeUrl parameter.', "400 Client Error: Bad Request for url: https://XXXX.sharepoint.com/_api/Web/getFileByServerRelativeUrl('sites%2FXXX%2FShared%20Documents%2FXYZ.xlsx')?$select=ServerRelativeUrl`

What am i doing wrong? I couldn't find examples for /sites in your /examples.

**Comment by vgrem** [comment]
Greetings!

`Web.get_file_by_server_relative_url` is a _site-scoped_ method meaning `ClientContext` expects a url  of a site where file resides: 

```
site_url = "https://{tenant}.sharepoint.com/sites/{site}"
ctx = ClientContext(site_url).with_credentials(UserCredential("{username}", "{password}"))
```


Alternatively ( without a client context involved) file could be downloaded by _absolute url_ as demonstrated below:

```
abs_file_url = "https://{tenant}.sharepoint.com/sites/team/Shared Documents/big_buck_bunny.mp4"
with open(local_path, 'wb') as local_file:
    file = File.from_url(abs_file_url).with_credentials(client_credentials).download(local_file).execute_query()
print("'{0}' file has been downloaded into {1}".format(file.serverRelativeUrl, local_file.name))
```

**Comment by Vel-San** [comment]
Thanks a lot, @vgrem ! It works perfectly fine!
