### ISSUE TITLE
SyntaxError: invalid syntax - import ClientContext

### ISSUE THREAD

**Issue by njchandu** [vgrem/Office365-REST-Python-Client#282]
I am getting the below error when trying to execute the script. Any leads? I'm on python `Python 2.7.16 :: Anaconda, Inc.`
```
Traceback (most recent call last):
  File "sharepoint.py", line 2, in <module>
    from office365.sharepoint.client_context import ClientContext
  File "/opt/dataxu/dxuser/anaconda2/lib/python2.7/site-packages/office365/sharepoint/client_context.py", line 14, in <module>
    from office365.runtime.odata.odata_batch_request import ODataBatchRequest
  File "/opt/dataxu/dxuser/anaconda2/lib/python2.7/site-packages/office365/runtime/odata/odata_batch_request.py", line 105
    *headers_raw, content = lines[1:]
    ^
SyntaxError: invalid syntax
```
Thanks in advance.

**Comment by beliaev-maksim** [comment]
@vgrem 

here is the issue in unpacking which is not supported in Py2.7

was it decided to drop support of V2 due to EOL ?

**Comment by vgrem** [comment]
Hi all, 

to anyone stumble upon this error, it is recommended to upgrade to version `2.3.5` or above which addresses backward compatibility with Pyto anyone stumble upon this error, it is recommended to upgrade to version `2.3.5` or above which addresses backward compatibility with Python 2.7 and the provided error should no longer occur. hon 2.7 and the provided error should no longer occur. 

Similar issue: #326
