### ISSUE TITLE
Errno -2147024891, System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by Mooreel** [vgrem/Office365-REST-Python-Client#283]
I am using celery on redis to run some file upload/download tasks for my company. 
After some time I retrieve a **"Errno -2147024891, System.UnauthorizedAccessException The security validation for this page has timed out. Click Back in your Web browser, refresh the page, and try your operation again.: "403 Client Error: FORBIDDEN for url:"**

only restarting celery/redis helps solving this issue. 

Is there a way of  handling this error? seems the session is somewhere and just doing the login again is not solving this issue.

**Comment by kraptor** [comment]
@Mooreel Do you mind to share the solution/workaround you found to fix this?

**Comment by FnEsc** [comment]
@Mooreel Do you mind to share the solution/workaround you found to fix this?
