### ISSUE TITLE
Example of filter or where

### ISSUE THREAD

**Issue by ederfdias** [vgrem/Office365-REST-Python-Client#284]
Hello,
I am trying to filter an item from library before load the entire lib.
For example:

`list_files = context.web.lists.get_by_title(LIST_NAME)
files = list_files.get_items()`

There is any method or way to filter a item from GUID without load entire library?

Thanks a lot

**Comment by ederfdias** [comment]
Looks like a found the answer:
`list_files.items.filter("GUID eq '" + FILE_ID + "'")`

**Comment by vgrem** [comment]
Greetings,

there is such a method: [ `List.get_item_by_id`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/office365/sharepoint/lists/list.py#L113) which:

> Returns the list item with the specified list item identifier


Here is an example:

`item = list.get_item_by_id(item_id).get().execute_query()`

**Comment by sithankanna** [comment]
Is there an example for querying list items by their GUID

`list.get_item_by_unique_id('00761165-1514-4A40-A4B9-32A0A9709069')` gets me a 

_`System.ArgumentException', 'Value does not fall within the expected range.', "400 Client Error: Bad Request for url'_` error
