### ISSUE TITLE
Setting up questions to run this package

### ISSUE THREAD

**Issue by kenshengit** [vgrem/Office365-REST-Python-Client#285]
I am new to Office365-REST-Python-Client, and trying to use it for my problem that **I need to download file from Sharepoint through ADFS in Python code**. 

I ran some examples in this repository, e.g. connect_with_user_creds.py, and got errors like below. 
```
KeyError: 'office365_python_sdk_securevars'
```
I had installed the package using `pip install Office365-REST-Python-Client`, but only got 
`Office365-REST-Python-Client       2.2.2`
looks related in my pip list, which has no "settings" package. 

Am I missing anything in the setup or testing the examples? What is office365_python_sdk_securevars?? Or any suggestions how to realize my problem as mentioned above? Thanks.

**Comment by vgrem** [comment]
Greetings,

`office365_python_sdk_securevars` is environment variable used for CI/CD process, you don't need this one.  The following example demonstrates how to download a file by url:

```python
import os
from office365.runtime.auth.client_credential import UserCredential
from office365.sharepoint.files.file import File

username  = "'{username}@{tenant}.onmicrosoft.com'"
password = "--your password goes here--"
credentials = UserCredential(username, password)

abs_file_url = f"https://{tenant}.sharepoint.com/Shared Documents/big_buck_bunny.mp4"
file_name = os.path.basename(abs_file_url)
with open(local_path, 'wb') as fh:
     file = File.from_url(abs_file_url).with_credentials(client_credentials).download(fh).execute_query()
print("'{0}' file has been downloaded into {1}".format(file.serverRelativeUrl, local_file.name))
```




Another examples could be found under [`examples` folder](https://github.com/vgrem/Office365-REST-Python-Client/tree/master/examples/sharepoint/files)

**Comment by ardeal** [comment]
@vgrem ,

Hi,
Your upper code seems old at present.
I checked the code in examples folder in the repo. Those examples seem old as well.

My company has Teams tenant, and I could access Teams by the following user name and passwd.
The purpose of accessing Teams channel  using Python is to:
1) check whether a folder exist. if yes, I didn't nothing. if no, I will create.
2) if an additional folder exists, I will delete it.
3) upload files to a specified folder.
4) download files from a specified folder.

Do you have example code to do the upper thing?
Or is there example code in the repo?

```python
import os
from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.files.file import File
from office365.sharepoint.webs import web

username  = "xxx@aaa.com"
password = "abcsded!"
credentials = ClientCredential(username, password)

tenant = 'mytenant'
abs_file_url = f"https://{tenant}.sharepoint.com/Shared Documents/uu"
file_name = os.path.basename(abs_file_url)



```
