### ISSUE TITLE
File.open_binary(ctx, relative URL) stopped working on Nov 2

### ISSUE THREAD

**Issue by ponnet** [vgrem/Office365-REST-Python-Client#286]
Started throwing:
InvalidURL: Failed to parse: error

Here are the details:
InvalidURL: Failed to parse: //<bound method ClientContext.service_root_url of <office365.sharepoint.client_context.ClientContext object at 0x7f0012229b00>>web/getfilebyserverrelativeurl('/teams/myname/data/Shared%20Documents/myfolder/myfile.xlsm')/\$value

Here is Relative URL that worked until Nov 2:
'/teams/myname/data/Shared%20Documents/my%20folder/myfile.xlsm'

**Comment by vgrem** [comment]
Greetings @ponnet,

cant spot what might cause this error, at least in the latest version (`2.2.2` at the moment)  the [download example](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/files/download_file.py) succeeds and file gets downloaded. 

```python

from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext
site_url = "https://{tenant}.sharepoint.com/sites/{site}"
file_url = '/sites/sites/{site}/Shared Documents/big_buck_bunny.mp4'
credentials = ClientCredential(client_id, client_secret)
ctx = ClientContext(site_url).with_credentials(credentials)
download_path = os.path.join(local_path, os.path.basename(file_url))
with open(download_path, "wb") as local_file:
    file = ctx.web.get_file_by_server_relative_url(file_url).download(local_file).execute_query()

```
 
Could you please give it another shot againts the latest version?

**Comment by ponnet** [comment]
Thank you, @vgrem 

I have upgraded from Anaconda Py3.6 + Office365-Python-Client 2.1.7 to 2.2.2

Here is the old code's errors:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-c92f19c4969d> in <module>
>       4 import os
>       5 
> ----> 6 from office365.sharepoint.file import File
>       7 from office365.sharepoint.client_context import ClientContext
>       8 from office365.runtime.auth.authentication_context import AuthenticationContext
> 
> ModuleNotFoundError: No module named 'office365.sharepoint.file'
> 
> 

Also using the code above:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-3-2415c555ef63> in <module>
>       1 from office365.runtime.auth.client_credential import ClientCredential
> ----> 2 from office365.sharepoint.client_context import ClientContext
> 
> /usr/local/anaconda/lib/python3.6/site-packages/office365/sharepoint/client_context.py in <module>
>       1 import copy
>       2 
> ----> 3 import adal
>       4 
>       5 from office365.runtime.auth.authentication_context import AuthenticationContext
> 
> ModuleNotFoundError: No module named 'adal'
>

**Comment by vgrem** [comment]
@ponnet, please find my comments below

> ModuleNotFoundError: No module named 'office365.sharepoint.file'

Starting from  version 2.2.0 `File` module is expected to be imported like this:

`from office365.sharepoint.files.file import File`



Regarding 

> ModuleNotFoundError: No module named 'adal'

seems Anaconda [doesn't clean automatically older packages](https://github.com/conda/conda/issues/5347) and the command should do the trick: 

`conda clean -p `

**Comment by laishahirah** [comment]
Hi, Can you help advise for my issue too. 
I use python v3.7.3. and I received the following error

TypeError: 'ClientCredential' object is not subscriptable

My code:

from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File

**Comment by vgrem** [comment]
Hey @ponnet,

regarding the error:

> ModuleNotFoundError: No module named 'adal'

indeed the provided error occurred if `adal `package was not installed explicitly, the same issue has been reported here: #296  

Propose to upgrade to the latest version [the latest release](https://pypi.org/project/Office365-REST-Python-Client/), the provided error should no longer occur.

**Comment by ponnet** [comment]
Hi @vgrem ,

Finally got to the upgrade for the latest release.
With the latest release and a bit of tweaking:
1. None of the download codes here worked: [download examples](https://github.com/vgrem/Office365-REST-Python-Client/tree/master/examples/sharepoint/files)
2. Here is what worked:
`
import sys
sys.dont_write_bytecode = True
import os

from office365.sharepoint.files.file import File
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.authentication_context import AuthenticationContext

url1  = 'https://{myco}.sharepoint.com/teams/{myteam}/general'
client_id     = {12345}
client_secret = {abcdef}
relative_url  = '/teams/{myteam}/general/Shared%20Documents/'

ctx_auth = AuthenticationContext(url1)

file_url = relative_url + '{filename}'    
response = File.open_binary(ctx, file_url)
with open('{newfilenamelocation}', 'wb') as output_file:
    output_file.write(response.content)

`

P.S. BTW, links to the list of exampes are broken [here](https://pypi.org/project/Office365-REST-Python-Client/#Working-with-SharePoint-API)
