### ISSUE TITLE
Consider renaming (or dropping) the top-level package

### ISSUE THREAD

**Issue by jimr** [vgrem/Office365-REST-Python-Client#29]
The name `client` is pretty generic and seems unnecessary (since there's only one sub-module) - could you consider deleting it and having the top-level module be `office365` instead? It would mean updating all the docs, tests, etc but that should be relatively easy with a simple find and replace...

**Comment by vgrem** [comment]
That's indeed a good point and i agree. Lets drop the top level package.

**Comment by jimr** [comment]
Fantastic! Would you like me to make the changes and open a PR, or will you do it?

**Comment by vgrem** [comment]
I would appreciate you to make the changes and open a PR. Thank you!

**Comment by jimr** [comment]
I thought you might say that :)
