### ISSUE TITLE
SharePoint get lists item (caml query) does not work

### ISSUE THREAD

**Issue by BlazeOfFeathers** [vgrem/Office365-REST-Python-Client#290]
When I try to get a item from SharePoint with the caml query, it always returns all the items in het SharePoint list.
this is my code:

        caml_query = CamlQuery.parse(
            "<View><Query><Where><Eq><FieldRef Name='CustomId' /><Value Type='Text'>a68860528</Value></Eq></Where></Query></View>"
        )
        items = list.get_items(caml_query)
        ctx.load(items)
        ctx.execute_query()

**Comment by vgrem** [comment]
Greetings,

`CamlQuery.parse` method expect `Query` expression rather then View schema, that's probably the reason why it ignores query and returns all the items.


Given the provided example, CAML query could be constructed like this:

```
caml_query = CamlQuery()
caml_query .ViewXml = "<View><Query><Where><Eq><FieldRef Name='CustomId' /><Value Type='Text'>a68860528</Value></Eq></Where></Query></View>"
```


or 

```
caml_query = CamlQuery.parse(
        "<Where><Eq><FieldRef Name='CustomId' /><Value Type='Text'>a68860528</Value></Eq></Where>"
 )
```

**Comment by tobykwan** [comment]
I encounter the same problem, and I find that it seems the context should be loaded against the LIST, not the items
So
`   ctx.load(items)`
Shows ALL items, 

`    ctx.load(list)`
List filtered as expected

**Comment by obZenn** [comment]
I am facing a similar thing where I'm trying to get the latest uploaded file to sharepoint from the list. 
`caml_query = CamlQuery.parse(
        "<where><Geq><FieldRef Name='Modified' /><Value Type='DateTime'><Today OffsetDays='-1' /></Value></Geq></where>"
 )

caml_query.FolderServerRelativeUrl = sp

# 3. Retrieve list items based on the CAML query 
oList = ctx.web.lists.get_by_title('Documents')
list = oList.get_items(caml_query) 
ctx.execute_query()
ctx.load(list)
print(list)`

print list returns all items in 'Documents'
