### ISSUE TITLE
How to add a string and attachment in the same sharepoint's ListItem?

### ISSUE THREAD

**Issue by libora6** [vgrem/Office365-REST-Python-Client#291]
Hi @vgrem @Toilal,

I was looking to your code and trying to figure out a code that create a new line in a sharepoint list adding the "request id" string and its attachment file.

This is what I need to do:
<img width="941" alt="question_upload_file_sharepoint" src="https://user-images.githubusercontent.com/22372945/99250704-ddaf0f00-27ea-11eb-9c21-4606e904677e.png">

As the red arrows shows I need to add the "REQUEST_ID" string and add the "Attachments" file.

I saw some code to upload file but did not find anything related to attachments.

Any help is very welcome!

TKS

**Comment by vgrem** [comment]
Greetings @libora6 ,

here is a generic example which demonstrates how to:

- create a list item 
- upload an attachment into list item

```python
ctx = ClientContext(site_url).with_credentials(ClientCredential(client_id, client_secret))
list_object = ctx.web.lists.get_by_title(list_title)
# 1. create a list item first
new_item = list_object.add_item({
    "Title": "Task 123"
}).execute_query()
# 2. upload attachment into list item
with open(attachment_path, 'rb') as content_file:
    file_content = content_file.read()
attachment_file_name = os.path.basename(attachment_path)
attachment_file_information = AttachmentfileCreationInformation(attachment_file_name, file_content)
attachment_file = new_item.attachmentFiles.add(attachment_file_information).execute_query()
```


Notes:

- In the provided example only `Title` is specified for list item, in your case  make sure to specify proper name for field `REQUEST_ID` 


**Result** 

![image](https://user-images.githubusercontent.com/1596072/99538219-4c3fc880-29b5-11eb-8f56-8f9fe3af848e.png)

**Comment by libora6** [comment]
@vgrem tks for your prompt support.

**Comment by TM-ottrp0p** [comment]
For other if your list objects did not have attachmentFiles as an attribute, you may find it named attachment_files

**Comment by stevehaycock** [comment]
@vgrem I'm using the example above you have provided and trying to attach a PDF file to the new item. However, I see the following error 

'The data is invalid. (Exception from HRESULT: 0x8007000D)', "500 Server Error: Internal Server Error for url:

and not sure how to resolve it. Any help would be greatly appreciated.

**Comment by josegarciaestrada** [comment]
Hi, how did you upload the image?
