### ISSUE TITLE
Make adal dependency optional (as extras?) or declare it explicitly

### ISSUE THREAD

**Issue by zyv** [vgrem/Office365-REST-Python-Client#296]
Hello,

Currently `Office365-REST-Python-Client` does not depend on `adal`, but it is required to be able to talk to SharePoint even if it is not actually used:

https://github.com/vgrem/Office365-REST-Python-Client/blob/master/office365/sharepoint/client_context.py#L3

Here you have an explicit `import adal`. Could you please add a `try/catch` around it or move into `acquire_token`?

I'm using SharePoint with app credentials as shown here and if I comment out `import adal` it still works just fine:

https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/files/download_file.py

Unfortunately, `adal` is not declared as a dependency, which makes it extra annoying. 

All the best,
Yury

**Comment by vgrem** [comment]
Greeting!

Thank you for catching this issue, indeed in version `2.2.2` after switching from Azure Active Directory Authentication Library (ADAL) to  Microsoft Authentication Library (MSAL) as a default authentication library, SharePoint client still contains an explicit reference to adal, in particular for acquiring token via client certificate. The change be included in the forthcoming 2.2.3 release.

**Comment by vgrem** [comment]
Update: `adal` package dependency has been completely removed from SharePoint client in [the latest ( `2.3.0.1`) release ](https://pypi.org/project/Office365-REST-Python-Client/)

**Comment by zyv** [comment]
Awesome, many thanks!
