### ISSUE TITLE
ModuleNotFoundError: No module named 'office365.runtime'

### ISSUE THREAD

**Issue by mark4409** [vgrem/Office365-REST-Python-Client#298]
I'm struggling to get anything working due to this error and I'm not sure what's causing it.

I'm importing using:

`from office365.runtime.auth.client_credential import ClientCredential`

and it's erroring with:

`ModuleNotFoundError: No module named 'office365.runtime'; 'office365' is not a package`

I'm using this on Windows and have installed with pip. I've tried both version 2.2.0 and 2.2.2 on both Python 3.8.0 32 bit and 3.8.6 64 bit. 

The location shown in `pip show Office365-REST-Python-Client` matches a location in `sys.path`

**Comment by mark4409** [comment]
Schoolboy error..... I named my test python file 'office365.py'

Please close!

**Comment by vgrem** [comment]
@mark4409 good to know its been resolved.
