### ISSUE TITLE
401 Client Error: Unauthorized

### ISSUE THREAD

**Issue by xibriz** [vgrem/Office365-REST-Python-Client#314]
I have checked all the issues, especially #207 

I have registered the app: `https://[tenant].sharepoint.com/_layouts/15/appinv.aspx`
```
The app identifier has been successfully created.
Client Id:  	ID
Client Secret:  	TOKEN=
Title:  	PFS
App Domain:  	www.localhost.com
Redirect URI:  	https://www.localhost.com
```
I have given permissions: `https://[tenant].sharepoint.com/_layouts/15/appinv.aspx`
XML:
```
<AppPermissionRequests AllowAppOnlyPolicy="true">
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
</AppPermissionRequests>
```

But this code:
```
from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext

site_url = "https://[tenant].sharepoint.com/"
client_id = "ID"
client_secret = "TOKEN="

client_credentials = ClientCredential(client_id, client_secret)
ctx = ClientContext(site_url).with_credentials(client_credentials)
web = ctx.web
ctx.load(web)
ctx.execute_query()

print(web.properties['Url'])
```

Produces this error:
```
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/office365/runtime/client_request.py", line 75, in execute_query
    response.raise_for_status()
  File ".../lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://[tenant].sharepoint.com/_api/Web

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sharepoint.py", line 96, in <module>
    ctx.execute_query()
  File ".../lib/python3.6/site-packages/office365/runtime/client_runtime_context.py", line 138, in execute_query
    self.pending_request().execute_query()
  File ".../lib/python3.6/site-packages/office365/runtime/client_request.py", line 79, in execute_query
    raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: (None, None, '401 Client Error: Unauthorized for url: https://[tenant].sharepoint.com/_api/Web')
```

If i use `ctx = ClientContext(site_url).with_user_credentials(username, password)` everything works fine.

Where do I go from here?

**Comment by vgrem** [comment]
Greetings @xibriz,

according to provided description, it appears app principal has been registered and granted permissions properly.   

A few questions though:

- could you confirm your app principal is listed  in `Site Settings -> Site app permissions` page?   
![image](https://user-images.githubusercontent.com/1596072/104031730-cc282900-51d5-11eb-8d14-279115140513.png)

- just out of curiosity, are you certain client secret value is passed _as is_ (without any prefix like `"TOKEN="`) ?
- on `appinv.aspx page`,  does confirmation dialog appear, where `Trust` button is expected to be clicked to grant the permissions?


Btw, there is a instruction available  in wiki section:    
[How to connect to SharePoint Online and and SharePoint 2013 2016 2019 on premises with app principal](https://github.com/vgrem/Office365-REST-Python-Client/wiki/How-to-connect-to-SharePoint-Online-and-and-SharePoint-2013-2016-2019-on-premises--with-app-principal)

**Comment by xibriz** [comment]
Thanks for the quick response @vgrem 

Yes, it seems like the authentication is ok, but not the authorazation.

1. Yes,  the app is listed 
2. Yes, the token is correct. Changing it gives authentication error.
3. Yes, the Trust page appear and I can hit the Trust button.

I have studied the page and tried all kinds of different access XMLs.

Can it be something with my office365 environment?

**Comment by xibriz** [comment]
New week, new motivation :)

I found this thread https://stackoverflow.com/questions/64025660/python-sharepoint-library-office365-rest-python-client-error-401-unauthorized

Install cmdlet if you don't have it:
```
Install-Module -Name Microsoft.Online.SharePoint.PowerShell
```

Connect and run the command
```
Connect-SPOService -Url https://[tenant]-admin.sharepoint.com -Credential admin@domain.com
Set-SPOTenant -DisableCustomAppAuthentication $false
```

At first, I got the same error, but after a few minutes (5-10) the authorization worked without any other changes.

Note that my Office365 setup is only a few weeks old.

**Comment by xibriz** [comment]
@vgrem another thing... I read that these client secrets is only valid for 12 months.. is that true?

**Comment by vgrem** [comment]
@xibriz good to know you get it fixed and thank you for sharing the details, I believe someone else will find this useful.

Indeed since:

> **For new tenants**, apps using an ACS app-only access token is disabled by default. We recommend using the Azure AD app-only model which is modern and more secure. But you can change the behavior by running ‘set-spotenant -DisableCustomAppAuthentication $false' (needs the latest SharePoint admin PowerShell).

setting `DisableCustomAppAuthentication `to `$false` should do the trick.




Regarding 

> I read that these client secrets is only valid for 12 months.. is that true?

positive,  according to [Add-in secret expiration](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization#add-in-secret-expiration):
  

> The add-in secret must be replaced every **12 months**. For details, see Replace an expiring client secret in a SharePoint Add-in.

Although there is one trick available, for SharePoint Online app principal could be registered via Azure AD instead of `AppRegNew.aspx` page, this way app lifetime duration could be controlled on a more flexible level. 
![image](https://user-images.githubusercontent.com/1596072/104170537-f8c48680-5409-11eb-88ea-d02a5fc6dee0.png)


Refer, for example, this post for more details.

**Comment by ggmoriyon** [comment]
> ```Connect-SPOService -Url https://[tenant]-admin.sharepoint.com -Credential admin@domain.com```

If the login fails, it's most likely because MFA is enabled, try without `-Credential` to trigger the login window:
```Connect-SPOService -Url https://[tenant]-admin.sharepoint.com -Credential admin@domain.com```
