### ISSUE TITLE
Problem with first bar on paths

### ISSUE THREAD

**Issue by oktorok** [vgrem/Office365-REST-Python-Client#318]
I have this piece of code that retrieve the content of a directory on sharepoint.

```     
        folder = ctx.web.get_folder_by_server_relative_url(l)
        ctx.load(folder)
        ctx.execute_query()
        folders = folder.folders
        ctx.load(folders)
        ctx.execute_query()
```

Being the path: `l='/sites/MySite/Documents partages'` returns error with file not found and pointing to the url:

https://sharepointdomain.sharepoint.com/sites/MySite/_api/Web/getFolderByServerRelativeUrl('sites%2FMySite%2FDocuments%20partages')

Inspectioning the url we can see that the first '/' is missing and if we try to add it with:
`       folder = ctx.web.get_folder_by_server_relative_url("/"+l)` (duplicating the first '/' as one is removed)

Now the script returns the correct content.

Is this a bug? Or has it a porpouse?

**Comment by xibriz** [comment]
Looking at my URLs I use something like `l='/Documents partages/'`

Have you tried that?

**Comment by oktorok** [comment]
Yep, you are right, like this works as expected. 

Thank you
