### ISSUE TITLE
Trouble uploading document with encoding

### ISSUE THREAD

**Issue by benpolinsky** [vgrem/Office365-REST-Python-Client#32]
Attempting in various ways to upload a file to Sharepoint without dismissing the encoding. Just a text or log file, but after uploading, I'm seeing new line characters (\n) and carriage returns (\r) all over the place.

I've tried via ClientRequest and ClientContext, and have been able to upload files both to a Document Library and to a List, but I'm sort of stumped at this point. Is there a header I can set to let SharePoint know of the encoding?

**Comment by benpolinsky** [comment]
I'm reading in a logfile and setting the result to the data property RequestOptions:
```
file = open(file_name, 'r')
file.close()
options.data = file.read()
data = self.request.execute_query_direct(options)
```

Somewhere, characters are being escaped.  Using Windows.
Paths have an added '\'
so:
C:\Whatever\Src
becomes
C:\\Whatever\\Src

**Comment by benpolinsky** [comment]
Ah, so it appears options.data is a dict.  What's the property I'm supposed to set on options.data to pass in content?

**Comment by jimr** [comment]
I don't think this code is overridable at present - the data passed in seems to get passed to the `json` parameter in `requests` rather than `data` (see [office365/runtime/client_request.py#L84](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/office365/runtime/client_request.py#L84)). I've worked around this as follows:

    with open(path_to_file, 'rb') as f:                                                                                                                                                                                                                                                                                                                                               
        options = RequestOptions(url)                                                                                                                                                                                                                                                                                                                                        
        context.authenticate_request(options)                                                                                                                                                                                                                                                                                                                        
        context.ensure_form_digest(options)                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                             
        # The reason we do this directly is because the                                                                                                                                                                                                                                                                                                                      
        # `request.execute_query_direct` call wants to send JSON, but that                                                                                                                                                                                                                                                                                                   
        # doesn't work if you want to upload, eg, an XLSX file (Requests                                                                                                                                                                                                                                                                                                    
        # just falls over trying to decode the contents as text).                                                                                                                                                                                                                                                                                                            
        result = requests.post(                                                                                                                                                                                                                                                                                                                                              
            url=url, data=f, headers=options.headers, auth=options.auth,                                                                                                                                                                                                                                                                                                     
        ) 

But ideally we'd be able to specify whether the contents were JSON or 'raw' when executing queries.

**Comment by benpolinsky** [comment]
Excellent - this works nicely.

Thanks very much!
