### ISSUE TITLE
Obtaining sharing links

### ISSUE THREAD

**Issue by davidorme** [vgrem/Office365-REST-Python-Client#323]
I am trying to use the package to create sharing links. I can successfully connect to my site and access folder and files but can't find the API to create a link. I've had a quick look through the functions and classes in `office365.sharepoint.files.file` but I think I'm looking in the wrong part of the object model.

Apologies for posting questions on the issue tracker, but can you give me a pointer?

**Comment by GeoLegalTech** [comment]
Hey, I am walking through the same issue. Did you find a solution?

**Comment by davidorme** [comment]
I did not, sorry.

**Comment by GeoLegalTech** [comment]
Thanks for the answer, I found a way to do it.

**Comment by davidorme** [comment]
If you could post an example of the code, that would be fantastic!

**Comment by GeoLegalTech** [comment]
I will prepare it in the next days

**Comment by vgrem** [comment]
Hi,

although this is the relatively old thread, but in case if anyone stumble upon it here is an example how to create a sharing link for the file:

```python
ctx = ClientContext(site_url).with_credentials(user_credentials)
file = ctx.web.get_file_by_server_relative_url("Shared Documents/Archive/Report.xlsx")

result = file.share_link(SharingLinkKind.AnonymousView).execute_query()

print(result.value.sharingLinkInfo.Url)
```

A complete example:  [`share_file.py`](/master/examples/sharepoint/sharing/share_file.py)



  


creates a sharing link for the
