### ISSUE TITLE
Version 2.3.1 does not work on Python 2.7 with authentication modules anymore

### ISSUE THREAD

**Issue by halldk** [vgrem/Office365-REST-Python-Client#326]
With version 2.3.1, on Suse Enterprise, this does not work. Issue is with authentication modules. Works with Python 3.6. Unable to get authentication methods to work within python 2.7 environment.

**Comment by vgrem** [comment]
Similar to #275:

> in version v2.2.1 was introduced a few changes, incompatible with Python 2.7, sorry about inconvenience.


[Version `2.3.5`](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.5) is finally backward compatible with Python 2.7 again
