### ISSUE TITLE
Trouble with sharepoint URLS

### ISSUE THREAD

**Issue by rwslippey** [vgrem/Office365-REST-Python-Client#327]
This isn't the first time I've had issues with programing sharepoint URLs, but this one has got me stumped.

`ClientRequestException: ('-<NUMBERS>, System.ArgumentException', 'serverRelativeUrl\r\nParameter name: Specified value is not supported for the serverRelativeUrl parameter.', "400 Client Error: Bad Request for url: https://TENANT.sharepoint.com/_api/Web/getFileByServerRelativeUrl('Shared%20Documents%2FBook.xlsx')?$select=ServerRelativeUrl")`

Everything else gets me 404 so I guess maybe I do have the URL correct?

`file_url = 'Shared Documents/Book.xlsx`'

**Comment by andreas-j-hauser** [comment]
@rwslippey I'm not sure it helps or not, but from time to time the "complete relative URL" is required. Try `/sites/**YOU-LIBRARY-NAME**/Shared Documents/Book.xlsx`

**Comment by vgrem** [comment]
Although this is and thread but starting from [`2.4.2` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.4.2) when it comes for files and folders addressing in SharePoint API,  it is supported both _site relative_ (e.g. `folder/filename.ext`) and _server relative_ (e.g.` /sites/mysite/folder/filename.ext`) url formats:

Example: address a file by _site relative_ url

```python
ctx = ClientContext(site_url).with_credentials(credentials)
file_url = 'Shared Documents/Report.xlsx'
file = ctx.web.get_file_by_server_relative_url(file_url).get().execute_query()
```
