### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by attibalazs** [vgrem/Office365-REST-Python-Client#33]
I am unable to import the module for some reason, i am using Python 3.6
Any ideas ?

> Traceback (most recent call last):
>   File "C:/Users/me/Projects/o365/snippets/sharepoint.py", line 14, in <module>
>     from office365.runtime.auth.authentication_context import AuthenticationContext
> ModuleNotFoundError: No module named 'office365'

**Comment by attibalazs** [comment]
I have installed your library using pip from PyPI, i saw you made recent change i don't think you have updated the package in PyPI to the latest version. I will try building it from source instead.

**Comment by attibalazs** [comment]
Cloning it from github and installing it using setup.py worked.

**Comment by kgadek** [comment]
This problem will be resolved with #35. The actual reason for the import problem was #30 which changed the API of the package.

For reference: PyPI package was created from bit older commit. The actual tag is on my fork: https://github.com/kgadek/Office365-REST-Python-Client/tree/v1.1.0
