### ISSUE TITLE
X-MSDAVEXT_Error: 917656; Access+denied when getting the SPOIDCRL cookie

### ISSUE THREAD

**Issue by nsmcan** [vgrem/Office365-REST-Python-Client#338]
Just recently (April 7, 2021), the user-credentials based authentication on our SharePoint 365 stopped working.

Request to `https://{tenant}/_vti_bin/idcrl.svc/` at line 232 of saml_token_provider.py returns '401 Unauthorized' with a header:
`X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.`

The SharePoint admins were not able to locate a change, causing this behavior

As a workaround I could suggest to feed the security token to an URL, used for non-federated systems: `https://{authorityUrl}/_forms/default.aspx?wa=wsignin1.0`
with the browser-like user agent header: 
`Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)`

That allows to authenticate with the `rtFa` and `FedAuth` cookies

I have prepared a pull request for your review

**Comment by vgrem** [comment]
Closing this one since has been released with [`2.3.3` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.3)
