### ISSUE TITLE
No module named urlparse

### ISSUE THREAD

**Issue by attibalazs** [vgrem/Office365-REST-Python-Client#34]
I got the following error: No module named urlparse

I managed to solve it by changing to from `urllib import parse as urlparse` in `saml_token_provider.py`

https://stackoverflow.com/questions/29358403/no-module-named-urllib-parse-how-should-i-install-it

I am using Python 3.6

**Comment by vgrem** [comment]
Greetings!

Unfortunately at the moment Python 3 runtime is not supported yet. Will try to find a time to make it compatible with both Python 2 & 3 and get back to you shortly.

**Comment by attibalazs** [comment]
Thanks for your hard work putting this library together. I have made some progress with it i will let you know  if see any more issues.
