### ISSUE TITLE
Using select statement, the URL shows commas between all characters

### ISSUE THREAD

**Issue by Lack-IT** [vgrem/Office365-REST-Python-Client#343]
This is my first time posting about an issue so please be kind :)
I'm using Python 3.8.5 and Office365-REST-Python-CLient 2.3.2

Here is the relevant part of my code:
list_source = ctx.web.lists.get_by_title("Employee Files")
emails_only = list_source.get_items().select("FullName,Last Name,EMail").filter('EMail ne null')
ctx.load(emails_only)
ctx.execute_query()

And here is the error I'm getting:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/office365/runtime/client_request.py", line 83, in execute_query
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://sitename.sharepoint.com/sites/employees/_api/Web/lists/GetByTitle('Employee%20Files')/items?$select=F,u,l,l,N,a,m,e,,,L,a,s,t,%20,N,a,m,e,,,E,M,a,i,l&$filter=EMail%20ne%20null

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sharepoint.py", line 56, in <module>
    ctx.execute_query()
  File "/usr/local/lib/python3.8/dist-packages/office365/runtime/client_runtime_context.py", line 133, in execute_query
    self.pending_request().execute_query()
  File "/usr/local/lib/python3.8/dist-packages/office365/runtime/client_request.py", line 87, in execute_query
    raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: ('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', 'The expression "F,u,l,l,N,a,m,e,,,L,a,s,t, ,N,a,m,e,,,E,M,a,i,l" is not valid.', "400 Client Error: Bad Request for url: https://sitename.sharepoint.com/sites/employees/_api/Web/lists/GetByTitle('Employee%20Files')/items?$select=F,u,l,l,N,a,m,e,,,L,a,s,t,%20,N,a,m,e,,,E,M,a,i,l&$filter=EMail%20ne%20null")

As you can see for some reason the letters in the select statement are getting expanded with commas and I've no idea why. Is this a bug or an issue with my code?

Please note that I have been making queries against SharePoint up until now successfully, and when I run the code without the select statement it works fine

**Comment by vgrem** [comment]
Greetings!

Indeed invalid request is getting generated since [`ClientObject.select(names)`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/office365/runtime/client_object.py#L68) expects names to be list of strings, like this:

` emails_only = list_source.get_items().select(["FullName","Last", "Name", "EMail"]).filter('EMail ne null')`
