### ISSUE TITLE
siteUsers

### ISSUE THREAD

**Issue by scggit** [vgrem/Office365-REST-Python-Client#344]
I have a list which has a column of User Type. Is there a way I can get the name information from the column value. 

I tried this code but the siteUsers returned seems to be empty.
ctx = ClientContext(site_url).with_credentials(ClientCredential("))
users = ctx.web.siteUsers
print(len(users))   ==> return 0
user = users.get_by_id(171)
print(user.properties) =======> return {}

Below is the working link to the user. I would like to know how to use this API to get Title or Name of user.
https://xxxx.sharepoint.com/teams/tp/outages/_api/web/getUserById(171)

**Comment by vgrem** [comment]
Greetings!

This is expected since the request don't get submitted to the server, here is an updated example to retrieve user: 

``` python

user = ctx.web.siteUsers.get_by_id(user_id)
ctx.load(user)   # prepare request 
ctx.execute_query()  # submit request to the server

```

**Comment by Xeyow** [comment]
Is there any way to use the above code from @vgrem but instead of searching in ctx.web to search in ctx.web.lists (pointing to a specific list)?
