### ISSUE TITLE
Download File - Does Not Exist

### ISSUE THREAD

**Issue by monkeyman51** [vgrem/Office365-REST-Python-Client#346]
Attempted to download a file from SharePoint and returned an error message.   Note, anything between square brackets is confidential information.

Error message is this:

      b'{"error":{"code":"-2130575338, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The file /sites/[site_name]/Shared Documents/[file_name].txt does not exist."}}}'

Here is the code I use:

          from office365.sharepoint.files.file import File
          from office365.sharepoint.client_context import ClientContext, ClientCredential
          
          
          main_url: str = 'https://[tenant_name].sharepoint.com/sites/[site_name]/'
          relative_url: str = '/sites/[site_name]/Shared%20Documents/text_file.txt'
          
          client_id: str = '[client_id]'
          client_secret: str = '[client_secret]'
          
          download_path: str = r'C:\Users\[user_name]\Documents\test_file.txt'
          
          ctx = ClientContext(main_url).with_credentials(ClientCredential(client_id, client_secret))
          
          response = File.open_binary(ctx, relative_url).content
          with open(download_path, 'wb') as output_file:
              output_file.write(response)

**Comment by vgrem** [comment]
Greetings!

The example looks legitimate, what appears to be issue here is most likely related with file name which contains unsupported symbols such as `%` and `#`, refer [this article](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api) for a more details

Anyway, in the latest release the addressing files and folders have been improved (in terms of adding support for [APIs based on ResourcePath](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api#new-apis-based-on-resourcepath-that-support--and-)), and the provided error should no longer occur.

**Comment by walkingstar1** [comment]
Apparently, its the the filename... I still get the error even after changing the filename to simple one.

**Comment by vipin1211** [comment]
Any update on this?
I am getting the same error with a simple file name

b'{"error":{"code":"-2130575338, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The file /sites/[site_name]/Shared Documents/SharePointPythonTest.xlsx does not exist."}}}'

**Comment by walkingstar1** [comment]
Apparently, I found that, it could be to do with the scope configured, on the site.

**Comment by vipin1211** [comment]
@walkingstar1 Where you able to fix the issue by setting the scope, if yes please add more details of code as to where to define the scope.

**Comment by walkingstar1** [comment]
@vipin1211 , On the SharePoint site, navigate here: https://<site collection url>/_layouts/15/appinv.aspx, Use your Client ID / App ID, and for "Permission Request XML", look at this article: https://medium.com/ng-sp/sharepoint-add-in-permission-xml-cheat-sheet-64b87d8d7600.

Setting the appropriate scope, and running the code, I was able to download the file successfully.

**Comment by vipin1211** [comment]
@walkingstar1 Thank you, that link definitely helped. The key was to add 'sitecollection' access as tenant level access will not work if you are not an admin.
