### ISSUE TITLE
Assistance with Sharepoint search functions

### ISSUE THREAD

**Issue by mark4409** [vgrem/Office365-REST-Python-Client#347]
I'm just wondering if I could have a little help with the search functions when working with Sharepoint?

As per the example, it seems as though you add the query parameters to the SearchRequest function as follows:

```
request = SearchRequest("FileType:aspx")
result = search.post_query(request)
```

So my questions are:
1. Whats the correct format for multiple query parameters? ie if I wanted to filter by FileType and by isDocument?
2. How can I add selectproperties for that? There are some properties that I need to explicitly enter here or else I don't get them in the response... eg ViewsLast1Days,ViewsLast2Days,ViewsLast3Days,ViewsLast4Days,ViewsLast5Days
3. How can I add extra parameters such as orderBy, trimDuplicates, and rowlimit?

**Comment by mark4409** [comment]
Basically I'd like to get the same response as I do with this query done in the browser:

https://site.sharepoint.com/_api/search/query?querytext=%27SiteName:https://site.sharepoint.com/sites/examplesite%27&selectproperties=%27Title,ViewsLast1Days,ViewsLast2Days,ViewsLast3Days,ViewsLast4Days,ViewsLast5Days,ViewsLast6Days,ViewsLast7Days,ViewsRecent,ViewsLastMonths1,ViewsLastMonths2,ViewsLastMonths3,ViewsLifetime,Path%27&trimDuplicates=false&rowlimit=500

**Comment by vgrem** [comment]
Greetings!

Extra parameters for [`Microsoft.Office.Server.Search.REST.SearchRequest` type ](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-srchcsom/d00cf1e6-3349-4521-90ae-dcce256a1e79) could be passed via `**kwargs` as demonstrated below:

Query

`https://{site}.sharepoint.com/_api/search/query?querytext=IsDocument:1&selectproperties=%27Title,Path%27&trimDuplicates=false&rowlimit=500
`

could be constructed like this (via `postQuery` method):

```
select_props_col = ClientValueCollection(str, ["Title", "Path"])
request = SearchRequest("IsDocument:1", SelectProperties=select_props_col, TrimDuplicates=False, RowLimit=500)
result = search.post_query(request).execute_query()
```

_P.S. Tend to agree, might not the most intuitive way, and could be improved in terms of API design by explicitly exposing query parameters via `SearchRequest `type._
