### ISSUE TITLE
Set a library column of type Person or Group 

### ISSUE THREAD

**Issue by remotain** [vgrem/Office365-REST-Python-Client#348]
Hello there!

I have a library column of type Person or Group, I am not sure to understand how I can set the value of this column based on the user's email address.

Thanks for the help!

**Comment by vgrem** [comment]
Greetings!

Since it also depends whether user field is multi or single valued, below are provided examples for both cases:    

To set a _single-valued_ user field (field name is `Manager`):


``` python

user = ctx.web.ensure_user(user_principal_name)  

item_to_create = tasks_list.add_item({
    "Title": "New Task",
    "Manager": FieldUserValue.from_user(user)
}).execute_query()
```




To set _multi-valued_ user field:

``` python 

user = ctx.web.ensure_user(user_principal_name)
multi_user_value = FieldMultiUserValue()
multi_user_value.add(FieldUserValue.from_user(user))

item_to_create = tasks_list.add_item({
    "Title": "New Task",
    "AssignedTo": multi_user_value,
}).execute_query()
```
