### ISSUE TITLE
I wanna list file in a folder , but it will list all the files in that site

### ISSUE THREAD

**Issue by xiaosagemisery** [vgrem/Office365-REST-Python-Client#350]
My code is very simple .

`def printAllContents(ctx, relativeUrl):
    library = ctx.web.get_list(relativeUrl)
    all_items = library.items.filter("FSObjType eq 0").expand(["File"]).get().execute_query()
    all_items_name = []
    for item in all_items:  # type: ListItem
        cur_file = item.file
        all_items_name.append(cur_file)
    return all_items_name

client_credentials = ClientCredential('XXXXXXXXXXXXXXXXXXXXXXXXX',
                                      '	XXXXXXXXXXXXXXXXXXXXXXXXX')
ctx = ClientContext('https://XXXXXXXXXXXX.sharepoint.com/sites/NewHireComputerTracker').with_credentials(
    client_credentials)
for file in printAllContents(ctx, '/sites/NewHireComputerTracker/Shared%20Documents/newhire'):
    print(file.name)`

    There is no files under newhire folder , all the files are under another folder named "used-record" which is also in the root folder like "new hire" folder， they are Parallel Relationship. But it will print all the file names in that site ,  in this case, it will print the file names under  '/sites/NewHireComputerTracker/Shared%20Documents/used-record'

can you please help?

**Comment by vgrem** [comment]
Hey,

sorry for not providing any input in time, but if it is still relevant or maybe someone else is looking across this thread, here are a few options to consider:

### Option 1 : enumerate files within a folder (files 1 level beneath only)


```python

ctx = ClientContext(site_url).with_credentials(credentials)

target_folder_url = "Shared Documents/Archive"
folder = ctx.web.get_folder_by_server_relative_url(target_folder_url).expand(["Files"]).get().execute_query()
for file in folder.files:  # type: File
    print(file.name)
```


### Option 2: enumerate files within a folder (nested)

```python

def enum_folder(parent_folder, fn):
    """
    :type parent_folder: Folder
    :type fn: (File)-> None
    """
    parent_folder.expand(["Files", "Folders"]).get().execute_query()
    for file in parent_folder.files:  # type: File
        fn(file)
    for folder in parent_folder.folders:  # type: Folder
        enum_folder(folder, fn)


def print_file(f):
    print(f.properties['ServerRelativeUrl'])


target_folder_url = "Shared Documents/Archive"
root_folder = ctx.web.get_folder_by_server_relative_url(target_folder_url)
enum_folder(root_folder, print_file)
```
