### ISSUE TITLE
Setting Metadata in Sharepoint

### ISSUE THREAD

**Issue by DaveyOldenburg** [vgrem/Office365-REST-Python-Client#354]
Hello!

I'm trying to set Metadata (columns) in sharepoint. 

I use the following script:

```
list_item = target_file_try.listitem_allfields

list_item.set_property("Column_name", "value")
```

When I set multiple, some of the columns get their metadata value, but some don't get any value.

I found out that spaces need a specific encoding, this doesn't seem to be the issue. 

Can you help me with this issue?

**Comment by vgrem** [comment]
Greetings!

Along with setting a property, the list item update operation (`ListItem.update`) needs to be submitted to the server (`execute_query`), here is a complete example for a reference ( where task item's `Title `metadata is getting updated):

```python

list_tasks = ctx.web.lists.get_by_title("Tasks")
items = list_tasks.items.get_by_id(task_id)
item_to_update = items[0]
item_to_update.set_property("Title", f"Task {task_prefix}")
item_to_update.update().execute_query()


```
