### ISSUE TITLE
Bug: Wrong URL when copying folder in sharepoint

### ISSUE THREAD

**Issue by qqqzhi** [vgrem/Office365-REST-Python-Client#356]
Hi team,

I think I found a bug in the code, when I was trying to copy a folder to another place in sharepoint, the srcUrl and destUrl given by code are, so the '/MySiteName/teams/' seems duplicated in the srcUrl and a '/' is missing in destUrl between MySiteName and the starting of my destUrl

`{'srcUrl': 'https://microsoft.sharepoint.com/teams/MySiteName/teams/MySiteName/Shared Documents/Test/BER20', 'destUrl': 'https://microsoft.sharepoint.com/teams/MySiteNameShared Documents/TestFolder', 'options': {'KeepBoth': False, 'ResetAuthorAndCreatedOnCopy': False, 'RetainEditorAndModifiedOnMove': False, 'ShouldBypassSharedLocks': False, '__metadata': {'type': 'SP.MoveCopyOptions'}}}`

**Comment by vgrem** [comment]
Hi,

thank you for reporting, indeed it confirmed to be a bug and has been resolved in [`2.3.5` version](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.5).


Similar thread: #360
