### ISSUE TITLE
How to upload a file to an specific folder in Sharepoint Using User Credentials

### ISSUE THREAD

**Issue by cwillromero** [vgrem/Office365-REST-Python-Client#357]
Good afternoon!
Can anyone tell me how to upload a file to an specific folder using user credentials (user and password) please?
I've tried using the get_folder_by_server_relative_url() and the using the upload_file() method but I get the 403 error, I'm not sure if it's because I'm using wrong the url_relative.
Thanks in advance. 
Greetings

**Comment by cwillromero** [comment]
Nevermind I did it thanks to the other issues.
Have a nice day!

**Comment by SunnyCCCh** [comment]
Hello,can you give a example on how to fix this situation ?
thank you very much.
