### ISSUE TITLE
Quick question - how to overwrite an existing file with a chunk upload?

### ISSUE THREAD

**Issue by mrranck** [vgrem/Office365-REST-Python-Client#359]
Good afternoon, this is a terrific library.  I was wondering where to edit the example code from item #40 's solution to overwrite the large file?  Thanks!

ctx = ClientContext(site_url, ctx_auth)
size_1Mb = 1000000
local_path = "./data/big_buck_bunny.mp4"
target_url = "/Shared Documents"
result_file = ctx.web.get_folder_by_server_relative_url(target_url).files.create_upload_session(local_path, size_1Mb, print_upload_progress)
ctx.execute_query()
print('File {0} has been uploaded successfully'.format(result_file.properties['ServerRelativeUrl']))

**Comment by vgrem** [comment]
Good afternoon!

To override a file,  calling the same method `FileCollection.create_upload_session` will do the trick: 

``` python 

def print_upload_progress(offset):
    print("Uploaded '{}' bytes from '{}'...[{}%]".format(offset, file_size, round(offset / file_size * 100, 2)))

target_folder = ctx.web.get_folder_by_server_relative_url(target_folder_url)
uploaded_file = target_folder.files.create_upload_session(local_path, size_chunk, print_upload_progress).execute_query()
```

**Comment by mrranck** [comment]
That worked, thank you very much!
