### ISSUE TITLE
How to get data from lookup column 

### ISSUE THREAD

**Issue by pavanbangad** [vgrem/Office365-REST-Python-Client#361]
Hi,

Do you have a code snippet on how to get SharePoint list items from lookup column?

**Comment by vgrem** [comment]
Hi there,

The following example demonstrates how to retrieve lookup field value (`Predecessors`) from a `Tasks `list:


```python 

tasks_list = ctx.web.lists.get_by_title("Tasks")
task_items = tasks_list.items.select(["Title", "Predecessors/Title", "Predecessors/Id"]).expand(["Predecessors"]).get().execute_query()

for item in task_items:  # type: ListItem
    task_predecessors = item.get_property('Predecessors')
```




> Note: You need to explicitly specify that the request returns projected fields from other lists and the values of lookups. To do this, we specify the field name in both the `$select` and `$expand` query options, refer the [official documentation](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests) for a more details

**Comment by pavanbangad** [comment]
Hi vgrem,

do you have a code snippet for fetching multiple lookup column in a list.

I have a list A which has 2 lookup column. I need to fetch value for both of them.

Thanks in advance!
