### ISSUE TITLE
beginner question to this module

### ISSUE THREAD

**Issue by Kickdak** [vgrem/Office365-REST-Python-Client#362]
Hey,
I'm trying to understand how to use this package.
But can't seem to get the hang of it.
How do I get file data for example?

My auth and everything of paths are correct.

I have found out how to upload and download but other than that I'm stuck.
![image](https://user-images.githubusercontent.com/44496037/120907034-7eb5c800-c65e-11eb-83c8-b74431939ba4.png)

**Comment by vgrem** [comment]
Hi there,

method `Web.get_file_by_server_relative_path` returns _a file metadata_  meaning what is depicted in provided screenshot is  expected result. 

It appears you are after to _download a file content_ , for that matter `File.download` method is intended, here is an example:


```python 


file_url = '/sites/team/Shared Documents/sample.docx'
ctx = ClientContext(settings['url']).with_credentials(client_credentials)
with open(download_path, "wb") as local_file:
    file = ctx.web.get_file_by_server_relative_path(file_url).download(local_file).execute_query()
```




And here is a [complete sample](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/files/download_file.py)

**Comment by Kickdak** [comment]
Hi,
Thanks for the answer, but maybe I was a little unclear.
I want to access the metadata of folders and files.
Like file version, last_edited, minor version, name, and so on.
As you can see in the picture I get None everywhere when I debug.

**Comment by vgrem** [comment]
In terms of `File`/`Folder `metadata it indeed might be a bit confusing. Understanding the way how SharePoint API itself is designed might make things look a bit clearer, specifically: 

- some metadata are _not directly exposed via `File`/`Folder`_ itself but retrieved _via associated `ListItem` instead_. For example system metadata  such as `Created`, `Modified ` which needs to be retrieved via `File.ListItemAllFields` property
- some metadata (properties) are not returned _by default_  (by API design) and needs to be retrieved _explicitly_ via `expand` method, for example `File.Versions` property

The following example summarizes it:

``` python 

file = ctx.web.get_file_by_server_relative_path(file_url).expand(["versions", "listItemAllFields"]).get().execute_query()
file_name = file.name
file_versions = file.versions  # <- collection type
file_ver_num = file.major_version
file_modified_by_id = file.listItemAllFields.get_property("EditorId")
```

**Comment by Kickdak** [comment]
Thanks!
This made it a little clearer and can continue my learning.
Thanks for your work ^^

**Comment by rangannanaik** [comment]
How to get  modified  by  information ?

**Comment by nmz787** [comment]
in the call to `listItemAllFields.get_property("EditorId")` how can I find all other acceptable entries for `get_property`? For example, it seems `EditorId` returns some sort of Microsoft-created user-ID, which is a number I do not recognize. How do I get the "EditorName" (that string returns `None`)? What else is available?

**Comment by karges612** [comment]
i  am also facing the same exact issue. iam able to download and list the files in a folder but unable to know who has uploaded the files using the same context object. tried the above two links also.  repeatedly getting "NoneType" for almost all of the metadata property.
any help would be greatly appreciated thanks in advance.

**Comment by nklsla** [comment]
> i am also facing the same exact issue. iam able to download and list the files in a folder but unable to know who has uploaded the files using the same context object. tried the above two links also. repeatedly getting "NoneType" for almost all of the metadata property. any help would be greatly appreciated thanks in advance. @vgrem

Did you try the `expand()` method? That solved my issue. e.g.
```
# get folder id
_target_folder_id = (
        ctx.web.get_folder_by_server_relative_path(sp_folder)
        .expand(["UniqueId"])
        .get()
        .execute_query()
    ).get_property("UniqueId")

# Get folder object with id
target_folder = ctx.web.get_folder_by_id(_target_folder_id)
```

Then I could upload files without exceeding the url-limit of 255 characters.
