### ISSUE TITLE
Can't use the function get_file_by_server_relative_path

### ISSUE THREAD

**Issue by crimzon96** [vgrem/Office365-REST-Python-Client#363]
In the repo i see this function but when im trying to use it it says its not on the Web object any idea?

(Pdb) ctx.web.get_file_by_server_relative_path
*** AttributeError: 'Web' object has no attribute 'get_file_by_server_relative_path'
(Pdb) ctx.web.get_folder_by_server_relative_url
<bound method Web.get_folder_by_server_relative_url of <office365.sharepoint.webs.web.Web object at 0x7f952dc38550>>

**Comment by vgrem** [comment]
Hi there,

Are you positive [`2.3.4` version](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.4) of library is being used or above?  `Web.get_file_by_server_relative_path` method has been introduced in mentioned version.

**Comment by ANVLISTENER** [comment]
Same issue here. I see the a lot of issues coming from web object with little to no function available at all. This where same issue for small and large files given the example in repository occurs. it does create the mess. rest everything is perfectly fine. Trying to download the excel. Now, face the issue. can you push a code for the in the excel having lot of troubles. pls. Thank you.

**Comment by vgrem** [comment]
Since the support `Web.get_file_by_server_relative_path`  property has been introduced , propose to close this issue. 

![image](https://user-images.githubusercontent.com/1596072/132310992-99ad3e1b-eb01-416e-9128-8811cf2a0e43.png)
