### ISSUE TITLE
In OData, open collection properties are not supported

### ISSUE THREAD

**Issue by AHemanthika** [vgrem/Office365-REST-Python-Client#365]
In sharepoint I have a column " Deck type" which accepts multiple choice values
To update the column value of a particular file I'm executing the below code
```
item = file.listItemAllFields
ctx.load(item)
ctx.execute_query()
multi_choice_value = FieldMultiChoiceValue(["Introduction"])
item.set_property("Deck_x0020_type",multi_choice_value)
item.update()
ctx.execute_query()
```
Upon executing this code I'm getting the below error
```
ClientRequestException: ('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', "An open collection property 'Deck_x0020_type' was found. In OData, open collection properties are not supported."
```
Could anyone please tell the solution for this error?

**Comment by vgrem** [comment]
Greetings,

thank you for reporting it, it confirmed to be a bug and could be reproduced in version 2.3.4 version and related with List Item update method when entity type is incorrectly getting determined.


Has been resolved in the [latest (`2.3.5`) version](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.5)
