### ISSUE TITLE
Non-Text mail attachment

### ISSUE THREAD

**Issue by KubaTaba1uga** [vgrem/Office365-REST-Python-Client#371]
Hi,
When sending a message with attachment bigger than 4MB which is no text-file format, in logs i can found that the response status code is  200 but the message is not being send.
I tried different files extensions like mp3, exe or wav, but the message is not appearing in receiver mailbox.
Any walkarounds on this?

**Comment by vgrem** [comment]
Starting from [`2.3.9` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.9)  `Message.upload_attachment` has been introduced which supports  uploading large attachments, for example:


```python
local_path = "./large_attachment.mp3"
message = (
    client.me.messages.add(
        subject="Meet for lunch?",
        body="The new cafeteria is open.",
        to_recipients=[
            "fannyd@contoso.onmicrosoft.com"
        ],
    )
    .upload_attachment(local_path, print_progress)
    .send()
    .execute_query()
)

```
