### ISSUE TITLE
Ability to manage file object sharing / permissions

### ISSUE THREAD

**Issue by kevinglasson** [vgrem/Office365-REST-Python-Client#373]
Is there an example / is it possible to manage file level sharing / permissions?

I tried to figure this out but it seems there is only the ability to list the permissions but not to modify them?

**Comment by vgrem** [comment]
Greetings,

here is an example which demonstrates how to assign user with `Contributor` role to a file:


``` python 

client = ClientContext(site_url).with_credentials(test_client_credentials)
file_url = "Shared Documents/Expenses.xslx"

# get Contributor role
role_def = client.web.role_definitions.get_by_type(RoleType.Contributor)

# get user by email
user = client.web.siteUsers.get_by_email(test_user_principal_name_alt)

# assign user with role to file
target_file = client.web.get_file_by_server_relative_path(file_url)
target_file.listItemAllFields.add_role_assignment(user, role_def).execute_query()


```


Refer [`RoleAssignmentCollection.Add` method](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee544637(v=office.15)) for a more details
