### ISSUE TITLE
memory leak in upload session

### ISSUE THREAD

**Issue by beliaev-maksim** [vgrem/Office365-REST-Python-Client#376]
When you upload a large file using upload session you will see that somewhere there is a memory leak that consumes almost all the RAM

Code to reproduce:
~~~python
import os

from office365.runtime.http.request_options import RequestOptions
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.authentication_context import AuthenticationContext


def print_upload_progress(offset, total_size):
    print("Uploaded '{}' bytes from '{}'...[{}%]".format(offset, total_size, round(offset/total_size*100, 2)))

site_url = "https://mycompany.sharepoint.com/sites/mysite"

app_principal = {
    'client_id': os.environ["client_id"],
    'client_secret': os.environ["client_secret"]
}

context_auth = AuthenticationContext(url=site_url)
context_auth.acquire_token_for_app(client_id=app_principal['client_id'],
                                   client_secret=app_principal['client_secret'])

ctx = ClientContext(site_url, context_auth)
target_folder = "Shared Documents/beta_builds/"
target_folder = ctx.web.get_folder_by_server_relative_url(target_folder)

file_path = r"C:\Users\mbeliaev\Downloads\10Gb_file.zip"
size_chunk = 1024*100
file_size = os.path.getsize(file_path)

result_file = target_folder.files.create_upload_session(file_path, size_chunk, print_upload_progress, file_size)

ctx.execute_query()
~~~

**Comment by beliaev-maksim** [comment]
everytime `data = file_object.read(size)` is executed, memory is appended with chunk size until the whole file is loaded into memory

~~~python
def read_in_chunks(file_object, size=1024):
    """Lazy function (generator) to read a file piece by piece.

    :type size: int
    :type file_object: typing.IO
    """
    while True:
        data = file_object.read(size)
        if not data:
            break
        yield data
~~~

**Comment by beliaev-maksim** [comment]
@vgrem 
I think I found a way, please check if you find it appropriate #377

**Comment by beliaev-maksim** [comment]
@vgrem 
I have to reopen the issue since your last updates reverted the bug
![grafik](https://user-images.githubusercontent.com/51964909/129081983-bdd5c990-3b0c-4f1a-bce2-59ab21c443d6.png)

and after some time:
![grafik](https://user-images.githubusercontent.com/51964909/129082087-d773786a-57e5-4c7d-b904-ad575f913a33.png)


can you please fix it?

**Comment by vgrem** [comment]
Thanks for catching it (again), needs to be verified..

**Comment by beliaev-maksim** [comment]
tested again latest master and works fine again 🤦‍♂️
thanks and sorry for bothering with it

I checked implementation and only concern is about closure of the file on fail. But I assume script execution will also stop in such conditions in most of the cases
