### ISSUE TITLE
Question: Sharepoint Filter example

### ISSUE THREAD

**Issue by vpistis** [vgrem/Office365-REST-Python-Client#378]
Hi @vgrem ,

I searched into the code and docs, but I have not seeing any example about filtering Sharepoint lists.
I use some code like this: `sp_lists = ctx.web.lists.filter("filter=(Created gt 2021-07-13T09:59:32Z)")` and this `sp_lists = ctx.web.lists.filter("Created gt 2021-07-13T09:59:32Z")`, but it returns  all elements.

Please, has you some simple example about filtering by date or also any other field, please?

Thank you so mutch

**Comment by vgrem** [comment]
Greetings! 

i wonder why SharePoint is not complaining and all the data is getting retuned :), but the valid filter expression is expected to be specified like this:


```
ctx.web.lists.filter("Created gt '2021-07-13T09:59:32Z'")

                                 ^^^^^^^^^^^^^^^^^^^^^
                              datetime is enclosed and passed with single quotes
```
                                                 




Here a grammar for `$filter` query option depicted on picture ([source](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#supported-odata-query-options))
![image](https://user-images.githubusercontent.com/1596072/125352335-cb7d7480-e369-11eb-8478-4851882cd031.png)




It seems there is two

**Comment by vpistis** [comment]
Hi,

I checked the docs and tested your suggestion, but it not solve :( 
Is possible the `filter` must be used in another way?

This is my code, without sensitive informations:
```python
from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.client_context import ClientContext

site_url = "https://{MYDNS}.sharepoint.com/sites/{SITENAME}/"
sp_list = "SP_LIST_NAME"
ctx = ClientContext(site_url).with_credentials(UserCredential("{MYUSERNAME}", "{MYPASSWORD}"))

print("CTX: {}".format(ctx))

sp_lists = ctx.web.lists.filter("Created gt '2021-07-30T09:59:32Z'")
# print("SP LIST {}".format(sp_lists))
s_list = sp_lists.get_by_title(sp_list)
l_items = s_list.get_items()
ctx.load(l_items)
ctx.execute_query()

for item in l_items:
    print("ITEM: ID {}, Created {}".format(item.properties['ID'], item.properties['Created']))

```

This code, IMHO, it must be return no elements :)

Thank you for your support!

**Comment by vpistis** [comment]
Ok SOLVED, I have found the right way to filtering results:

```python
from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.client_context import ClientContext

site_url = "https://{MYDNS}.sharepoint.com/sites/{SITENAME}/"
sp_list = "SP_LIST_NAME"
ctx = ClientContext(site_url).with_credentials(UserCredential("{MYUSERNAME}", "{MYPASSWORD}"))

print("CTX: {}".format(ctx))

sp_lists = ctx.web.lists
# print("SP LIST {}".format(sp_lists))
s_list = sp_lists.get_by_title(sp_list)
l_items = s_list.get_items().filter("Created gt '2021-07-30T09:59:32Z'")
ctx.load(l_items)
ctx.execute_query()

for item in l_items:
    print("ITEM: ID {}, Created {}".format(item.properties['ID'], item.properties['Created']))
```

Maybe can be used into the example code for helping someone else?

Thank you for your support and for maintain this project!
