### ISSUE TITLE
Is it possible to create a document set in a folder?

### ISSUE THREAD

**Issue by amberzaragoza** [vgrem/Office365-REST-Python-Client#379]
I have tried to create a document set in a folder, but it does not work. I do not get any error output, but the document set doesn't get generated either.

**Comment by vgrem** [comment]
Greetings!

Thank you for reporting this, indeed, incorrect folder addressing prevented the creation of a set of documents under certain circumstances (namely sub folder), in the latest version the support for sets of documents ([`2.3.6`](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.6)) has  been improved.

The following example demonstrates how to create a document set (named `Orders`) under a sub folder `Archive/2019`:


```python

parent_folder_path = "Archive/2019"
doc_set_name = "Orders"

test_client_credentials = ClientCredential(client_id,client_secret)
client = ClientContext(site_url).with_credentials(client_credentials)
target_folder = client.web.default_document_library().root_folder.folders.get_by_url(parent_folder_path)

doc_set = DocumentSet.create(client, target_folder, doc_set_name).execute_query()
```
