### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by attibalazs** [vgrem/Office365-REST-Python-Client#38]
I am getting an error when running your example code for file listing from Sharepoint.

> NameError: name 'basestring' is not defined

```
@staticmethod
    def encode_method_value(value):
        if isinstance(value, basestring):
            value = "'{0}'".format(value)
        elif isinstance(value, bool):
            value = str(value).lower()
        return value
```

**Comment by vgrem** [comment]
The issue has been resolved. `basestring` needs to be explicitly imported like this:

`from requests.compat import basestring`
