### ISSUE TITLE
Managed Metadata column upload/edit failure

### ISSUE THREAD

**Issue by dankrzeminski32** [vgrem/Office365-REST-Python-Client#380]
Hi,

I am attempting to write to a managed metadata column in my SharePoint Document Library. I have certain keys set up and I am using the internal name of the keys and the GUID of the Term values. 

![Screenshot 2021-07-27 132652](https://user-images.githubusercontent.com/76189617/127208013-d6f16611-7edf-449a-acff-24c10f430824.png)

However when I try to run my program, the file gets uploaded successfully but the managed metadata fails. It even shows up as registered when I do item.properties

The error message I am getting is ""An unexpected 'PrimitiveValue' node was found when reading from the JSON reader. A 'StartObject' node was expected.""400 Client Error: Bad Request for url: (my share point site doc library)"

**Comment by dankrzeminski32** [comment]
Note: I have also attempted just using the key name as a value in the dict.

**Comment by dankrzeminski32** [comment]
Note: I tried changing "context.execute_query" to "context.execute_batch" and I am now recieving the error "Cannot deserialize data for type Microsoft.SharePoint.Taxonomy.TaxonomyFieldValue."

**Comment by vgrem** [comment]
Greetings!

it depends whether taxonomy field is a _single_ or _multi_ valued, in OM the following types are available for that matter:

- `TaxonomyFieldValue` -  represents a single value held in a `TaxonomyField` object
- `TaxonomyFieldValueCollection` - represents the multi-value object for the taxonomy column.

In case of _single valued_ taxonomy field, its value could be updated for list item like this: 


```python
tax_field_value = TaxonomyFieldValue("Sweden", "f9a6dae9-633c-474b-b35e-b235cf2b9e73")
item_to_update.set_property("Country", tax_field_value).update().execute_query()
```


where 

- `Country` is a field (_internal_) name
- and `Sweden`, `f9a6dae9-633c-474b-b35e-b235cf2b9e73` are term label and term guid respectively


Here is a complete example which demonstrates how to create list item and set single-valued (`Country`) and multi-valued (`Countries`) taxonomy field values:

```python 
ctx = ClientContext(site_url).with_credentials(client_credentials)

tasks_list = ctx.web.lists.get_by_title("Tasks")

tax_field_value = TaxonomyFieldValue("Sweden", "f9a6dae9-633c-474b-b35e-b235cf2b9e73")
item_to_create = tasks_list.add_item({
    "Title": "New task",
    "Country": tax_field_value,
    "Countries": TaxonomyFieldValueCollection([tax_field_value])
}).execute_query()
print("List item created.")
```

 
**Note**  

In `[2.3.5` version](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.5) unfortunately a bug was found which prevents updating multi-valued taxonomy fields, to circumvent this it is proposed to update to the latest version via GitHub (until a new package will be released to PyPi):

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`

**Comment by kamrunsumi** [comment]
I want to update document libraries managed metadata column. Even though the code says my update is successful, there is no change in the sharepoint site.
What am I missing here? Could you please help?
Here is the screenshot of my code. 
![gitup](https://user-images.githubusercontent.com/43836648/219131786-b69a530e-e421-49da-b99b-41a32b075180.PNG)

**Comment by EKOLX** [comment]
I have the same issue. I'm trying to update multiple terms and getting error:

`Error: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-1, Microsoft.SharePoint.Client.ClientServiceException","message":{"lang":"en-US","value":"Cannot deserialize data for type Microsoft.SharePoint.Taxonomy.TaxonomyFieldValueCollection."}}}`

This is the code:
```
const list = this.sp.web.lists.getByTitle(SITE_PAGES);
const tags = terms.map(term => ({
    Label: term.name,
    TermGuid: term.termSet,
    WssId: -1,
}));
const i = await list.items.getById(itemId).update({ Tags: tags });
```

@vgrem  from where you **import** `TaxonomyFieldValue`  and `TaxonomyFieldValueCollection`?
