### ISSUE TITLE
test coverage and design intent

### ISSUE THREAD

**Issue by timcoote** [vgrem/Office365-REST-Python-Client#385]
Thanks for this repo.

The MS APIs seem complex and it's good to get a more pythonic abstraction - although I can see that may be fragile if MS changes its designs.

Looking at the Sharepoint API, there is an abstraction for folders, but there doesn't seem to be any test coverage for it. There is some coverage for `folder` methods in the `web` part of the code (eg `ensure_folder_path`). If I've analysed this correctly, it is intentional or is the idea that the `folders` abstraction will supersede the `web` mechanism?

**Comment by vgrem** [comment]
Greetings!

in terms of API design changes, unlikely, it least no evidence to support it still. 
What seems more likely, the evolution of unified MS Graph API and bringing more SharePoint API features under its endpoint.


In terms of `folders` namespace, the library covers at least all the standard operations [listed here](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee538304(v=office.15)). There is also a [folders examples section](../examples/sharepoint/folders)  where demonstrated how to:

- [create a nested folder ](../examples/sharepoint/folders/create_nested_folders.py)
- [create document set](../examples/sharepoint/folders/create_docset.py)
- [copy folder ](../examples/sharepoint/folders/copy_folder.py)
- [download files from a folder ](../examples/sharepoint/folders/download_folder.py)

 
Speaking of `Folder.ensure_folder_path` method, it is intended for creating a nested folder.

**Comment by timcoote** [comment]
thanks.
