### ISSUE TITLE
import of graph client fails due to incorrect path import of generator

### ISSUE THREAD

**Issue by rikeshtailor** [vgrem/Office365-REST-Python-Client#387]
![image](https://user-images.githubusercontent.com/19854395/129189729-80a15fbc-0232-41bc-a992-10617cdf977e.png)

**Comment by rikeshtailor** [comment]
actually the issue is not this.  I install the latest package using pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git

however when i look in libs/site/packages/office365 i dont see the folder generator

**Comment by vgrem** [comment]
Greetings,


thank you for catching it, confirm to be a bug since is expected to derive from `office365.entity.Entity` type, maybe you could adjust  PR in this regard?

**Comment by vgrem** [comment]
... and right, `generator` package is no longer included in production version

**Comment by rikeshtailor** [comment]
created pull request.  Thanks

https://github.com/vgrem/Office365-REST-Python-Client/pull/389
