### ISSUE TITLE
downloading files from sharepoint breaks with v2.3.6

### ISSUE THREAD

**Issue by josefschabasser** [vgrem/office365-rest-python-client#399]
Hello! We recently tried to upgrade this library from v2.3.5 to v2.3.6 and downloading files from sharepoint stopped working. We always receive HTTP 404. As soon as we downgrade to v2.3.5 it starts working again.

Here's the code that we are using, trimmed down to the essential part and tested with v2.3.5 (works) and v2.3.6 (breaks).
```python
from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.files.file import File
from office365.runtime.client_request_exception import ClientRequestException

try:
    with open('./test.csv', 'wb') as local_file:
        File.from_url('https://company.sharepoint.com/sites/Demo/path/to/test.csv').with_credentials(
            UserCredential(user_name='username@company.com', password='supersecret')
        ).download(local_file).execute_query()
except ClientRequestException as e:
    msg = 'Sharepoint download failed:'
    print(msg, e.message)
```

Best regards

**Comment by josefschabasser** [comment]
Here's a detailed error message:
```
office365.runtime.client_request_exception.ClientRequestException: ('-2130575338, Microsoft.SharePoint.SPException', "Die Datei '/sites/Demo/path/to/test.csv' ist nicht vorhanden.", "404 Client Error: Not Found for url: https://company.sharepoint.com/_api/Web/getFileByServerRelativePath(DecodedUrl='%2Fsites%2FDemo%2Fpath%2Fto%2Ftest.csv')?$select=ServerRelativeUrl")
```

**Comment by vgrem** [comment]
Greetings,

it's been confirmed to be a bug related with the order in which query queue is executed.

Anyway the provided error should no longer occur in the _latest_ version which could be grabbed via GitHub:

`pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git`

and expected to be released in the  forthcoming version: `2.3.7`

**Comment by vgrem** [comment]
Resolved in the [latest release  (`v.2.3.7`)](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.7)

**Comment by josefschabasser** [comment]
Thanks for the nice work! Successfully tested with version 2.3.7! :+1:
