### ISSUE TITLE
How to download old version files?

### ISSUE THREAD

**Issue by kazukiaaaa** [vgrem/Office365-REST-Python-Client#400]
When downloading minor version 0.5 I understand that you can get the file by the following URL.
URL:https://tenant.sharepoint.com/sites/base/_api/web/GetFileByServerRelativeUrl('/sites/base/sample.txt')/versions(5)/$value

Is it possible to download a file from the above URL using this function?
function: ctx.web.get_file_by_server_relative_path(file_url).download(local_file).execute_query()

**Comment by stefanstapinski** [comment]
Where do you get "/versions(5)/$value" from? 

I'm still having trouble with all examples, I can read the library site but I'm not able to read items in a folder

**Comment by vgrem** [comment]
Greetings!

Managing file versions were somewhat indeed limited and the only option to download the content for a specific version was to construct a custom request. 

Starting from [`2.3.8` version](https://pypi.org/project/Office365-REST-Python-Client/) the library _natively_ supports managing file versions, here are a few examples:


### Example: download a specific file version  content

```python 
ctx = ClientContext(test_team_site_url).with_credentials(credentials)
file_url = "/sites/team/Shared Documents/Guide.docx"
version = ctx.web.get_file_by_server_relative_path(file_url).versions.get_by_id(512)  #address file version by version identifier
download_path = os.path.join(tempfile.mkdtemp(),  os.path.basename(file_url))
with open(download_path, "wb") as local_file:
    file = version.download(local_file).execute_query()
```


### Delete a file version

```python
ctx = ClientContext(test_team_site_url).with_credentials(credentials)
file_url = "/sites/team/Shared Documents/Guide.docx"
target_file = ctx.web.get_file_by_server_relative_path(file_url)
versions = target_file.versions.top(1).get().execute_query()
versions[0].delete_object().execute_query()
```


All another [API methods](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee537767(v=office.15)) are also supported.

**Comment by kazukiaaaa** [comment]
Thank you for your generous support!
