### ISSUE TITLE
Sharepoint Office365 REST Python Client get users

### ISSUE THREAD

**Issue by Xeyow** [vgrem/Office365-REST-Python-Client#403]
Hello,

I am trying to integrate SharePoint in one of my Python Scripts and I need to grab the users from a SP list. Until now, I managed to log in, search for a specific list, and enumerate all of its items.

```
def enum_items(list):
    items = list.items
    ctx.load(items)
    ctx.execute_query()
    for index, item in enumerate(items):
        print("{0}: {1}".format(index, item.properties['Email']))
```

The 'Email' column's value is set to User.email like so:

```
{
   "$schema": "https://developer.microsoft.com/json-schemas/sp/v2/column-formatting.schema.json",
   "elmType": "div",
   "txtContent": "[$User.email]"
}
```

Basically the Email is automatically set when a new user is added in the User column.

Some entries where manually added, and others use the above code. For those that were manually added it prints the email, but for the other, it prints: "None".

If I change the 'Email' to 'User', I get the following error, like it cannot find that column or so:

```
    print("{0}: {1}".format(index, item.properties['User']))
KeyError: 'User'
```

Is there anyway I can grab the USER object, and then use its properties (which ever those are) to grab some information about it?

Thanks!

**Comment by vgrem** [comment]
Greetings,

regarding

> Some entries where manually added, and others use the above code. For those that were manually added it prints the email, but for the other, it prints: "None".

this is by SharePoint API design itself, not all the properties are getting returned _by default_, for instance User field value. It  needs to be _explicitly requested_,  in terms of this library and given the provided example, the line: 
 
`ctx.load(items)`

could to be replaced with: 

`ctx.load(items, ["Id","UserFieldName"])`

where the second argument accepts the list of selected properties (_field internal names_) to be returned

**Comment by Xeyow** [comment]
Just to add some more info on this issue.

The User column has "User" as field internal name, and it's set as **Person or Group**. I have other c

I tried the code down below:

```
def enum_items(list):
    items = list.items
    ctx.load(items, ["User"])
    ctx.execute_query()
    for index, item in enumerate(items):
        print("{0}: {1}".format(index, item.properties['Email']))
```

And I get the following error:

`office365.runtime.client_request_exception.ClientRequestException: ('-1, Microsoft.SharePoint.SPException', "The query to field 'User' is not valid. The $select query string must specify the target fields and the $expand query string must contains User.", "400 Client Error: Bad Request for url:`

If I use other columns like "Group" and "UpdateRequest", like so:

```
def enum_items(list):
    items = list.items
    ctx.load(items, ["Group", "UpdateRequest"])
    ctx.execute_query()
    for index, item in enumerate(items):
        print("{0}: {1}".format(index, item.properties['UpdateRequest']))
```

It prints out the correct information for the column UpdateRequest

```
0: Requested
1: Requested
2: Group Transfer
```

I also tried searching for the ID of a an item that has a specific value for the Group/UpdateRequest column. And it works, I end up with the ID of that item... But I still can't use it to retrieve the email (or the name of the user).

**Comment by Xeyow** [comment]
I couldn't find anything to grab the USER, and then grab its email. In C# it's pretty straight forward.

```
public SP.User getSPuser(String inputUserName, ClientContext context)
        {
            UserCollection usersGroup = context.Web.AssociatedMemberGroup.Users;
            context.Load(usersGroup);
            context.ExecuteQuery();

            List<string> users = new List<string>();
            string[] username = inputUserName.Split(' ');
            foreach (User u in usersGroup)
            {
                int matches = 0;
                for (int i = 0; i < username.Length; i++)
                {
                    if (u.Title.Contains(username[i]))
                    {
                        matches++;
                    }
                }
                if (matches == username.Length)
                {
                    users.Add(u.Title);
                }
            }

            SP.User spUser = null;
            spUser = context.Web.EnsureUser(users[0]);
            context.Load(spUser);
            string useremail = spUser.Email.ToString();
            try {context.ExecuteQuery(); }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return spUser;
        }
```

This code is used to search for a specific user based on its name. If all of its first names/last names are found, a spUser object is created. Then you can call spUser.Email.ToString() to grab its email. 

Is there anything alike in Python?

**Comment by vgrem** [comment]
Hi,

affirmative, it is supported, here is an example how to extract user email from user collection (converted into Python version):

```python
group_users = ctx.web.associatedMemberGroup.users.get().execute_query()
users_emails = [u.properties["Email"] for u in group_users]
```
