### ISSUE TITLE
Whether the check-in operation is supported (SharePoint)

### ISSUE THREAD

**Issue by kvarg-ru** [vgrem/Office365-REST-Python-Client#409]
Hello guys!

After uploading the file to SharePoint, I've realized that nobody can see this until I check-in this file to SharePoint. Is it exist some method in Office365-REST-Python-Client for check-in files after uploading?

Thanks!

---
Best Regards,
Mike

**Comment by vgrem** [comment]
Greetings!

indeed, when library setting

> Require documents to be checked out before they can be edited?

is enabled, upon file upload it needs to be explicitly checked in afterwards. 

Here is an example:

```python
client = ClientContext(site_url).with_credentials(credentials)

path = "./Sample.rtf"
with open(path, 'rb') as content_file:
    file_content = content_file.read()

list_title = "Documents"
target_folder = client.web.lists.get_by_title(list_title).root_folder
target_file = target_folder.upload_file(os.path.basename(path), file_content)
target_file.checkin("Uploaded file", 1)
client.execute_query()

```

where  in `File.checkin(comment, checkin_type)` method, `checkin_type` parameter specifies the type of check-in and could accept  the following value:  
- `0` (MinorCheckIn) 
- `1` (MajorCheckIn)  
- `2` (OverwriteCheckIn)
