### ISSUE TITLE
Deleting list items does not work

### ISSUE THREAD

**Issue by robesv** [vgrem/Office365-REST-Python-Client#41]
The examples seem outdated when it comes to using ClientRequest objects. The constructor does not seem to take both a url and AuthenticationContext anymore and execute_query_direct now takes one RequestOptions object instead of several parameters.

I have tried to recreate the example using the current API, but have not succeeded. The below code at least, results in a requests library error: 'AuthenticationContext' object is not callable.

```
ctx_auth = AuthenticationContext(url)
        if ctx_auth.acquire_token_for_user(username, password):
            request = ClientRequest(ctx_auth)
            url = "{0}/_api/web/lists(guid'{1}')/items({2})".format(
                url,
                list_guid,
                item_id)
            options = RequestOptions(url)
            options.set_header('IF-MATCH', '*')
            options.set_header('X-HTTP-Method', 'DELETE')
            options.method = HttpMethod.Delete
            options.auth = ctx_auth
            data = request.execute_query_direct(options)
        else:
            print ctx_auth.get_last_error()
```

Can you please help me understand how to delete list items using the current API?

**Comment by italonesi** [comment]
Any news on that one please? Same happens when delete a given item list. Thank you and keep up the great work guys.

**Comment by vgrem** [comment]
Greetings,

how about to delete `ListItem` this way:

```
item_to_delete = ctx.web.lists.get_by_id(list_guid).get_item_by_id(item_id)
item_to_delete.delete_object()
ctx.execute_query()
```
