### ISSUE TITLE
Module Not found error: office365 not found

### ISSUE THREAD

**Issue by chrisvgranicus** [vgrem/Office365-REST-Python-Client#411]
I have seen this issue with some resolutions already, but none have worked for my issue. I have pip installed the latest version of office365(V 2.2.0)  to my knowledge using the command: pip install office365-rest-client

i am trying to import using the following lines of code:

```
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File
```

I receive the following error:
ModuleNotFoundError: No module named 'office365'

Just to test it out, I uninstalled and reinstalled pandas, then successfully imported pandas into my project.

**Comment by vgrem** [comment]
Greetings!

It appears you refer to a way too outdated package, thats seems the reason why the provided error occurs.

The _latest_ (`2.3.8` at the moment) version could be downloaded from _default_ package index: [Office365-REST-Python-Client ](https://pypi.org/project/Office365-REST-Python-Client/) 

`pip install Office365-REST-Python-Client`

**Comment by syalamanchili-tonik** [comment]
<html>
<body>


File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/office365/runtime/client_object.py", line 4, in <module>
--
584 | from typing import (
585 | ImportError: cannot import name 'ParamSpec' from 'typing' (/root/.pyenv/versions/3.9.17/lib/python3.9/typing.py)


</body>
</html>

Getting this error since last two hours with latest version of this package "Office365_REST_Python_Client-2.5.0"

**Comment by dishit2141** [comment]
@syalamanchili-tonik  is it resolved?
Please guide getting similiar error
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.files.file import File

error:
Traceback (most recent call last):
  File "C:\Users\Dishit.Pandya\OneDrive - Streebo Inc\R&D-projects\PDF Crawler - python - flask\python\downloadFiles.py", line 1, in <module>
    from office365_api import SharePoint
  File "C:\Users\Dishit.Pandya\OneDrive - Streebo Inc\R&D-projects\PDF Crawler - python - flask\python\office365_api.py", line 10, in <module>
    from office365.sharepoint.client_context import ClientContext
ModuleNotFoundError: No module named 'office365'
