### ISSUE TITLE
Receive emails

### ISSUE THREAD

**Issue by Error00101** [vgrem/Office365-REST-Python-Client#412]
Hello,
Is there a way to receive emails via the library?
E.g.: Get the last 100 recieved emails. (email-header, email-body, attachments)

The given example is for sending only.
Thanks in advance!

**Comment by vgrem** [comment]
Greetings,

for collection data `100` items are getting returned by default (page size), use `top` method to adjust the page size, for example,  the following query returns the first `200` messages in the user's mailbox:

```python
my_messages = client.me.messages.top(200).get().execute_query() 
```

[`top` parameter documentation](https://docs.microsoft.com/en-us/graph/query-parameters#top-parameter)
