### ISSUE TITLE
Check if folder exists?

### ISSUE THREAD

**Issue by thomasweisend** [vgrem/Office365-REST-Python-Client#420]
How would you check to see if a folder exists?

**Comment by dswhite42** [comment]
Just for reference, commit 4b34f80 has corrected syntax for this, from:

`folder = ctx.web.get_folder_by_server_relative_url(folder_rel_url).select("Exists").get().execute_query()`

to:

`folder = ctx.web.get_folder_by_server_relative_url(folder_rel_url).select(["Exists"]).get().execute_query()`
