### ISSUE TITLE
Upload attachment to a sharepoint list

### ISSUE THREAD

**Issue by brunamulinari** [vgrem/Office365-REST-Python-Client#422]
Hello,

I would like to add an attachment to a sharepoint list, but I have not been successful. Can you help me? 

I am doing something like: 

```

attachment_file = AttachmentFile(ctx)
with open(path_file_name, 'wb') as fh:
    source_list.add_item({'Title': 'my_test', 'Attachments': attachment_file.upload(fh).execute_query()}).execute_query()
```

**Comment by matteoaurelio** [comment]
Can you add an attachment to an already **existing row in SharePoint list**? Without having to create a new one?

**Comment by mhar993** [comment]
> Can you add an attachment to an already **existing row in SharePoint list**? Without having to create a new one?

@matteoaurelio yep just change:
```
task_item = tasks_list.add_item({
    "Title": "New Task"
}).execute_query()
```
for:
```
task_item = tasks_list.get_item_by_id(row_id)
```
and enter the ID of the relevant row
