### ISSUE TITLE
Calendar Integration

### ISSUE THREAD

**Issue by codvlpr** [vgrem/Office365-REST-Python-Client#428]
I can't find the examples for the following features, Let me know if they're even supported or not.

- List Calendars
- List Events in Calendar
- Create new event in the specific calendar
- Remove already created event from the specific calendar.

Thanks!

**Comment by vgrem** [comment]
Greetings,

positive, all the listed operations are supported, here are a few examples:

### [`List calendars` endpoint](https://docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&tabs=http):


Get all the user's calendars: 

```python
client = GraphClient(acquire_token_func)
calendars = client.me.calendars.top(10).get().execute_query()
for cal in calendars:  # type: Calendar
    print(cal.name)

```


### List Events in Calendar

Get all the events in user default calendar:


```python
client = GraphClient(acquire_token_func)
events = client.me.calendar.events.get().top(10).execute_query()
for event in events:  # type: Event
    print(event.subject) 
```



### [`Create Event` endpoint](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http)


Create an event in the user's default calendar or specified calendar


```python
client = GraphClient(acquire_token_func)
new_event = client.me.calendar.events.add()  # type: Event
new_event.subject = "Let's go for lunch"
new_event.body = "Does mid month work for you?"
new_event.start = datetime.utcnow() + timedelta(days=1)
new_event.end = datetime.utcnow() + timedelta(days=1) + timedelta(hours=1)
new_event.attendees = ["samanthab@contoso.onmicrosoft.com"]
client.execute_query()
```


### Remove already created event from the specific calendar

```python
client = GraphClient(acquire_token_func)
event_id = "-- event id goes here--"
event_to_del = client.me.calendar.events[event_id]  # type: Event
event_to_del.delete_object().execute_query()
```
