### ISSUE TITLE
How to get Auther and TimeLastModified information for an old version file?

### ISSUE THREAD

**Issue by iwasaki-kdc** [vgrem/Office365-REST-Python-Client#429]
I try to get Auther and TimeLastModified information for an old version file.
I tried with the code below. (e.g. version 0.5)

ctx = ClientContext(test_team_site_url).with_credentials(credentials)
file_url = "/sites/team/Shared Documents/Guide.docx"
version = ctx.web.get_file_by_server_relative_path(file_url).versions.get_by_id(512).expand(["Author"])
ctx.load(version)
ctx.execute_query()

However, those information is missing in version.properties.
How can I get those information?

**Comment by kazukiaaaa** [comment]
excuse me. I am facing the same problem. Insufficient property information for older versions.

**Comment by vgrem** [comment]
Greetings,

it appears you are after  [`FileVerision.CreatedBy` property](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-csomspt/8a5d1a35-cf45-4f44-baef-6d45e807db87) which: 

> Specifies the user that represents the person who created the file version.


_([`FileVersion` type](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-csomspt/17d63dbf-ce29-45e5-ab9e-821955c19106) does not expose Author property)_


Providing the `expand` method is indeed mandatory here Author is a navigational property, here is an  an updated example:


```python
ctx = ClientContext(site_url).with_credentials(credentials)
version = ctx.web.get_file_by_server_relative_path(file_url).versions.get_by_id(1).expand(["CreatedBy"]).get().execute_query()
print(version.created_by.login_name)
```

**Comment by nmz787** [comment]
it looks like from @vgrem's reply here (https://github.com/vgrem/Office365-REST-Python-Client/issues/362#issuecomment-855388377) that what I want to do is:
```
file_metadata = source_file.expand(["versions", "listItemAllFields"]).get().execute_query()
most_recent_date_modified = file_metadata.time_last_modified
compound_version_string = f'{file_metadata.major_version}.{file_metadata.minor_version}'
```
but I'm still unclear as to how to get the Author name.


It would be great if @vgrem could update this example:
https://github.com/vgrem/Office365-REST-Python-Client/blob/5554194559faa1607719fdc51190520015c3f7a9/examples/sharepoint/files/get_file_version.py

as a new user (never used the Sharepoint REST API before attempting to with this library) when I see the title `get_file_version` I was expecting to get the version string for a file... not get a list of possible versions of a file's revisions. The latter is useful, but there's some naming overload here and I think it makes sense to cover both cases.
