### ISSUE TITLE
copy_to_by_path() does not Copy it moves

### ISSUE THREAD

**Issue by stefanstapinski** [vgrem/Office365-REST-Python-Client#431]
Hey I noticed that when I ran copy_to_by_path(), that it moved the entire directory vs making a copy.

    source_folder_url = "/sites/.../test1"
    target_folder_url = "/sites/..../target"

    source_folder = ctx.web.get_folder_by_server_relative_url(source_folder_url)
    target_folder = source_folder.copy_to_by_path(target_folder_url).get().execute_query()
    print(f"File copied into {target_folder.serverRelativeUrl}")

Not sure if this was fixed in a more recent version? I installed a couple months ago

**Comment by VdWWouter** [comment]
There is a default argument to copy_to_by_path method `keep_both=False` that seems to make the call analogous to a "move" operation.

This is, at the time of writing, in the master:
https://github.com/vgrem/Office365-REST-Python-Client/blob/820c029c695a2ce0ac080272a5af8f3ddd6009d4/office365/sharepoint/folders/folder.py#L131

**Comment by stefanstapinski** [comment]
wow thanks @VdWWouter ... I thought keep_both was only when it came to when the same file name exists.

**Comment by VdWWouter** [comment]
I see. That can be confusing indeed. You have to really experiment and dive into the source code.

According to what I've tested, the default behavior (when the same file exists) is to place the copied file next to it with a number appended. Just like windows would do it in it's filesystem.
