### ISSUE TITLE
ModuleNotFoundError: No module named 'office365.runtime.auth.ClientCredential'

### ISSUE THREAD

**Issue by rajaranjith** [vgrem/Office365-REST-Python-Client#434]
After installing the latest version of Office365_REST_Python_Client-2.3.9 via pip install Office365-REST-Python-Client command, getting ERROR on executing the code "from office365.runtime.auth.ClientCredential import ClientCredential".

ModuleNotFoundError: No module named 'office365.runtime.auth.ClientCredential'

after that installed the office365-rest-client-2.2.0 package, but still same ERROR.

**Comment by vgrem** [comment]
Hey,

have you tried another options, for instance, install package in [virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/)?

**Comment by vgrem** [comment]
Closing this one due to inactivity

**Comment by rajaranjith** [comment]
Yes, it was installed in virtual environment and running it from there...
-Ranjith G

**Comment by rajaranjith** [comment]
Sorry it was my bad, i did not see your message 14 days ago....
