### ISSUE TITLE
How to create an item with a lookup field in sharepoint list?

### ISSUE THREAD

**Issue by txz233** [vgrem/Office365-REST-Python-Client#435]
Hi. I used add_item function to create new item in my list, but I don't have the method to put a lookup value in it. I have the ID of the item looked up to, is there any function in this repo can help me with it?

**Comment by txz233** [comment]
FieldLookupValue(lookupid) shall do. solved

**Comment by andresgd7** [comment]
Im having problems with this. When i use `FieldLookupValue(lookupid)` python throws:
`
NameError: name 'FieldLookupValue' is not defined`
