### ISSUE TITLE
How to move email messages to another folder

### ISSUE THREAD

**Issue by minsis** [vgrem/Office365-REST-Python-Client#438]
I seem to be missing something here but I dont see how to move a message from one folder to another.

https://github.com/vgrem/Office365-REST-Python-Client/blob/820c029c695a2ce0ac080272a5af8f3ddd6009d4/office365/outlook/mail/messages/message.py#L129-L136

`Move a message to another folder within the specified user's mailbox`

Where do you specify the folder you want to move it to?

**Comment by vgrem** [comment]
Greetings,

thank you for catching this inconsistency with API,  starting from [`2.3.10` version](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.10)  `Message.move` method  expects `destination_id` argument:

> The destination folder ID, or a well-known folder name

  


Example: [`move_message.py`](../tree/master/examples/outlook/move_message.py)
