### ISSUE TITLE
Bulk Call? Fastest Way to Return File Properties when files are in different directories

### ISSUE THREAD

**Issue by stefanstapinski** [vgrem/Office365-REST-Python-Client#441]
Is there a more efficient/faster way to return the file properties, my current function returns the last-modified time for 4k files in 9-15 minutes (9Min when calling from NYC, 15min when calling from California). I also don't want to return the entire parent directory because there are other files in the same directories that I don't care for. Is there a way to do a bulk call?

the files are spread into multiple different directories I want FileA.xlsx and FileB.xlsx
Ex.:
level1/level2/levelA/FileA.xlsx
level1/level2/levelA/somefile.xlsx ## IGNORE

level1/level2/levelB/FileB.xlsx

FUNCTION BELOW RETURNS LAST MODIFIED TIME & FILE SIZE

def fileprops(ctx, file_url_list):
""" file_url_list = ['/sites/.../test.xlsx'] """ # Run Adhoc Test
filename_lastmodified = {}
filename_size = {}

for file_url in file_url_list:
file = ctx.web.get_file_by_server_relative_path(file_url).get().execute_query()
datetime_object = datetime.datetime.strptime(file.time_last_modified, "%Y-%m-%dT%H:%M:%SZ")
filename_lastmodified[file_url] = "jq_" + str(datetime_object)  ### making my own Mark to TIMESTSAMP
filename_size[file_url] = file.length

return [filename_lastmodified, filename_size]

**Comment by VdWWouter** [comment]
Do you have an idea of what the file to folder ratio is? If it's big enough, you may observe an improvement fetching all properties for the file collection?

Sample code:
``` python
folder = self.ctx.web.get_folder_by_server_relative_url(relative_url)
directory = folder.folders
self.ctx.load(directory)
self.ctx.execute_query()

print('folder properties:')
print(str(directory.properties))

print('sub folder properties:')
for d in directory._data:
    print('SUB FOLDER: {d.properties["Name"]}')
    print(str(d.properties))

sub_folders = folder.files
self.ctx.load(sub_folders)
self.ctx.execute_query()

print('file properties:')
for s_folder in sub_folders:
    print('FILE: {s_folder.properties["Name"]}')
    print(str(s_folder.properties))
```

**Comment by stefanstapinski** [comment]
When I try to fetch the Top directory I exceed the 5k limit call as there are too many folders

My Top level directory has 10k folders and in each folder, there are multiple folders & files, (30+ files). In each folder there is 1 specific file I want to fetch, so 10k unique files amongst a small but growing sea of files.

**Comment by nafets33** [comment]
Hey I came across batch calls doc, is there a way to utilize this in the package?

https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis#executive-summary-of-the-batch-option

**Comment by nafets33** [comment]
@vgrem do you know how to do this? I see that ctx has execute_batch(), but I don't know how to generate a batch of relative_urls file objects. Would you happen to know how to use it?

I have a list of urls [ '/sites/Mysite/DirA/987.xlsm',  '/sites/Mysite/DirB/123.xlsm'] and I want to do a batch call and return the file objects (the last modified time)

I'm currently looping through each url in the list and calling ctx.web.get_file_by_server_relative_path(file_url).get().execute_query()
?

**Comment by vgrem** [comment]
Greetings,

@nafets33, regarding:

> I see that ctx has execute_batch()
precisely, this method implements batch request.   

> but I don't know how to generate a batch of relative_urls file objects. Would you happen to know how to use it?

Here is an example which demonstrates how to retrieve file's metadata via a batch request:

```python
file_urls = ["/sites/consoto/Shared%20Documents/Archive/01/Report.xlsx",
             "/sites/contoso/Shared%20Documents/Archive/02/Report.xlsx"]

ctx = ClientContext(test_site_url).with_credentials(client_credentials)
files = [ctx.web.get_file_by_server_relative_url(file_url).get() for file_url in file_urls]
ctx.execute_batch()
for file in files:  # type: File
    print(file.time_last_modified)
```

**Comment by vgrem** [comment]
Hi @stefanstapinski,

regarding 

> Fastest Way to Return File Properties when files are in different directories 

the following option could be considered:


```python
ctx = ClientContext(site_url).with_credentials(client_credentials)
lib = ctx.web.lists.get_by_title("Documents")
items = lib.items.filter("FSObjType eq 0").expand(["File"]).get().execute_query()

# enum & print file url
for item in items:  # type: ListItem
    print(item.file.properties.get('ServerRelativeUrl'))
```

where

- a single request is submitted to retrieve all the items within a library via `/web/lists/getbytitle({title})/items` endpoint 
- the expression `$expand=File` instructs the query to return associated files metadata
- to return only files, the filter expression `FSObjType eq 0` is utilized

**Comment by nafets33** [comment]
@vgrem you F-in Rock EXACTLY what I needed!

files = [ctx.web.get_file_by_server_relative_url(file_url).get() for file_url in file_urls]
ctx.execute_batch()
