### ISSUE TITLE
Is there support to use the delta on files?

### ISSUE THREAD

**Issue by RobinVds** [vgrem/Office365-REST-Python-Client#448]
I'm looking at: https://docs.microsoft.com/en-us/graph/delta-query-overview

I was not able to determine if this kind of functionality is included in this repo?

**Comment by vgrem** [comment]
Greetings,

in [`2.3.10` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.10) the support for delta queries has been improved in terms of extending the list of [supported resources](https://docs.microsoft.com/en-us/graph/delta-query-overview#supported-resources).

Example: get incremental changes for users

```python
client = GraphClient(acquire_token_func)
changed_users = self.client.users.delta.get().execute_query()
```
