### ISSUE TITLE
Is it possible to delete a folder?

### ISSUE THREAD

**Issue by gregory-dan** [vgrem/Office365-REST-Python-Client#451]
Hi
I do not see an option to delete a folder and all it's content, although it seems to be supported by REST API:

POST https://{site_url}/_api/web/GetFolderByServerRelativeUrl('/Folder Name')
Authorization: "Bearer " + accessToken
If-Match: "{etag or *}"
X-HTTP-Method: "DELETE"
X-RequestDigest: "{form_digest_value}"

is it possible?

**Comment by vgrem** [comment]
Greetings,  

all basic operations (CRUD) operations against `Folder` resource are supported, here is an example on how to delete a folder:

```python
client = ClientContext(site_url).with_credentials(credentials)
client.web.get_folder_by_server_relative_path(folder_path).delete_object().execute_query()
```
