### ISSUE TITLE
Retrieve SharePoint List Created-By (Author), and Modified-By (Editor) fields

### ISSUE THREAD

**Issue by mickmill54** [vgrem/Office365-REST-Python-Client#455]
Hi,

I am having trouble retrieving both the Author and Editor field from a SharePoint list.  I am getting this error 

```
python o365_get_list.py
Traceback (most recent call last):
  File "/Users/mick/dev/export_sp_list/o365_get_list.py", line 183, in <module>
    enum_items(l_items, "print_out")
  File "/Users/mick/dev/export_sp_list/o365_get_list.py", line 103, in enum_items
    item.properties["Editor"]
KeyError: 'Editor'
```

Easier to look at the code, but here is the line that fails.
```
item.properties["Editor"]
```

I am sure I am missing something.  

My repo is here:
https://github.com/mickmill54/export_sp_list
[o365_get_list.py.zip](https://github.com/vgrem/Office365-REST-Python-Client/files/7854330/o365_get_list.py.zip)

**Comment by vgrem** [comment]
Greetings, 

some properties are not getting return _by default_ (by SharePoint REST API design), for instance `User` field type (such as `Author`). To  request those field values they need to be specified explicitly via both the `$select` and `$expand` query options, for example:


```python
ctx = ClientContext(team_site_url).with_credentials(client_credentials)
tasks_list = ctx.web.lists.get_by_title("Tasks")
items = tasks_list.items.get().select(["*", "Author/Id", "Author/Title", "Editor/Title"]).expand(["Author", "Editor"]).execute_query()
for item in items:
    print("{0}".format(item.properties.get('Author').get("Title"))) 
```

Refer [Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests) for a more details

**Comment by mickmill54** [comment]
Thanks so much.  This will for sure unblock me.  One last question.  Is there an API reference that describes these files type and their structure so that I can resolve myself.?

Thanks 1) For created this lib. and 2) for you awesome support.
