### ISSUE TITLE
Calculated column

### ISSUE THREAD

**Issue by brunamulinari** [vgrem/Office365-REST-Python-Client#471]
Is it possible to create a "calculated column" with a formula that uses other columns from a sharepoint list?

**Comment by vgrem** [comment]
Greetings,

would like to confirm it is supported, here is a generic example on how to create a _calculated site field_ with setting formula:


```python 
client = ClientContext(site_url).with_credentials(credentials)

field_name = "AuthorInfo"
create_field_info = FieldCreationInformation(field_name, FieldType.Calculated)
create_field_info.set_property("Formula", '=CONCATENATE(Author,":",Created)')
created_field = client.site.root_web.fields.add(create_field_info).execute_query()  
```


**References**
  
- example: [create_field.py](../blob/master/examples/sharepoint/fields/create_field.py)

- [Examples of common formulas in lists](https://support.microsoft.com/en-us/office/examples-of-common-formulas-in-lists-d81f5f21-2b4e-45ce-b170-bf7ebf6988b3)
