### ISSUE TITLE
Return SharePoint List field names

### ISSUE THREAD

**Issue by mickmill54** [vgrem/Office365-REST-Python-Client#474]
Hi,

I am trying to create a general purpose SharePoint list exporter.  To do that I need the fieldName and then DisplayName to create a dict so that I can get all the items of a view.  This code works.

I can't see to figure out how to get the DisplayName for all the fields.  I have the fieldName, no problem.  

Thanks,

Mick Miller

Trying to build this structure:
-------------------------------------
EXAMPLE_COLUMNS = [
        ("ID",                                     "ID"),
        ("Title",                                 "Internal Name"),
        ("Description",                    "Identifying Description"),
        ("Picture",                            "Image fileName"),
        ("Filed_x002c_01",             "Field 01"),
        ("Field_x002x_02",             "Field 02"),
        ]

Config
---------------------------------
{
    "share_point": 
        {
            "user": "user@domain.com",
            "password": "o365-password",
            "url": "https://tenent.sharepoint.com",
            "site": "https://tenent.sharepoint.com/sites/your_site/",
            "list_name": "Your SP List"
            "list_view": "Your SP view",
            "image_path" : "./images",
            "attachment_path" : "./attachments",
            "filename" : "filename.xlsx"
        }
}

Code
-------------------------------------------------------

from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.client_context import ClientContext
import json
import os

# read config.json
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
config_path = '/'.join([ROOT_DIR, 'config.json'])

# read json config file and load variables
with open(config_path) as config_file:
    config = json.load(config_file)
    config = config['share_point']

# get the variables
USERNAME = config['user']
PASSWORD = config['password']
SHAREPOINT_URL = config['url']
SHAREPOINT_SITE = config['site']
SHAREPOINT_LIST=config['list_name']
SHAREPOINT_VIEW=config['list_view']

# get an authenticated connection to the SharePoint site
ctx = ClientContext(SHAREPOINT_SITE).with_credentials(UserCredential(USERNAME, PASSWORD))

# Get all the fields from the view
list_object = ctx.web.lists.get_by_title(SHAREPOINT_LIST)
view_fields = list_object.views.get_by_title(SHAREPOINT_VIEW).view_fields
ctx.load(view_fields)
ctx.execute_query()

# Print the fields
for item in view_fields:
        print(f"Field: {item}")

**Comment by guicorsi** [comment]
Hi i've dealed with the same situation. I used the Fields endpoint to get the displayname and the internal name. After that i iterated over the list items renaming the fields. here is a snippet i hope it helps you: 

        def get_list_items(self, list_name):
          sharepoint_list = self.ctx.web.lists.get_by_title(list_name)
          items = sharepoint_list.items.paged(True)
  
          self.ctx.load(items)
          self.ctx.execute_query()
          
          fields = sharepoint_list.fields.get().execute_query()
          fields_list = [field.properties for field in fields if not field.hidden]
          renamed_cols = {field['InternalName']: field['Title'] for field in fields_list}
          
          for item_obj in items:
              item = item_obj.properties
              old_keys = item.keys()
              keys_to_rename = renamed_cols.keys()
              common_keys = [key for key in old_keys if key in keys_to_rename]
              for key in common_keys:
                  new_name = renamed_cols[key]
                  item[new_name] = item.pop(key)
          return items`

**Comment by vgrem** [comment]
Greetings,
that's a good question indeed, thank you!

And in addition to solution @guicorsi kindly provided, here is another one which might be more beneficial in terms of performance:

- first view fields are getting requested as provided in section Get all the fields from the view 
- and finally fields are getting requested via `List.get_by_internal_name_or_title` method, but from a performance perspective i would prefer `execute_batch` over `execute_query` in this regard   


Complete example

```python 
list_title = "Site Pages"
view_title = "By Author"

ctx = ClientContext(test_team_site_url).with_credentials(test_client_credentials)
list_object = ctx.web.lists.get_by_title(list_title)

view_fields = list_object.views.get_by_title(view_title).view_fields.get().execute_query()

fields = [list_object.fields.get_by_internal_name_or_title(field_name).get() for field_name in view_fields]
ctx.execute_batch()    

fields_json = {f.internal_name: f.title for f in fields}
print(json.dumps(fields_json))
```

**Comment by guicorsi** [comment]
Hi @vgrem, 

 I realized that my def will have some performance problems, especially with big lists, but, I didn't know how to improve it. So thank you for your reply.
 
  I'm trying to automate some data pipelines that use SharePoint lists but I'm struggling with the way that Sharepoint's API is designed. Do you have some docs site or even a book to recommend?

**Comment by karunpoudel** [comment]
Hi @vgrem , @guicorsi ,
While using the view "All Items", it returns a field with `internal_name: LinkTitle`. But, while getting list of all items using `list_object.items.get().execute_query()`, it has property called 'Title'; it doesn't have properties called 'LinkTitle'. So I had to hard code to map LinkTitle to Title. Is there any other better way.

I couldn't get items from the "All Items" view using `list_object.views.get_by_title('All Items').get_items().execute_query()`; it returned nothing. ( I can get items using list.items.get() but not using view.get_items())

Do you have a better approach?

**Comment by karunpoudel** [comment]
End up doing this:
```
field_mappings = {f.internal_name: f.title for f in fields}
title = field_mappings.get('LinkTitle') or field_mappings.get('Title') or field_mappings.get('LinkTitleNoMenu')
if 'Title' not in field_mappings:
    field_mappings['Title'] = title or 'Title'
field_mappings.pop('LinkTitle', None)
field_mappings.pop('LinkTitleNoMenu', None)
```
