### ISSUE TITLE
SiteProperties update via Admin context

### ISSUE THREAD

**Issue by afdezl** [vgrem/Office365-REST-Python-Client#480]
Hello,

I'm looking for help trying to update site properties via the admin client:

```python
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.tenant.administration.tenant import Tenant

ctx = ClientContext("https://mytenant-admin.sharepoint.com").with_client_certificate("mytenant.onmicrosoft.com", **cert_settings)
tenant = Tenant(ctx)

site_props = tenant.get_site_properties_by_url("https://mytenant.sharepoint.com/sites/mysite", True).execute_query()
```
Site properties are loaded fine and auth with the service principal certificate works.

But when attempting an update to the `SiteProperties` object as follows:
```python
site_props.set_property('ConditionalAccessPolicy', 1)
site_props.update().execute_query()
```
results in a:

```python
ClientRequestException: (None, None, '401 Client Error: Unauthorized for url: https://mytenant-admin.sharepoint.com/_apiNone')
```

I have also attempted context switching to the site, resulting in the same error.
It seems as if the resource path for that specific SiteProperties resource is not set, how can I achieve this?

For reference, a working version in C# would look something like this:

```csharp
// From https://social.technet.microsoft.com/Forums/en-US/38fb7a3b-57da-4654-8622-400413c1a90d/method-getsitepropertiesbyurl-cant-return-the-modify-value
using Microsoft.Online.SharePoint.TenantAdministration;
using Microsoft.SharePoint.Client;

Tenant tenant = new Tenant(ctx);
var site = tenant.GetSitePropertiesByUrl("https://mytenant.sharepoint.com/sites/mysite, true);
tenant.Context.Load(site);
tenant.Context.ExecuteQueryAsync().Wait();
site.UserCodeMaximumLevel = 380.0;
site.UserCodeWarningLevel = 30.0;
site.Update();
tenant.Context.ExecuteQueryAsync().Wait();
```

Am I making an obvious mistake?

Thanks.

**Comment by vgrem** [comment]
Greetings,

thank you for the analysis and catching this error, i confirm it was the bug with the `SiteProperties.update` method. But not any longer, in a new version ( [`2.3.11` release](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.11)) the update operation should work as expected, here is an example which demonstrates how to set external sharing (adapted from [Set external sharing](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365)):



```python
tenant = Tenant(ctx)
site_props = tenant.get_site_properties_by_url("https://mytenant.sharepoint.com/sites/mysite", True).execute_query()
site_props_to_update.set_property('SharingCapability', SharingCapabilities.ExternalUserAndGuestSharing)
site_props_to_update.update().execute_query()
```

**Comment by afdezl** [comment]
Hi @vgrem, much appreciated. :+1:
