### ISSUE TITLE
Question regarding downloading Sharepoint file using an app

### ISSUE THREAD

**Issue by kodw93** [vgrem/Office365-REST-Python-Client#483]
Hello,

First of all, I love this library. It helps me tremendously with my daily tasks and I just wanted to thank you for providing this. 
I had a question about downloading the files from Sharepoint using an application. 

I keep running to the **403 Forbidden Response** when using this Python code:

```
client_id = "_____________" 
client_secret= "_________________"

url = 'https://mycompanyname-my.sharepoint.com/personal/________'
relative_url = '/_____________/EXCELFILE.xlsx'

client_credentials = ClientCredential(client_id, client_secret)
ctx = ClientContext(f'{url}').with_credentials(client_credentials)

response = File.open_binary(ctx, relative_url)

#save data to BytesIO stream
bytes_file_obj = io.BytesIO()
bytes_file_obj.write(response.content)
bytes_file_obj.seek(0) #set file object to start

#read file into pandas dataframe
df = pd.read_excel(bytes_file_obj)
df
```

I feel like this is a permission issue as it works fine with my company email and password (code below)
```

user_email = 'user@companyemail.com'
user_password = 'userpassword'

ctx = ClientContext(url).with_credentials(UserCredential(user_email, user_password))
response = File.open_binary(ctx, relative_url)

#save data to BytesIO stream
bytes_file_obj = io.BytesIO()
bytes_file_obj.write(response.content)
bytes_file_obj.seek(0) #set file object to start

#read file into pandas dataframe
df = pd.read_excel(bytes_file_obj)

```
I currently have the following permissions for the app:
Microsoft Graph 

- Files.Read.All
- Sites.Read.All
- User.Read

SharePoint 

- Sites.Full.Control.All

Could you tell me what permissions I am missing or if there is something wrong with my code for downloading files through the application? Thank you so much!

**Comment by kodw93** [comment]
@vgrem Hi Vadim! Just wondering if I will be able to get an answer to this question. I would love to hear what you think! Thank you so much!

**Comment by vgrem** [comment]
Greetings @kodw93,

regarding: 

> Could you tell me what permissions I am missing 

i believe everything is fine with the granted permissions, the reason why the error  `403 Forbidden ` occurs is related with SharePoint Online restrictions for Azure AD App Only access token. For this so called [low-trust authorization system](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization) scenario a token issued via Azure AD client credentials flow is **not** supported (blocked) by SharePoint Online and certificate App Only trust needs to be utilized instead (option 1 from below list)         



Here is the list of options and workarounds to consider:


### Option 1: utilize client certificate flow 

Refer [wiki](https://github.com/vgrem/Office365-REST-Python-Client/wiki/How-to-connect-to-SharePoint-Online-with-certificate-credentials) on how to connect to SharePoint Online with certificate credentials, here is an example:

```python

cert_settings = {
    'client_id': -- client id goes here--',
    'thumbprint': "-- thumbprint goes here--",
    'cert_path': '--path to self signed cert file--' ,
    'scopes': ['{0}.default'.format(test_site_url)]
}

ctx = ClientContext(test_site_url).with_client_certificate(test_tenant, **cert_settings)
current_web = ctx.web.get().execute_query()
```

**References**:

- [How to connect to SharePoint Online with certificate credentials](https://github.com/vgrem/Office365-REST-Python-Client/wiki/How-to-connect-to-SharePoint-Online-with-certificate-credentials)
- [Granting access via Azure AD App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread)


### Option 2: granting access using SharePoint App-Only

the trick is to grant AD app access via Azure Access Control (ACS) which is still supported:

navigate to page: `https://{tenant}-my.sharepoint.com/personal/{username}_{tenant}_onmicrosoft_com/_layouts/15/appinv.aspx` and and grant permissions for _already_ registered app in Azure AD and provide permission settings where **App Id** corresponds to Azure AD application identifier 

Here is an example for permission request (site collection scope): 

```xml
<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
</AppPermissionRequests>
```

Once granted, client credentials flow should work as expected:  

`ctx = ClientContext(site_url).with_credentials(client_credentials)`


**Note**: per the official  documentation:

> For new tenants, apps using an ACS app-only access token is disabled by default. We recommend using the Azure AD app-only model which is modern and more secure. But you can change the behavior by running ‘set-spotenant -DisableCustomAppAuthentication $false' (needs the latest SharePoint admin PowerShell).


**References**:

- [Granting access using SharePoint App-Only](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs)

**Comment by ohofherr** [comment]
Hi @vgrem, thank you for this explanation. I tried approach 2 because I have the same problem as @homieHolmes (https://github.com/vgrem/Office365-REST-Python-Client/issues/678). Where can I find the App IDs in Office365?

**Comment by vgrem** [comment]
Greetings @ohofherr, 

one option would be to find app id by visiting page: `https://contoso.sharepoint.com/{site-path}/_layouts/15/appprincipals.aspx    `

where `AppIdentifier` column contains value in the following format: i:0i.t|ms.sp.ext|{app-id}@{tenant-id}

 and App ID corresponds to  `{app-id}` value
