### ISSUE TITLE
Upload File To Sharepoint Sub Folder

### ISSUE THREAD

**Issue by dbirdflyshi** [vgrem/Office365-REST-Python-Client#485]
There's an issue identical to what I am trying to do yet it was marked as 'wontfix' with no context as to why. https://github.com/vgrem/Office365-REST-Python-Client/issues/450

I don't understand why uploading to a subfolder is not a worthy functionality to implement as it defeats the purpose of uploading files to sharepoint if you can't dig deeper than the root. 

If the functionality does indeed exist, I look forward to a solution.

**Comment by dbirdflyshi** [comment]
I figured it out. I was looking at the big file upload code example and noticed that it was different than the regular upload file so I deconstructed the code and mixed both solutions to come up with this : 

```
ctx = ClientContext(sharepoint_base_url, auth)

buffer = io.BytesIO()               # Create a buffer object
df.to_excel(buffer, index=False) # Write the dataframe to the buffer
buffer.seek(0)
file_content = buffer.read()

target_url = "/sites/site_name/Shared Documents/sub_folder_name"
target_folder = ctx.web.get_folder_by_server_relative_url(target_url)

target_file = target_folder.upload_file('file_name.xlsx', file_content).execute_query()
```

**Comment by cilles** [comment]
I was also having trouble with uploading to a subfolder, so figured I would throw my example here as well for anybody that might need the extra help.

NOTE: Depending on the how the sharepoint site is set up, you may not have the correct authentication access to authenticate based off the site_base_url (as done with the comment above). Therefore, mine is slightly different in that it authenticates off the full site URL, and grabs the relative URL from there.

```
from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.client_context import ClientContext

# using Office365-REST-Python-Client
# https://github.com/vgrem/Office365-REST-Python-Client

user_credentials = UserCredential('user@email.com', 'PASSWORD')
sharepoint_url = 'https://DOMAIN.sharepoint.com/sites/SITENAME/'
target_url = "/sites/SITENAME/Shared Documents/SubFolderName"
file_to_upload = 'test.zip'


ctx = ClientContext(sharepoint_url).with_credentials(user_credentials)

target_folder = ctx.web.get_folder_by_server_relative_url(target_url)

with open(file_to_upload, 'rb') as content_file:
	file_content = content_file.read()

target_file = target_folder.upload_file(file_to_upload, file_content).execute_query()
print("File has been uploaded to url: {0}".format(target_file.serverRelativeUrl))
```
