### ISSUE TITLE
Ordering Results in Sharepoint Search 

### ISSUE THREAD

**Issue by domdinicola** [vgrem/Office365-REST-Python-Client#496]
Hi @vgrem ,

Was wondering if the ordering is implemented in the Search Functionality..
I saw https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#sortlist , not sure if it's implemented

**Comment by domdinicola** [comment]
@vgrem this is not been implemented yet, correct?

**Comment by vgrem** [comment]
Greetings @domdinicola  and good to hear from you :)

For the [`GET request`](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#sample-get-request-13)

it could be represented like this:

```python 
ctx = ClientContext(site_url).with_credentials(credentials)
search = SearchService(ctx)
request = SearchRequest("sharepoint", sortlist="rank:descending,modifiedby:ascending")
result = search.query(request).execute_query()
```


For [`POST request`](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview#sample-post-request-13)

```python
request = SearchRequest(query_text="sharepoint",
                        SortList={'results': [
                            {
                                'Direction': 1,
                                'Property': 'ModifiedBy',
                            },
                            {
                                'Property': 'Created',
                                'Direction': '0'
                            },
                        ]})
result = search.post_query(request).execute_query()
```

In terms of API design and usability apparently not the most intuitive and will be improved in future releases.

**Comment by domdinicola** [comment]
Greetings to you @vgrem ! Always good to hear from you :)

This doesn't seem to work for me... I also tried with different Property/Fields and changing the Direction...
Did you try it?

**Comment by vgrem** [comment]
Hi @domdinicola,  

hmm, seems to be working as expected on my side.
 
Anyway in a new version (`2.3.12`) a few enhancements have been introduced for `Search` namespace, among them:

- an alternative way of passing (KQL) query expression to `query` and `post_query` methods of `SearchService` class (no need of instantiating `SearchRequest` type if only query text needs to be passed):
```python
search = SearchService(ctx)
result = search.query("IsDocument:1").execute_query()
```

- simplifying the passing of complex types (namely `SelectProperties`, `SortList` properties) when constructing a search request:
```python
search = SearchService(ctx)
request = SearchRequest(query_text="IsDocument:1",
                        sort_list=[Sort("LastModifiedTime", 1)],
                        select_properties=["Path", "LastModifiedTime"],
                        row_limit=20)
```    



### Sorting search results example


```python 
request = SearchRequest(query_text="IsDocument:1",
                        sort_list=[Sort("LastModifiedTime", 1)],
                        select_properties=["Path", "LastModifiedTime"],
                        row_limit=20)
result = search.post_query(request).execute_query()
relevant_results = result.value.PrimaryQueryResult.RelevantResults
for r in relevant_results.get('Table').get('Rows').items():
    cells = r[1].get('Cells')
    print(cells[1].get('Value'))
```


**Result** 

![Screenshot from 2022-05-29 14-46-23](https://user-images.githubusercontent.com/1596072/170866373-8a3be865-8b45-44d4-8502-2a279bd93658.png)

**Comment by domdinicola** [comment]
hi @vgrem !

Thanks for your help here! Much appreciated :)
Looks like the new SearchRequest doesn't have the possibility to set the source_id, can we (re)introduce it?

Dom

**Comment by domdinicola** [comment]
Thanks @vgrem ,
I confirm you it's backward compatible and that select_properties changed from dict to list.

Best,
Dom
