### ISSUE TITLE
Office365-REST-Python-Client | Sharepoint | Download files | 404 File does not exists 

### ISSUE THREAD

**Issue by prabchou** [vgrem/Office365-REST-Python-Client#499]
Hi,

I have properly created an App, generated client credentials, and trusted the app for my SharePoint online site. 

I have created a file test.txt and it is placed under -https://company.sharepoint.com/sites/VILASCA/Shared%20Documents/General/test.txt

Installed the latest version of the module
```
pip freeze | grep Office
Office365-REST-Python-Client==2.3.11

```

```
class SharePoint:

    def __init__(self):
        context_auth = AuthenticationContext(Configs.SITE_URL) --->   SITE_URL='https://company.sharepoint.com/sites/VILASCA/'
        context_auth.acquire_token_for_app(client_id=Configs.OAUTH_CLIENT_ID, client_secret=Configs.OAUTH_CLIENT_SECRET)
        self.ctx = ClientContext(Configs.SITE_URL, context_auth)

    def download_files(self):
        file_url = "/sites/VILASCA/Shared%20Documents/General/test.txt"
        download_path = os.path.join(tempfile.mkdtemp(), os.path.basename(file_url))
        print(download_path)
        with open(download_path, "wb") as local_file:
            file = self.ctx.web.get_file_by_server_relative_url(file_url).download(local_file).execute_query()
        print("[Ok] file has been downloaded into: {0}".format(download_path))

if __name__ == '__main__':
    s = SharePoint()
    s.download_files()

```

However, it throws an error, not able to get my head around this.
```
office365.runtime.client_request_exception.ClientRequestException: ('-2130575338, Microsoft.SharePoint.SPException', 'The file /sites/VILASCA/Shared%20Documents/General/test.txt does not exist.', "404 Client Error: Not Found for url: https://company.sharepoint.com/sites/VILASCA/_api/Web/getFileByServerRelativeUrl('%2Fsites%2FVILASCA%2FShared%2520Documents%2FGeneral%2Ftest.txt')?$select=ServerRelativePath")

```

**Comment by vgrem** [comment]
Greetings,

your example looks good, although one question regarding: 

> trusted the app for my SharePoint online site

are you certain it has been trusted(granted) against a _proper_ site collection, per [step 6](https://github.com/vgrem/Office365-REST-Python-Client/wiki/How-to-connect-to-SharePoint-Online-and-and-SharePoint-2013-2016-2019-on-premises--with-app-principal), in your case page url should be:  

`https://company.sharepoint.com/sites/VILASCA/_layouts/15/appinv.aspx`

**Comment by prabchou** [comment]
Thanks for the reply. Hi, yes, it has been trusted against a proper site collection. Actually, I tried to replace the site name with some arbitrary value while posting this question but I think i missed at one place.

**Comment by prabchou** [comment]
I did it using https://company.sharepoint.com/sites/VILASCA/_layouts/15/Appinv.aspx not appinv.aspx. Do you think, this could be a problem.

**Comment by prabchou** [comment]
![image](https://user-images.githubusercontent.com/42576926/162614711-38f64c39-df30-4a0a-a160-87136e24207e.png)

This is the permission I have setup.

**Comment by prabchou** [comment]
Found the issue. I have put improper scope. Thank you.

**Comment by vgrem** [comment]
Good catch and good to know! 👍 

In case if someone else will stumble upon this issue, the list of supported scopes could be found [here](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint) ( Table 1. SharePoint add-in permission request scope URIs and descriptions)
