### ISSUE TITLE
Listing files in a folder doesn't work as expected

### ISSUE THREAD

**Issue by leoalekseyev** [vgrem/Office365-REST-Python-Client#5]
I am working with a slightly modified version of `file_operations.py` example, as the Sharepoint instance I'm working with doesn't have any lists.  Thus, I am trying to obtain files like so:
```
    folder = ctx.web.get_folder_by_server_relative_url('/')
    ctx.load(folder)
    ctx.execute_query()
    files = folder.files
    ctx.load(files)
    ctx.execute_query()
```
This yields ValueError: ('Response error:', {u'lang': u'en-US', u'value': u'Cannot find resource for the request Files.'})

Looking at the code, it seems that when the folders are fetched, the class constructor does not include the current resource path, and therefore when invoking `folder.files`, no valid URL is constructed.  Indeed, the request becomes "GET //_api/Files" as opposed to the expected "GET http://myhost/_api/Web/GetFolderByServerRelativeUrl('%2f')/Files".  Looks like a bug to me.

(Grepping for "__deferred" it doesn't seem that the resource URIs in __deferred objects are being parsed or used anywhere, so I imagine the URIs must be constructed from ResoucePath objects.)

**Comment by vgrem** [comment]
Greetings Leo,

indeed it was a bug related with initialization of so called navigation properties and the it's been resolved.

Thank you for reporting it, hopefully it works now as expected,
Vadim
