### ISSUE TITLE
How to get username of latest file modifier from File object?

### ISSUE THREAD

**Issue by ChaddRobertson** [vgrem/Office365-REST-Python-Client#501]
I have listed all files within a SharePoint document library. For each of these files, I would like to create a dictionary of the following form:

`file_dict = {File.serverRelativeUrl: [file_attribute_1, file_attribute_2, ...]}`

Where one of the above-mentioned attributes is the name of the latest user to modify the file (as seen under the "Modified By" column header on SharePoint). I am attempting to use the `File.modified_by()` method, but am unable to get the username from the User return type (and am unsure if this is the correct way to go about this).

How would one determine the name of the associated modifier of a file?

**Comment by vgrem** [comment]
Greetings,

>  I am attempting to use the File.modified_by()

that's right, it corresponds to [`ModifiedBy` system property](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-csomspt/27d38ff5-8ed4-4a73-b0b4-09c60688f617) which:

> Specifies the user who last modified the file. 

Most likely the reason why: 

> but am unable to get the username from the User return type

due the fact that  `ModifiedBy` property never gets retrieved in your example.  

The way how [SharePoint REST API is designed](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests) _lookup field values_ are not getting retrieved _by default_, they needs to be retrieved explicitly, for that matter `expand` method could be utilized:     

`file = ctx.web.get_file_by_server_relative_url(file_url).expand(["ModifiedBy"]).get()`


**Example**:


```python
file_urls = ["/sites/contoso/Shared%20Documents/Archive/Report1.pdf",
             "/sites/contoso/Shared%20Documents/Archive/Report2.pdf"]

ctx = ClientContext(test_site_url).with_credentials(client_credentials)
files = [ctx.web.get_file_by_server_relative_url(file_url).expand(["ModifiedBy"]).get() for file_url in file_urls]
ctx.execute_batch()
for file in files:  # type: File
    print(file.modified_by.properties.get('LoginName'))  
```
