### ISSUE TITLE
Unable to download file office365.runtime.client_request_exception.ClientRequestException:404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by amalik2005** [vgrem/Office365-REST-Python-Client#515]
python dn_sp.py
Traceback (most recent call last):
  File "dn_sp.py", line 16, in <module>
    file = ctx.web.get_file_by_server_relative_path(file_url).download(local_file).execute_query()
  File "/home/srv_sddc/miniconda2/lib/python2.7/site-packages/office365/runtime/client_object.py", line 41, in execute_query
    self.context.execute_query()
  File "/home/srv_sddc/miniconda2/lib/python2.7/site-packages/office365/runtime/client_runtime_context.py", line 134, in execute_query
    self.pending_request().execute_query()
  File "/home/srv_sddc/miniconda2/lib/python2.7/site-packages/office365/runtime/client_request.py", line 84, in execute_query
    raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: (u'-2130575338, Microsoft.SharePoint.SPException', u'The file /sites/Test504/Shared Documents/General/architecture.JPG does not exist.', u"404 Client Error: Not Found for url: https://<url>/_api/Web/getFileByServerRelativePath(DecodedUrl='%2Fsites%2FTest504%2FShared%20Documents%2FGeneral%2Farchitecture.JPG')?$select=ServerRelativePath")

**Code** 
import os
import tempfile
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File
url = "https://<company>.sharepoint.com"
username = "username"
password = "password"
file_url = "/sites/Test504/Shared Documents/General/architecture.JPG"
ctx_auth = AuthenticationContext(url)
ctx_auth.acquire_token_for_user(username, password)
ctx = ClientContext(url, ctx_auth)
web = ctx.web.get().execute_query()
download_path =  "/tmp/"+ os.path.basename(file_url)
with open(download_path, "wb") as local_file:
    file = ctx.web.get_file_by_server_relative_path(file_url).download(local_file).execute_query()
print("[Ok] file has been downloaded into: {0}".format(download_path))

**Comment by vgrem** [comment]
Greetings, 

according to file url from error description: 
> The file` /sites/Test504/Shared Documents/General/architecture.JPG` does not exist.', u"404 Error: Not Found

the corresponding site url is expected to be  `https://{tenant}.sharepoint.com/sites/Test504` instead of `https://{tenant}.sharepoint.com`. The error occurs since the _root_ site collection is provided while the file resides on  _another_ site collection (site collection represents an isolated container)   


An alternative option to download a file from _absolute url_: 

```python
abs_file_url = 'https://{tenant}.sharepoint.com/sites/Test504/Shared Documents/General/architecture.JPG'
with open(os.path.join(local_path, file_name), 'wb') as local_file:
        file = File.from_url(abs_file_url).with_credentials(user_credentials).download(local_file).execute_query()
```


Refer[ `download_file_from_url.py` example](../blob/master/examples/sharepoint/files/download_file_from_url.py)
