### ISSUE TITLE
Trying to add date column in share point list

### ISSUE THREAD

**Issue by GaneshBellana** [vgrem/Office365-REST-Python-Client#521]
I am trying to add or upload data of excel sheet into share point custom list which is created with all the columns with specified data types.
when I tried to add date columns in excel to date columns in share point list, it is not working ,but if i change the excel column into string and upload into sharepoint column with one line of text type , it is working.

**Comment by vgrem** [comment]
Hi,

when specifying `datetime` field value, ensure it is provided in [ISO 8601](http://www.iso.org/iso/home/standards/iso8601.htm) format, for example:  

```
field_name = "DateColumn"
field_value = date.today()
list_item.set_property(field_name, field_value.isoformat()).update().execute_query()
```
