### ISSUE TITLE
Batch load extended file and folder properties

### ISSUE THREAD

**Issue by davidorme** [vgrem/Office365-REST-Python-Client#522]
We're writing code to create an inventory of the files in a Sharepoint site and have:

```python
def get_sharepoint_folder_contents(ctx: ClientContext, dir: Folder):
    """
    Function to provide a dictionary of folders and files within a
    sharepoint folder.
    """

    # Get the sub-directories
    subdirs = dir.folders
    ctx.load(subdirs)
    ctx.execute_query()

    # Get the files
    files = dir.files
    ctx.load(files)
    ctx.execute_query()

    return dict(
        folders=[(sub.properties["ServerRelativeUrl"], sub) for sub in subdirs],
        files=[(f.properties["Name"], f) for f in files],
    )
```

where dir is accessed using:

```python
dir = ctx.web.get_folder_by_server_relative_url(root_dir_relative_url)
```

We'd like to extend this to include other fields - such as `Description` - but I can't figure out how to expand the query. I've seen the comments and code in #362 but that is set up to only handle individual files. We could loop over the files, but if it is possible to do it in one go that would be more efficient. 

Also - if I'm being honest - I can't get that approach to return anything!

```python
>>> # existing file reference for a file with Description
>>> file_url = file.properties['ServerRelativeUrl']
>>> file = ctx.web.get_file_by_server_relative_url(file_url).expand(["versions", "listItemAllFields"]).get().execute_query()
>>> file.listItemAllFields.get_property('Description') is None
True
```

**Comment by vgrem** [comment]
Greetings,

everything seems to be fine with the provided approach,  rather  `Description` property is a tricky part here, namely the way how it is exposed via REST API. 
A built-in `Description` field  of Documents library which internal name is 
`OData__ExtendedDescription` is not getting returned by default and needs to be explicitly retrieved for example via :

`GET /_api/Web/getFileByServerRelativeUrl('{file-url}')?$expand=listitemallfields/properties`

Here is a _modified_ example to retrieve 

```python
file = ctx.web.get_file_by_server_relative_url(file_url).expand(["versions", "listItemAllFields/properties"]).get().execute_query()
desc = file.listItemAllFields.get_property("Properties").get('OData__x005f_ExtendedDescription')  # <- Description field value
```
