### ISSUE TITLE
Adding bypass-shared-lock parameter to delete object request

### ISSUE THREAD

**Issue by dasiekr** [vgrem/Office365-REST-Python-Client#523]
Hi,
I'm wondering if it is possible to modify headers for delete_object method or write completely custom query.
I want to delete xlsx file on sharepoint but if anybody has this file open I'm not allowed to perform this action.
In order to allow that I need to use 'Prefer': 'bypass-shared-lock' in header of this request.

I'm not familiar with creating API request and thats why I ask here for help.
I would like to use below code which works after monkey patching in shareplum.

```
url = self.site_url + f"/_api/web/GetFileByServerRelativeUrl('{self.info['d']['ServerRelativeUrl']}/{file_name}')"

headers = {'Accept': 'application/json;odata=verbose',
           'If-Match': '*',
           'X-HTTP-Method': 'DELETE',
           'Prefer': 'bypass-shared-lock',    ### KEY PARAMETER
           'Content-Type': 'application/json;odata=verbose',
           'X-RequestDigest': self.contextinfo['FormDigestValue']}

post(self._session, url=url, headers=headers)
       'X-RequestDigest': self.contextinfo['FormDigestValue']}
```

**Comment by vgrem** [comment]
Greetings,

instead of constructing a custom request, would propose the following approach instead: 

```python
file_url = "/sites/team/Shared Documents/Guide.docx"


def custom_delete(request):
    """
    :type request: office365.runtime.http.request_options.RequestOptions
    """
    request.headers['Prefer'] = 'bypass-shared-lock'


file = ctx.web.get_file_by_server_relative_url(file_url)
ctx.before_execute(custom_delete)  # Modify request before it gets submitted to server
file.delete_object().execute_query()
```

The original delete operation  gets modified by appending a custom header into underlying request.

**Comment by dasiekr** [comment]
This is exactly what I was looking for.
Thanks so much for your help :)

**Comment by maylad31** [comment]
Does it also work for upload?
