### ISSUE TITLE
site.py", line 46    site_url = f"{root_site_url}sites/{alias}" error with python 2.7

### ISSUE THREAD

**Issue by maryam-hesham96** [vgrem/Office365-REST-Python-Client#529]
the f for format string isn't compatible with python 2.7 so it throws an error

**Comment by vgrem** [comment]
Thank you for catching this bug, it has been resolved in [`2.3.14` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.14)
