### ISSUE TITLE
I don't know argument in function

### ISSUE THREAD

**Issue by duksosleepy** [vgrem/Office365-REST-Python-Client#533]
drive = client.users["{user_id_or_principal_name}"].drive.get().execute_query()

The function client.users["{user_id_or_principal_name}"]. What is the ["{user_id_or_principal_name}"] ? 
When I type my username in this, my code raise exception  " 'dict' object is not callable ".

**Comment by vgrem** [comment]
Greetings,

it is expected to be either `id` or `userPrincipalName`  property(`str` type) where:

- `id` - The unique identifier for the user.
- `userPrincipalName`  The user principal name (UPN) of the user.

Examples

`drive = client.users["AdeleV@contoso.onmicrosoft.com"].drive`

`drive = client.users["87d349ed-44d7-43e1-9a83-5f2406dee5bd"].drive`

**Comment by duksosleepy** [comment]
Thank you so much !!!
