### ISSUE TITLE
ModuleNotFoundError: No module named 'office365.sharepoint.files.file_creation_information'

### ISSUE THREAD

**Issue by Nareshom** [vgrem/Office365-REST-Python-Client#535]
Hi.

i have very strange error,  code works fine in source machine where i developed my script, but when i do the same on the production system, i getting the error - ModuleNotFoundError: No module named 'office365.sharepoint.files.file_creation_information'

i did pip uninstall Office365-REST-Python-Client and reinstall the same, but still the same issue. i can assume this something to do with that particular system, same code works fine on the other production system. just wanted to double check if anyone have come across such error 

from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File
#above code executive  perfectly after that below code throw's error 

from office365.sharepoint.files.file_creation_information import FileCreationInformatio

Thanks in advance 
Naresh

**Comment by Nareshom** [comment]
Update:
my Source Machine where the version was 2.3.11 and new system version was 2.3.13. when i removed and installed 2.3.11 on the production system it worked.

**Comment by the-working-rene** [comment]
Hi, I also got that Error when Updating from 2.3.12 to a newer Version (2.3.13-2.3.16). Specifically when trying to import:
```python
from office365.sharepoint.files.file_creation_information import FileCreationInformation
```

The refactoring in version 2.3.13 seems to be the reason. It would be nice, if the old imports stay working on a minor upgrade. Maybe with a deprecation notice which warns about the api change.

The needed change in the code to workaround this issue, is to change

```python
from office365.sharepoint.files.file_creation_information import FileCreationInformation
```
 
to 

```python
from office365.sharepoint.files.creation_information import FileCreationInformation
```
