### ISSUE TITLE
No module named use Office365\Runtime\Auth\ClientCredential when I am using in PHP

### ISSUE THREAD

**Issue by exploreron** [vgrem/Office365-REST-Python-Client#536]
I have used these reference code with my core PHP project. I tried to connect thru examples/SharePoint/ConnectOnline.php - "examples\SharePoint/../vendor/autoload.php): failed to open stream: No such file or directory in"

other errors are getting:- 
1. /tests/sharepoint/FolderTest.php
    a. Fatal error: Uncaught Error: Class 'Office365\SharePointTestCase' not found in
    b. Error: Class 'Office365\SharePointTestCase' not found in

**Comment by vgrem** [comment]
This issue appears to belong to another project, namely [phpSPO](https://github.com/vgrem/phpSPO)
