### ISSUE TITLE
Getting additional field names from document library queried by a CAML query

### ISSUE THREAD

**Issue by denicomp** [vgrem/Office365-REST-Python-Client#542]
I want to get a list of files from a document library using a CAML query. This also needs to be recursive because the library contains many folders that have the files.

I can get this to work, but I need to get a URL to each of the files. However, when I use get_items(caml_query), it is not returning all of the fields on each file.  It is returning:

```
FileSystemObjectType
Id
ServerRedirectedEmbedUri
ServerRedirectedEmbedUrl
ContentTypeId
ComplianceAssetId
Title,
MediaServiceImageTags
MediaServiceOCR
ID
Created
AuthorId
Modified
EditorId
OData__CopySource
CheckoutUserId
OData__UIVersionString
GUID
```

What I think I need is one of these: FileRef, ServerUrl, EncodedAbsUrl

How do I tell it to get the fields I want - I see examples of how to do it getting an individual file, but what about when you want all files found using a CAML query, without making a separate API call on every file returned?

My code is like this:

```
	sp_lists = ctx.web.lists
	doclib = sp_lists.get_by_title("Some Document Library")
	query_text = '''<View Scope='Recursive'><Query><Where>
        <Eq>
            <FieldRef Name='Project_x0020_ID' />
            <Value Type='Text'>ABC123</Value>
        </Eq>
       </Where></Query></View>
        '''
	caml_query = CamlQuery.parse(query_text)
        sel_items = doclib.get_items(caml_query).execute_query()

         for item in sel_items
              url = item.properties["ServerUrl"]      <<< KeyError 'ServerUrl'
```

**Comment by vgrem** [comment]
Greetings,

to return a certain field values, they need to be explicitly specified via [`ViewFields` attribute](https://learn.microsoft.com/en-us/sharepoint/dev/schema/viewfields-element-list) as demonstrated below:

```python
qry = CamlQuery()
qry.ViewXml = f"""
    <View Scope='RecursiveAll'>
       <Query/>
        <ViewFields>
            <FieldRef Name='FileRef' />
            <FieldRef Name='EncodedAbsUrl' />
       </ViewFields>
       <RowLimit Paged='TRUE'>100</RowLimit>
    </View>
    """
items = lib.get_items(qry).execute_query()
```

**but** it appears (sadly) [`items` endpoint](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest)  _ignores_ those system fields (e.g. as `FileRef`,  `EncodedAbsUrl` and a few another) and they never gets returned.

To circumvent this limitation, would suggest to switch to [OData `$select` and `$filter` query options](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests) instead:



```python
from_datetime = datetime.datetime(2022, 1, 20, 0, 0)
filter_text = "Created gt datetime'{0}'".format(from_datetime.isoformat())
include_fields = ["Created", "FileRef", "EncodedAbsUrl"]
items = lib.items.filter(filter_text).select(include_fields).get().execute_query()
```
