### ISSUE TITLE
Question : Pass Proxy to ClientContext with credentials

### ISSUE THREAD

**Issue by MagMeten** [vgrem/Office365-REST-Python-Client#548]
Hi,
I'm connecting to my organization sharepoint with success if I'm connecting using personal network, however when I'm using the organization network, I can't, because we need to connect using a proxy. (as I'm doing when I'm installing libraries using pip)
I'm not finding where I can add my proxy information.
My code is the following : 
```
from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext

site_url = 'https://tenant.sharepoint.com/sites/site'

app_principal = {
    'client_id': 'my_client_id',
    'client_secret': 'my_client_secret',
}

credentials = ClientCredential(app_principal['client_id'], app_principal['client_secret'])
ctx = ClientContext(site_url).with_credentials(credentials)
web = ctx.web.get().execute_query()
print("Web title: {0}".format(web.properties['Title']))
```
Thanks in advance for your help

**Comment by braveru** [comment]
use os.environ for the proxy settings : 
`
    import os
    os.environ['http_proxy'] = 'http://xxx.xxx.com:port'
    os.environ['https_proxy'] = 'http://xxx.xxx.com:port'
    os.environ['HTTP_PROXY'] = 'http://xxx.xxx.com:port'
    os.environ['HTTPS_PROXY'] = 'http://xxx.xxx.com:port'
`

**Comment by MagMeten** [comment]
Perfect it works just fine. Thank you very much.
