### ISSUE TITLE
100 rows limit. 

### ISSUE THREAD

**Issue by Toilal** [vgrem/Office365-REST-Python-Client#55]
I just hit ths issue, it took me a long time to figure out what was really going on. 

https://sharepoint.stackexchange.com/questions/74777/list-api-get-all-items-limited-to-100-rows

How could we make iterator return all elements instead of only 100 first?

**Comment by Toilal** [comment]
I used the top() method, maybe it's enough

**Comment by vgrem** [comment]
Greetings,

`$top` query option should suffice for most cases of querying large lists.

To summarize the following options are available:

- using [$top query option](https://msdn.microsoft.com/en-us/library/dd541263.aspx) to explicitly specify the amount of items to return 
return _paged results_ using via `$skiptoken` as demonstrated in [this answer](https://sharepoint.stackexchange.com/a/128885/10610)

**Comment by haozheng522** [comment]
Hi vgrem and Toilal,

I'm facing the same problem, trying to use get_items() extract items from a column, but it has a 100 items limit. It seems this ticket is the most related one to my problem. 
For the $top query to change the limit, I haven't found a way to do it in the python script, could you should me how to achieve it in the python? Much appreciate!
