### ISSUE TITLE
Updating STSProfile ServiceURL for Azure National Cloud using Username and Password Credentials

### ISSUE THREAD

**Issue by ntomczek** [vgrem/Office365-REST-Python-Client#550]
I've been working on pulling SharePoint data and ran into an issue with Azure National Cloud. I am currently limited to username and password to connect. 

Currently when the STSProfile class initializes it sets the serviceURL to 'https://login.microsoftonline.com'. 
When the function `_acquire_service_token` in SamlTokenProvider.py is called it creates a new instance of of STSProflie and pulls the `_sts_profile.security_token_service_url` which will always point to Pub cloud. This results in the following error:

`AADSTS90038: Tenant '<tenant>' request is being redirected to the National Cloud`

If I manually change the serviceURL to 'https://login.microsoftonline.us'. Everything works fine.

I have not been able to find a way to update the serviceURL to point to National Cloud via the ClientContext, RequestOptions or other means. Before I start working on alternative security methods, or a fix, I wanted to verify that I'm not missing an existing way to make this change.

**Comment by bamartin125** [comment]
I am also hitting this same issue. It would be nice to someday determine the right way to handle this, but in the interim, I am willing to settle for a workaround.

@ntomczek , did you find a workaround suitable for your use case? If so, would you be willing to share that here?

**Comment by ntomczek** [comment]
@bamartin125 Yes, I was able to find a workaround. I added a monkey patch in our Python code to overwrite the URL endpoint at runtime. 

I have the following method in a class I use for the call:
```python
def update_security_token_service_url()
   return "/".join(['https://login.microsoftonline.us', 'extSTS.srf'])
```

Then this is the patch that overwrites the default value:
```python
if __name__ == '__main__'
   STSProfile.security_token_service_url = <my class name>.update_security_token_service_url()
```

You could obviously simplify this to have the method return value in the patch itself this just lines up with how our team wrote the app.

**Comment by vgrem** [comment]
Closing as resolved since SharePoint authentication support with GCC High Environments has been introduced in [`2.5.4`](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.4) version
