### ISSUE TITLE
How to download a file shared with me from SharePoint or OneDrive?

### ISSUE THREAD

**Issue by pietrogalvagni** [vgrem/Office365-REST-Python-Client#553]
Hello @vgrem, 
I was able to download a file from my personal SharePoint following the ReadMe (create credential client_id and client_secret), but now I need to download a file **shared** with me by another account. The file is shared within my organization (so it's not public). Is that possible?

My current code is the following

```
class SharePoint:

    def auth(self):
        cred = ClientCredential(CLIENT_ID, CLIENT_SECRET)
        ctx = ClientContext(URL_SITE).with_credentials(cred)
        return ctx

    def downloadFile(self, fileName, folderName):
        conn = self.auth()
        file = conn.web.get_file_by_guest_url(SHAREPOINT_URL).execute_query()
        print(file.name)

        with open(f"{LOCAL_FOLDER}/{file.name}", "wb") as f:
            file.download(f).execute_query()
```

If SHAREPOINT_URL is generated from a file in my drive, the code works fine. If it comes from a file shared with me, it doesn't work. The following exception arise:

> ClientRequestException
('-2130575338, Microsoft.SharePoint.SPException', 'The file |0 does not exist.', '404 Client Error: Not Found for url: https://xxx.sharepoint.com/personal/pietro_galvagni_xxx_com/_api/Web/GetFileByGuestUrl')

Do you know a way to get the file?
Thank you

**Comment by pietrogalvagni** [comment]
No clues on how can be done in this regard?

**Comment by vgrem** [comment]
Greetings,

most likely the error occurs since the provided file does not resides at site collection against which`ClientContext` get initialized:     

```
ctx = ClientContext(URL_SITE).with_credentials(cred)
                              ^^^^^^^^^^^
                        invalid site collection 
```


Make sure a _proper_ site url is provided which could be determined from guest link url. For instance, for guest link: `https://contoso.sharepoint.com/:x:/s/team/{link}`, `ClientContext` is expected to be initialized like this:

`ctx = ClientContext("https://contoso.sharepoint.com/sites/team").with_credentials(cred)`

**Comment by pietrogalvagni** [comment]
Hello @vgrem, thank you for your answer

I still can't figure out how to solve the issue, since in my case the urls are a bit different. In my real case, I have these values

```
// Client context
URL_SITE = "https://companyname-my.sharepoint.com/personal/pietro_galvagni_xxx_com/"
cred = ClientCredential(CLIENT_ID, CLIENT_SECRET)
ctx = ClientContext(URL_SITE).with_credentials(cred)

// File I want to download but cannot
URL_DOWNLOAD = https://companyname-my.sharepoint.com/:w:/g/personal/emanuele_trabattoni_xxx_com/<alphanumeric_string>?e=<another_string>
file = conn.web.get_file_by_guest_url("URL_DOWNLOAD ").execute_query()

// File I'm able to download
URL_DOWNLOAD2 = https://companyname-my.sharepoint.com/:w:/g/personal/pietro_galvagni_xxx_com/<alphanumeric_string>?e=<another_string>
file = conn.web.get_file_by_guest_url("URL_DOWNLOAD2 ").execute_query()
```

Please notice the different name inside the urls. Also, `CLIENT_ID` and `CLIENT_SECRET` are generated from my account (Pietro Galvagni)
Can be a fault of the `/g/` instead of `/s/` inside the link? (I'm not sure about what these letters mean)
