### ISSUE TITLE
ModuleNotFound: no mudule named office365

### ISSUE THREAD

**Issue by FunnyGoofy** [vgrem/Office365-REST-Python-Client#555]
Why does this happen? Please help me out. 

I emitted two commands:

1. pip install office365
2. pip install  office365-REST-Python-Client

![image](https://user-images.githubusercontent.com/27033943/185204722-a0d8cb3b-884c-4da2-8d50-4572cbd95bcb.png)

Thank you so much

**Comment by vgrem** [comment]
Greetings,

the _official_ package could be installed via: 

`pip install office365-REST-Python-Client`

and below is demonstrated an Azure function (minimal) example.


### Prerequisites

- [Azure Functions Core Tools version 3.x](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#install-the-azure-functions-core-tools)

### `Requirements.txt`

```
azure-functions
Office365-REST-Python-Client
```


### `__init__.py`

```python
import json
import os

import azure.functions as func
from office365.sharepoint.client_context import ClientContext

site_url = os.environ['SiteUrl'] 
username = os.environ['Credentials_Username'] 
password = os.environ['Credentials_Password'] 


def main(req: func.HttpRequest) -> func.HttpResponse:
    ctx = ClientContext(site_url)
    ctx.with_user_credentials(username, password)
    me = ctx.web.current_user.get().execute_query()
    return func.HttpResponse(json.dumps(me.to_json()),status_code=200)
```

**Comment by FunnyGoofy** [comment]
great, it works as I expect.
