### ISSUE TITLE
Search emails in Outlook

### ISSUE THREAD

**Issue by etiennecelery** [vgrem/Office365-REST-Python-Client#557]
Hi all, is there any way to search emails in an inbox or specific folder?
I saw there's a Search API but it is only available for Sharepoint and Onedrive.
Thank you

**Comment by vgrem** [comment]
Greetings,

search endpoint appears to be way to go, but sadly, i haven't managed to get it working with specific folder (`parentFolderId` property) 

```python
inbox = client.me.mail_folders["Inbox"].get().execute_query()
query_text = "parentFolderId:{0}".format(inbox.id)
result = client.search.query_messages(query_text).execute_query()
```

where `SearchEntity.query_messages` method corresponds to search endpoint for a messages   

[This thread](https://learn.microsoft.com/en-us/answers/questions/656200/graph-api-to-filter-results-on-39from39-and-39subj.html) reports the similar issue:

> I don't quite understand why the folderId: predict doesn't work in the graph


Another approach would be to utilize `$filter` query option , the following example demonstrates how to search messages by `subject` in inbox:

```python
graph_client = GraphClient(acquire_token_by_username_password)
inbox = client.me.mail_folders["Inbox"]  # type: MailFolder
result_messages = inbox.messages.filter("subject eq '{0}'".format(text)).get().execute_query()
```


**References**



- [Update to Filtering and Sorting in the Mail, Calendar and Contacts REST API](https://devblogs.microsoft.com/microsoft365dev/update-to-filtering-and-sorting-rest-api/)
