### ISSUE TITLE
List a sharepoint folder using python office365 containing more than 5000 files

### ISSUE THREAD

**Issue by rakekris** [vgrem/Office365-REST-Python-Client#558]
`from office365.runtime.auth.client_credential import ClientCredential
from office365.runtime.client_request_exception import ClientRequestException
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File
import io
import datetime
import pandas as pd
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File
import io
import datetime
import pandas as pd
app_principal = {
        'client_id': 'xxxxxxxxxxxxxxxxxxxxxxx',
        'client_secret': 'xxxxxxxxxxxxxxxxxxxxxxx'
}

sp_site = 'https://<domain>.sharepoint.com/sites/TSM839/'
relative_url = "/sites/TSM839/Shared Documents"
client_credentials = ClientCredential(app_principal['client_id'], app_principal['client_secret'])
ctx = ClientContext(sp_site).with_credentials(client_credentials)
libraryRoot = ctx.web.get_folder_by_server_relative_path(relative_url)
ctx.load(libraryRoot)
ctx.execute_query()
files = libraryRoot.files
ctx.load(files)
ctx.execute_query()
len(files)`

This program works perfectly when the number of files in the sharepoint folder is < 5000, when it is > 5000, getting below exception
![image](https://user-images.githubusercontent.com/22142158/188210729-4109aa08-3953-4f46-8259-9bd7d65628e2.png)

**Comment by rakekris** [comment]
@vgrem , can you please share the approach . It is critical for go live.
your help is much appreciated

**Comment by Danxx26hub** [comment]
> @vgrem , can you please share the approach . It is critical for go live.
> your help is much appreciated

That error is a share point limitation in views. You can’t have a view with over 5k items.. you will need to create index columns and then apply them to your SharePoibt libraries view.

**Comment by Danxx26hub** [comment]
> > @vgrem , can you please share the approach . It is critical for go live.
> > your help is much appreciated
> 
> That error is a share point limitation in views. You can’t have a view with over 5k items.. you will need to create index columns and then apply them to your SharePoibt libraries view.

Here is a really good article on dealing / overcoming this limitation https://social.technet.microsoft.com/wiki/contents/articles/53460.sharepoint-troubleshooting-5000-list-view-threshold-limit-issue.aspx

**Comment by vgrem** [comment]
Greetings,

this is the _expected_ behavior and the reason why this exception occurs in the first place is due to threshold limit in SharePoint. the list view threshold which is configured at 5,000 items by default. When one try to access more than 5000 items at a time, the exception occurs.

One of the options to circumvent this behavior is consider to _paged data retrieval_ mode, which is supported by library 

**Note**:

> make sure to update to the latest version (`2.3.14` atm) which introduces a few enhancements in this regard


Here are a few examples:

1) retrieve all the items in a collection, regardless of the size via `ClientObjectCollection.get_all` method:


``` python 
def print_progress(items):
    """
    :type items: office365.sharepoint.listitems.collection.ListItemCollection
    """
    print("Items read: {0}".format(len(items)))

page_size = 500
ctx = ClientContext(site_url).with_credentials(client_credentials)
large_list = ctx.web.lists.get_by_title(list_title)
all_items = target_list.items.get_all(page_size, print_progress).execute_query()
```

2) retrieve paged data via `ClientObjectCollection.paged` method:

``` python 
page_size = 500

ctx = ClientContext(site_url).with_credentials(client_credentials)
large_list = ctx.web.lists.get_by_title(list_title)
paged_items = large_list.items.paged(page_size, page_loaded=print_progress).get().execute_query()
    for index, item in enumerate(paged_items):  # type: int, ListItem
        print("{0}: {1}".format(index, item.id))
```

**Comment by JuanFilho** [comment]
> Greetings,
> 
> this is the _expected_ behavior and the reason why this exception occurs in the first place is due to threshold limit in SharePoint. the list view threshold which is configured at 5,000 items by default. When one try to access more than 5000 items at a time, the exception occurs.
> 
> One of the options to circumvent this behavior is consider _paged data retrieval_, which is supported by library
> 
> **Note**:
> 
> > make sure to update to the latest version (**`2.3.14`** atm) which introduces a few enhancements in this regard
> 
> Here are a few examples:
> 
> 1. retrieve all the items in a collection, regardless of the size via `ClientObjectCollection.get_all` method (_recommended_):
> 
> ```python
> def print_progress(items):
>     """
>     :type items: office365.sharepoint.listitems.collection.ListItemCollection
>     """
>     print("Items read: {0}".format(len(items)))
> 
> page_size = 5000
> ctx = ClientContext(site_url).with_credentials(client_credentials)
> large_list = ctx.web.lists.get_by_title(list_title)
> all_items = target_list.items.get_all(page_size, print_progress).execute_query()
> ```
> 
> 2. retrieve paged data via `ClientObjectCollection.paged` method:
> 
> ```python
> page_size = 5000
> 
> ctx = ClientContext(site_url).with_credentials(client_credentials)
> large_list = ctx.web.lists.get_by_title(list_title)
> paged_items = large_list.items.paged(page_size, page_loaded=print_progress).get().execute_query()
>     for index, item in enumerate(paged_items):  # type: int, ListItem
>         print("{0}: {1}".format(index, item.id))
> ```

Hello vgrem!
I tried your approach on this method and somedays ago it worked, but as it seems, it's not working anymore as intended. It gives me this error: `AttributeError: 'ListItemCollection' object has no attribute 'get_all'`

Do you have any idea why this happens?
