### ISSUE TITLE
Unable to import tests while uploading a file to sharepoint

### ISSUE THREAD

**Issue by imagautham** [vgrem/office365-rest-python-client#560]
I'm trying to upload a file to a sharepoint site and was referring to the below link:
https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/files/upload_file.py

I was replicating the same code, but when i try to execute the below code,

`from tests import test_user_credentials, test_team_site_url`

I'm getting an error: **ImportError: cannot import name 'test_user_credentials' from 'tests'**

I tried searching online, but was not able to find a similar issue. I tried to do `pip install tests` but that is not able to find.

Meanwhile, I already have python rest api installed using `pip install Office365-REST-Python-Client`

How do I solve this issue?

**Comment by vgrem** [comment]
Hi,

those are tests specific variables, here is a modified example which demonstrates how to initialize `UserCredential`:


```python 
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.user_credential import UserCredential

site_url = "https://contoso.sharepoint.com"
user_credentials = UserCredential("--login--", "--password--")

ctx = ClientContext(site_url).with_credentials(user_credentials)

path = "../../data/report #123.csv"
with open(path, 'rb') as content_file:
    file_content = content_file.read()

list_title = "Documents"
target_folder = ctx.web.lists.get_by_title(list_title).root_folder
name = os.path.basename(path)
target_file = target_folder.upload_file(name, file_content).execute_query()
print("File has been uploaded to url: {0}".format(target_file.serverRelativeUrl))
```
