### ISSUE TITLE
Empty Files in 'Documents'

### ISSUE THREAD

**Issue by stopwind93** [vgrem/Office365-REST-Python-Client#563]
Hi, I have been trying for 2 weeks with multiple different codes in displaying files in 'Shared Documents'.
Seems like I am able to access 'Shared Documents' but unable to access the files inside.
Is it an authentication issue?

I am using a linux machine. Will it affect?

![Untitled](https://user-images.githubusercontent.com/54277944/189261259-df00ad93-3a32-435d-a0bc-38b16e24179a.png)

**Comment by vgrem** [comment]
Hey, 

files are expected to be requested _explicitly_. In case of `ClientObject.load` method second argument is intended for that purpose.  Given the provided example, consider to replace   `ctx.load(folder)` with `ctx.load(folder, ["Files"])` to retrieve folder metadata along with files.

**Comment by stopwind93** [comment]
Hi @vgrem,

Thanks for your prompt response.
I tried your method and it still return empty.
Appreciate for any of your guidance.

![1](https://user-images.githubusercontent.com/54277944/189559000-2512cc2d-a2dd-4ace-8ee3-95e363666451.png)

I verified that there are indeed files in 'Shared Documents' as well.
![2](https://user-images.githubusercontent.com/54277944/189559198-dfd284d3-dc72-44d6-8ab4-a8e51a754a64.png)

**Comment by stopwind93** [comment]
Hi @vgrem,

Do you think is it possible is an authentication issue?

**Comment by vgrem** [comment]
Greetings @stopwind93,

> Do you think is it possible is an authentication issue?

seems like this,  perhaps the permissions have not been granted per application ([**step 7**](https://github.com/vgrem/Office365-REST-Python-Client/wiki/How-to-connect-to-SharePoint-Online-and-and-SharePoint-2013-2016-2019-on-premises--with-app-principal) per this instruction)?  




The following example demonstrates how to determine current user (App Principal in this example) permissions for a list:

```python
ctx = ClientContext(site_url).with_credentials(client_credentials)

doc_lib = ctx.web.default_document_library()  # <- default_document_library refers to default Documents library
result = doc_lib.get_user_effective_permissions(ctx.web.current_user).execute_query()
print(result.value.permission_levels)
```

`permission_levels` property is expected to contain at least `ViewListItems` permission level, which [per documentation:](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee536458(v=office.15))

> `ViewListItems` | View items in lists, documents in document libraries, and Web discussion comments.






View items in lists, documents in document libraries, and Web discussion comments.

**Comment by stopwind93** [comment]
Hi @vgrem,

Does this mean the permissions have not been granted properly?
![image](https://user-images.githubusercontent.com/54277944/190371059-7df24fb6-133b-4359-b4d3-16601c10b64c.png)

**Comment by vgrem** [comment]
According to screenshot, seems this way, meaning permissions have not been granted per provided site collection.   


**Another possible reason**

Although it also might be case when a _custom_ permissions have been assigned _per library_ , it could be verified via Library Settings -> More Library Settings -> Permissions for this document library

the message is expected to be getting displayed in this is the case: 
> This library has unique permissions. 


Per [official documentation](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint) the minimum permission request could look like this:


```xml
<AppPermissionRequests AllowAppOnlyPolicy="true">
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
</AppPermissionRequests>
```

where 
- grant page `htps://{your-tenant}.sharepoint.com/sites/BCSQ/_layouts/15/appinv.aspx`
- scope: `SiteCollection`
- rights: `Read`

**Comment by stopwind93** [comment]
Hi @vgrem,

Thank you so much for your guidance and help.
It is working after my IT team helped to change the scope to Scope="http://sharepoint/content/sitecollection"
