### ISSUE TITLE
Adding images (not attatchment) in a column of a list

### ISSUE THREAD

**Issue by josegarciaestrada** [vgrem/Office365-REST-Python-Client#564]
Hi everyone

I have a issue because i want to upload a image from databricks folder, actually I could do this but in a folder (not a list) so i defined a function in python:

I replace real data with dummy data for security

def add_to_list_2(list_name, blob_file_path):
  #--------------------------------------------------------------
  from modules.office365.runtime.auth.authentication_context import AuthenticationContext
  from modules.office365.runtime.client_request import ClientRequest
  from modules.office365.sharepoint.client_context import ClientContext
  from modules.office365.sharepoint.attachments.creation_information import AttachmentCreationInformation
  import base64
  

  url='https:.sharepoint.com/sites/data/
  username = user
  pwd = 'pwd'
  ctx_auth = AuthenticationContext(url)
  ctx_auth.acquire_token_for_user(username, pwd)   
  ctx = ClientContext(url, ctx_auth)
  blobpath = '/dbfs' + blob_file_path
  filename=os.path.basename(blob_file_path)
  with open(blobpath, 'rb') as content_file:
    file_content = base64.b64encode(content_file.read())
  list_object = ctx.web.lists.get_by_title(list_name)
  store_nk=filename[0:9]
  year_month_id=filename[10:17]
  new_item = list_object.add_item({
    "STORE_NK": store_nk,
    "YEAR_MONTH_ID": year_month_id,
    "IMG_TEST": file_content#<--------------------------column with image type
  }).execute_query()

I got the following error when i tried to execute and insert  image (contained in file_content)
  ('-2147024809, System.ArgumentException', 'parameters\r\nParameter name: Specified value is not supported for the parameters parameter.

I tried to fill the fields of this list without the image and i was succesfull, but when i try to add image i got the error

**Comment by andresgd7** [comment]
damn, im looking exactly for the same

**Comment by josegarciaestrada** [comment]
Thank you! @vgrem  It works fine
