### ISSUE TITLE
Get a list of column names

### ISSUE THREAD

**Issue by matteoaurelio** [vgrem/Office365-REST-Python-Client#566]
Hi,

Is there any possibility of getting a list of the column names (let's say we don't know which columns we have in the List beforehand) from the Python API?

**Comment by vgrem** [comment]
Greetings,

surely, this operation along with another operations are supported, the full list of supported operations could be found [here](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code):  


The example demonstrates how to retrieve all the fields(columns) for a list (adapted from [this example](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code#retrieve-all-of-the-fields-in-a-list)):

```python
client = ClientContext(site_url).with_credentials(credentials)
target_list = client.web.lists.get_by_title("Site Pages")
fields = target_list.fields.get().execute_query()
```
