### ISSUE TITLE
Column 'AssignedToId' does not exist. 

### ISSUE THREAD

**Issue by BananaHsu** [vgrem/Office365-REST-Python-Client#567]
Hi, I'd like to update the data to someone else with his/her email id. Although the column displayed on the Web site is "AssignedTo", I got "AssignedToId" and "AssignedToStringID" by using item.properties.keys(). So I try to update the key "AssignedToId", but it pops up the error saying it doesn't exist. Is it correct to use properties.keys()  to get the column list? or is there any other way I can get the correct keys for "AssginedTo".

**Comment by vgrem** [comment]
Greetings,

assuming  `AssignedTo` field is of `User` field type, it could be updated/set as demonstrated below:

`list_item.set_property("AssignedTo", FieldUserValue(user_id)).update().execute_query()`


where `FieldUserValue` is a user field value type and `user_id` is mandatory prop which corresponds to user identifier 


Alternately `FieldUserValue` could be initialized from user object:

```python
me = ctx.web.current_user
list_item.set_property("AssignedTo", FieldUserValue.from_user(me)).update().execute_query()
```
