### ISSUE TITLE
AuthenticationContext.with_client_certificate cannot work with in-memory certificates

### ISSUE THREAD

**Issue by rbubley** [vgrem/Office365-REST-Python-Client#568]
AuthenticationContext.with_client_certificate reads in a certificate from a path (`cert_path`). This is fine if you have a filesystem, but is hard to use if you don't.

It would be good to be able to give the private_key as a string as an alternative to it being read from a file.

**Comment by vgrem** [comment]
Greetings,

in [`2.3.15` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.15) it is supported to pass `private_key` as a string:


```python
cert_path = 'selfsigncert.pem'
with open(cert_path, 'r') as f:
      private_key = open(cert_path).read()

cert_credentials = {
     'tenant': test_tenant,
     'client_id': '--client id--',
     'thumbprint': '--thumbprint--',
     'private_key': private_key
}
ctx = ClientContext(test_team_site_url).with_client_certificate(**cert_credentials)
```
