### ISSUE TITLE
Getting an error when i try to stream a document on share point.

### ISSUE THREAD

**Issue by skywalker45** [vgrem/Office365-REST-Python-Client#572]
I inherited some code from an old co-worker, and i think the code might be outdated, but can someone explain why i get a 404?

Here are the import statements:
```
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.runtime.client_request import ClientRequest
from office365.sharepoint.client_context import ClientContext
from office365.runtime.http.request_options import RequestOptions
from office365.sharepoint.files.file import File
import urllib.parse
```
This is how i authenticate, and send the request:
```
ctx_auth = AuthenticationContext(sharepoint_url) 
        if ctx_auth.acquire_token_for_user(environ['sharepoint_user'], environ['sharepoint_pass']):
            context = ClientContext(sharepoint_url, ctx_auth)
            #build sharepoint query request
            sharepoint_request = ClientRequest(ctx_auth)
            sharepoint_options = RequestOptions(sharepoint_query_url)
            sharepoint_options.set_header('Accept', 'application/json')
            sharepoint_options.set_header('Content-Type', 'application/json')
            sharepoint_response = sharepoint_request.execute_request_direct(sharepoint_options)
            data = json.loads(sharepoint_response.content)
      }
```

from that response, there is logic to grab the path, extention, and sitename:
```
 for each in data['PrimaryQueryResult']['RelevantResults']['Table']['Rows'][0]['Cells']:
                if each['Key'] == "Path":
                    filePath = each['Value']
                if each['Key'] == "FileExtension":
                    fileExtension = each['Value']
                if each['Key'] == 'SiteName':
                    sharepoint_site = each['Value']
```
Then using the site name, this is done again:
```
context = ClientContext(sharepoint_site, ctx_auth)
```
Then an attempt is made to stream the file back to the get request:
```
relative_path = filePath.replace(sharepoint_url,'')
                app.logger.critical("filename: " + fileName)
                app.logger.critical("relative_path: " + relative_path)
                binary_pdf = File.open_binary(context, urllib.parse.quote(relative_path))
                print(binary_pdf.status_code)
                file_response = make_response(binary_pdf.content)
                file_response.headers['Content-Type'] = 'application/pdf'
                file_response.headers['Content-Disposition'] = 'inline; filename=%s' % fileName
                return file_response
```
The binary.status_code is always 404.  I think the issue is grabbing the sitename from the response, as it started returning null which probably doesn't set the right context. My question is; is there another way to grab the siteName from the response? or is there something im doing wrong?

**Comment by vgrem** [comment]
Greetings,

first of all, a few recommendations if you don't mind:

1)to initialize an authenticated context, nowadays a preferred way would be

```python
user_credentials = UserCredential('username', 'password')
ctx = ClientContext(site_url).with_credentials(user_credentials)
```

instead of: 

```python
if ctx_auth.acquire_token_for_user(environ['sharepoint_user'], environ['sharepoint_pass']):
       context = ClientContext(sharepoint_url, ctx_auth)
```


2) since  it is supported to download a file by _absolute_ url, would suggest to utilize `File.from_url `method over `File.open_binary`. Among the benefits, no need to construct site url and server relative file url.  



Now comes the turn of error itself. Since the search request is a _cross site query_, the result might contains links to files which reside in _different_ site collections, meaning the following line would fail:

> `binary_pdf = File.open_binary(context, urllib.parse.quote(relative_path))`

if `context` has been initialized against a one site collection, while `relative_path` refers to file from another site collection, for example:

-  `ctx = ClientContext("https://contoso.sharepoint.com/sites/siteA").with_credentials(user_credentials)`  - **Note**: `ClientContext` is always getting initialized in terms of site collection scope (security boundary)  
-  `relative_path = "/sites/siteB/Documents/Report.xslx"`





Here is a complete example which demonstrates how to search files and download them no matter on what site collection they reside: 


```python
import json
import os
import tempfile

from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.files.file import File
from office365.sharepoint.search.request import SearchRequest
from office365.sharepoint.search.service import SearchService


def extract_cell_value(cells, name):
    """
    Extract cell value
    """
    return next((c.get("Value") for c in cells.values() if c.get("Key") == name), None)


def download_file_from_url(abs_file_url, credentials):
    download_path = os.path.join(tempfile.mkdtemp(), os.path.basename(abs_file_url))
    with open(download_path, 'wb') as f:
        file = File.from_url(file_url).with_credentials(credentials).download(f).execute_query()
    print("[Ok] file has been downloaded into: {0}".format(download_path))


user_credentials = UserCredential('--username--',  '--password--')
ctx = ClientContext('--site_url--').with_credentials(user_credentials)
search = SearchService(ctx)

request = SearchRequest(query_text="IsDocument:1", select_properties=["Title", "Path"],
                        trim_duplicates=False, row_limit=50)
result = search.post_query(request).execute_query()
relevant_results = result.value.PrimaryQueryResult.RelevantResults
for i in relevant_results['Table']['Rows']:
    cur_cells = relevant_results['Table']['Rows'][i]['Cells']
    file_url = extract_cell_value(cur_cells, "Path")
    download_file_from_url(file_url, user_credentials)

```

**Comment by skywalker45** [comment]
Nice! really really nice! Incase anyone comes across this, to display the content of the pdf or document on a web page,
```
file = File.from_url(file_url).with_credentials(credentials).download(f).execute_query()
```
becomes 
```
file = File.from_url(file_url).with_credentials(credentials).execute_query()
```
then in order to return a response for a get request of the pdf file, you have to set a property on the file or it raises a ```valueError``` when you call ```file.read()```. You need to call ```file.read``` because inorder to use flask to return the response, you can't pass the file to the function ```make_response()``` you have to pass in the content of the file which you can get by calling ```file.read```. but you need to call ```set_property()``` and pass in the ```ServerRelativeUrl```. 

Huge thanks to you @vgrem
