### ISSUE TITLE
Basic authentication in sharepoint auth flow

### ISSUE THREAD

**Issue by adolfofp** [vgrem/Office365-REST-Python-Client#573]
Hi
With microsoft dropping basic authentication in a few weeks, i would like to know if current sharepoint auth flows ( including user credentials )will continue to work

I have seen oauth is supported in graph api (like outlook) in your readme, but i dont see anything for sharepoint

**Comment by vgrem** [comment]
Hi,

would like to confirm, SharePoint auth flows will not be affected by [deprecation of Basic authentication](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online), including user credentials flow (SAML-based claims authentication)
