### ISSUE TITLE
Creating MS Word documents

### ISSUE THREAD

**Issue by rickbps** [vgrem/Office365-REST-Python-Client#576]
Are there any plans to include the Office365 API for MS Word?

**Comment by vgrem** [comment]
Greetings,

in terms of creating a word document, it could be created via SharePoint API like this:

 
```python 
ctx = ClientContext(site_url).with_credentials(credentials)
result = ctx.web.default_document_library().create_document_with_default_name("","docx").execute_query()
print(f"'{result.value}' file has been created")
```

where  `create_document_with_default_name` method: 

> Creates a empty document with default filename with the given extension at the path given by `folderPath`. Returns the name of the newly created document.
