### ISSUE TITLE
Uploading Files to Sharepoint Subfolder

### ISSUE THREAD

**Issue by ThomasMBennett** [vgrem/Office365-REST-Python-Client#577]
Hi,

I'm struggling to upload local files to Sharepoint subfolders in this API's latest version. Previous issues seem to relate to example files which either no longer exist or feature deprecated functions.

I'm basing my code on the upload_file.py example:

```
import os
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.authentication_context import AuthenticationContext


siteurl = 'https://xxxxx.sharepoint.com/sites/xxxxx'


ctx_auth = AuthenticationContext(siteurl)
ctx_auth.acquire_token_for_user('user@site', 'password')
ctx = ClientContext(siteurl, ctx_auth) # make sure you auth to the siteurl.

path = "test_upload.csv"
with open(path, 'rb') as content_file:
    file_content = content_file.read()

path = 'sites/xxxxx/ Shared Documents/subfolder/test_upload.csv'


list_title = "Documents"
target_folder = ctx.web.lists.get_by_title(list_title).root_folder
name = os.path.basename(path)
target_file = target_folder.upload_file(name, file_content).execute_query()
print("File has been uploaded to url: {0}".format(target_file.serverRelativeUrl))
```

Which works, uploading the file "test_upload.csv" to the base "Documents" folder. trying to change any of the paths leads to a 404, or 403 authentication error. Please let me know how I would be able to upload the same file to the location in the "path" variable: ```sites/xxxxx/ Shared Documents/subfolder/test_upload.csv```

Many thanks

**Comment by vgrem** [comment]
Greetings,

according to this line:  `ctx.web.lists.get_by_title(list_title).root_folder` an file is landed into a folder `/sites/xxxxx/ Shared Documents` rather then of expected one: `/sites/xxxxx/ Shared Documents/subfolder.`  


Would suggest to a address a  (target) folder this way instead:

target_folder = ctx.web.get_file_by_server_relative_url("'/sites/xxxxx/ Shared Documents/subfolder")

then a file is expected to get uploaded into a proper sub folder (`subfolder`)
