### ISSUE TITLE
Generating embeddable links for SharePoint files

### ISSUE THREAD

**Issue by EverSoJoe** [vgrem/office365-rest-python-client#578]
Is there a way to generate embeddable style links for a file?
For Example:
`https://<tenent>.sharepoint.com/sites/<site>/_layouts/15/embed.aspx?UniqueId=<UID>`

I did not find anything like that in the examples or in my own searches.

Thank you for any help!

**Comment by vgrem** [comment]
Greetings,

since the provided link which represents a preview page url expects a file unique identifier  (`UniqueId`), perhaps like this? 

```python
file_url = "/Shared Documents/Dummy.pdf"

file = ctx.web.get_file_by_server_relative_path(file_url).get().execute_query()
preview_url = "{0}/_layouts/15/embed.aspx?UniqueId={1}".format(ctx.base_url, file.unique_id)
print(preview_url)
```

**Comment by EverSoJoe** [comment]
Thank you for the quick answer! This works like a charm. For the relative path there is the prefix '/site/<sitename>' missing, but other than that this is great, thank you!

It's really not easy to work with the Office365 APIs at all.
