### ISSUE TITLE
Outlook: Sending HTML content in message body

### ISSUE THREAD

**Issue by etiennecelery** [vgrem/Office365-REST-Python-Client#579]
Hi all,
Thanks for all the help.
I'm having trouble sending html content in an Outlook email. 
The send_mail function says its body can be in HTML format, but the emails are sent as plain text.
Probably I am missing something.

`    def send_mail(self, subject, body, to_recipients, save_to_sent_items=False):
        """Send a new message on the fly
        :param str subject: The subject of the message.
        :param str body: The body of the message. It can be in HTML or text format`

Thanks again

**Comment by etiennecelery** [comment]
Just figured out how to do it:
include `message.body.contentType = "html"` when calling send_mail.
Thanks

**Comment by ruuttt** [comment]
This worked for me:
```
client = GraphClient(acquire_token_by_username_password)
message = client.me.send_mail(
    subject="Meet for lunch?",
    body="The new cafeteria is open.",
    to_recipients=["fannyd@contoso.onmicrosoft.com", settings.get('user_credentials', "username")]
)
message.body.contentType='html'
message.execute_query()
```
