### ISSUE TITLE
AttachmentCollection.add_file only accepts string for content

### ISSUE THREAD

**Issue by Brandhor** [vgrem/Office365-REST-Python-Client#590]
attachments are usually binary files so I think it would make more sense for add_file to avoid doing content.encode("utf-8") and rather check first if content is bytes or string and then act accordingly

**Comment by xibriz** [comment]
https://github.com/vgrem/Office365-REST-Python-Client/blob/1776c321a43c5a710805f22276c79406bab467cf/office365/outlook/mail/attachments/collection.py#L27

It would be better to just change this to `return_type.content_bytes = content` and let the developer handle this. If you have a PDF file, you can't just use `encode` on the `content`.

The [documentation ](https://learn.microsoft.com/en-us/graph/api/resources/fileattachment?view=graph-rest-1.0) states that it has to be a base64 encoded string, so I think is would be better to accept a base64 encoded string and not let the function try to handle this.

**Comment by cilantro-ditrek** [comment]
I had this issue when attaching PDFs. I solved it by rewriting the `upload_attachment()` function in Message and the `add_file()` function in AttachmentCollection:

```
def add_file(self, name, content, content_type=None):
    """
    Attach a file to message
    :param str name: The name representing the text that is displayed below the icon representing the
         embedded attachment
    :param str content: The contents of the file
    :param str or None content_type: The content type of the attachment.
    """
    from office365.outlook.mail.attachments.file import FileAttachment
    return_type = FileAttachment(self.context)
    return_type.name = name
    return_type.content_bytes = content
    return_type.content_type = content_type
    self.add_child(return_type)
    return self

def upload_attachment(self, file_path, chunk_uploaded=None):
    """
    This approach is used to attach a file if the file size is between 3 MB and 150 MB, otherwise
    if a file that's smaller than 3 MB, then add_file_attachment method is utilized
    :param str file_path:
    :param ()->None chunk_uploaded: Upload action
    """
    max_upload_chunk = 1000000 * 3
    file_size = os.stat(file_path).st_size
    if file_size > max_upload_chunk:
        def _message_loaded():
            self.attachments.resumable_upload(file_path, max_upload_chunk, chunk_uploaded)

        self.ensure_property('id', _message_loaded)
    else:
        with open(file_path, 'rb') as file_object:
            content = base64.b64encode(file_object.read())
        self.attachments.add_file(os.path.basename(file_object.name), content)

Message.upload_attachment = upload_attachment
AttachmentCollection.add_file = add_file
```
