### ISSUE TITLE
Enumerating files broken since version 2.3.14

### ISSUE THREAD

**Issue by florinmihut-intel** [vgrem/Office365-REST-Python-Client#599]
Hi,

It seems that enumerating files is broken since 2.3.14. Works with 2.3.13. 
I tested as well 2.3.15 and 2.3.16. Same result.

This is how I try to list them:
```
        list = self.ctx.web.lists.get_by_title(library_name)
        items = list.items.select(["FileSystemObjectType"]).expand(["File"]).get().execute_query()

```
No change in the code, I run with 2.3.13 and I get from my lib 695 items. I upgrade to anything greater than 2.3.13 and I get only the folders.

Let me know if you need any additional information.

Regards,
Florin

**Comment by vgrem** [comment]
Greetings,

the library nowadays (starting from `2.3.14` version to be precise) honors the _default_ page size settings which for the most endpoints in SharePoint REST API is `100` records (including `listitems` endpoint) and the provided query returns the items for the `100` items of first page.

To return _all_ the items the following options could be considered:


- use the `top(n)` method to override default page size, for example: `items = list.items.select(["FileSystemObjectType"]).expand(["File"]).get().top(5000).execute_query()` where `5000` corresponds to the _default_ list view threshold


or prefer `get_all()` method over `get()` to return _all_ the items, for example: `items = list.items.select(["FileSystemObjectType"]).expand(["File"]).get_all().execute_query()
`
Refer[ read_large_list.py example](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/lists/read_large_list.py) for a more details.

**Comment by florinmihut-intel** [comment]
Thank you, I can confirm it works with get_all() and the progress!
Sorry, I did not realize, is there a place where I could read the release notes if announced?

**Comment by vgrem** [comment]
Good to know! 
In terms of announcements, at the moment the only place is [release section,](https://github.com/vgrem/Office365-REST-Python-Client/releases) for instance for [`2.3.14 `version ](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.14)
