### ISSUE TITLE
How to expose Page to html?

### ISSUE THREAD

**Issue by pilgrim2go** [vgrem/Office365-REST-Python-Client#60]
Hi,

Thanks for this great library.
I have a few questions

+ can we export Sharepoint page to html files?
+ Can we export List item to excel?
+ Can we download document?

My ultimate goal is exporting sharepoint and its associated contents to Google Sites but have no any clue for now.

Thanks,
Van

**Comment by vgrem** [comment]
> can we export Sharepoint page to html files?

> Can we download document?

surely, to download a document or page  use `Web.get_file_by_server_relative_url` method, for example:


```
with open(download_path, "wb") as local_file:
    source_file = ctx.web.get_file_by_server_relative_url("/relative-site-path/library-url/file-url")
    source_file.download(local_file)
    ctx.execute_query()
```

and regarding 

> Can we export List item to excel?  

here is a complete example on how to export list data into csv file:

```
ctx = ClientContext.connect_with_credentials(url, ClientCredential(client_id,client_secret))

# 1.retrieve list data
list_title = "Contacts_Large"
list_to_export = ctx.web.lists.get_by_title(list_title)
list_items = list_to_export.items.top(100)
ctx.load(list_items)
ctx.execute_query()
if len(list_items) == 0:
    print("No data found")

# 2.export to a file
path = os.path.join(tempfile.mkdtemp(), "Contacts.csv")
with open(path, 'w') as fh:
    fields = list_items[0].properties.keys()
    w = csv.DictWriter(fh, fields)
    w.writeheader()
    for item in list_items:
        w.writerow(item.properties)
```
