### ISSUE TITLE
List and Table type columns in a SharePoint List

### ISSUE THREAD

**Issue by sant3e** [vgrem/Office365-REST-Python-Client#606]
I finally made the module work for me as well. I get all the items into a dataframe and exported to an xlsx file.
Question: If some of the columns within my SharePointList are of type List and Table ... is there a way to extract the values I'm interested in?
For example: We have a column named Analyst. This is of type List. Within Power Query, if i click on this List i can select from multiple values (name, email, address, age, so on). I usually do this with an Extract Value (where i select name - for example)
Does this module have anything like this?

**Comment by vgrem** [comment]
_Lookup_ field values are not getting retuned by default, they need to be explicitly requested (namely via [expand query option](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)), for example:

```python
list_tasks = ctx.web.lists.get_by_title("Tasks")
items = (
    list_tasks.items.get()
    .select(
        [
            "*",
            "AssignedTo/Id",
            "AssignedTo/Title",
            "Predecessors/Id",
            "Predecessors/Title",
        ]
    )
    .expand(["AssignedTo", "Predecessors"])
    .top(10)
    .execute_query()
)
```

where 

- `AssignedTo` user field value

- `Predecessors` multi lookup field value



Example: [`get_lookup_field_value.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/listitems/get_lookup_field_value.py)
