### ISSUE TITLE
SSL Connection Error

### ISSUE THREAD

**Issue by PradeepRN1871991** [vgrem/Office365-REST-Python-Client#61]
i am facing the below error while trying through rest api

Error: HTTPSConnectionPool(host='xxxx', port=443)
retries exceeded with url: /_forms/default.aspx?wa=wsignin1.0 (Caused by S
r(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:777)'),))

**Comment by be-rock** [comment]
I read that this lib uses `requests` under the covers.  Can we pass it `verify=False`?

**Comment by pratibhagupta85** [comment]
I am also facing same issue. not able to verify/bypass certificate check in secure corporate environment. Is this issue fixed or is there any workaround for the same?

**Comment by vgrem** [comment]
In the latest release (`v2.1.9`)  `RequestOptions.verify` property is exposed which allows:

> to control whether to verify the server's TLS certificate which accepts:
> 
> - boolean value (defaults to True)
> - string value, which represents path to a CA bundle to use
> 

**Example**

Certification verification could be **disabled** via underlying HTTP request object as demonstrated below:

```
def disable_ssl(request):
    request.verify = False  # Disable certification verification


ctx = ClientContext.connect_with_credentials("https://contoso.sharepoint.com",
                                             UserCredential(username,
                                                            password)

ctx.get_pending_request().beforeExecute += disable_ssl
web = ctx.web
ctx.load(web)
ctx.execute_query()
print(web.properties["Url"])
```

Cross posted on [stackoverflow](https://stackoverflow.com/a/61827728/1375553)

**Comment by mayankbakhru** [comment]
import json
from office365.runtime.auth.user_credential import UserCredential
from office365.runtime.http.request_options import RequestOptions
from office365.sharepoint.client_context import ClientContext
site_url = "https://{your-tenant-prefix}.sharepoint.com"
ctx = ClientContext(site_url).with_credentials(UserCredential("{username}", "{password}"))
request = RequestOptions("{0}/_api/web/".format(site_url))
request.verify = False
response = ctx.execute_request_direct(request)
json = json.loads(response.content)
web_title = json['d']['Title']
print("Web title: {0}".format(web_title))

**Comment by shenoy-beep** [comment]
full_url = "".join([self.service_root_url(), "/", path])
TypeError: sequence item 2: expected str instance, RequestOptions found

**Comment by venkateshnyq550** [comment]
@vgrem 

I'm getting the below error 

ctx = ClientContext.connect_with_credentials('https://xxx.sharepoint.com/sites/Qlik_SE_APP_Mapping',ClientCredential(client_id, client_secret))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'ClientContext' has no attribute 'connect_with_credentials'

**Comment by habitish05** [comment]
I'm getting the following error:

"AttributeError: 'NoneType' object has no attribute 'text'".
