### ISSUE TITLE
How to verify if a file exists? There are any file property for this?

### ISSUE THREAD

**Issue by santospadua** [vgrem/Office365-REST-Python-Client#614]

**Comment by nafets33** [comment]
one solution is to wrap in a try except 

for ex this is how I check if folder exists...same should apply to file

def try_get_folder(ctx, url):
    # url = '/sites/mysite/myfolder'
    try:
        return ctx.web.get_folder_by_server_relative_url(url).get().execute_query()
    except Exception as e:
        if e.response.status_code == 404:
            return None
        else:
            raise ValueError(e.response.text)
