### ISSUE TITLE
issue in renaming the folder in sharepoint

### ISSUE THREAD

**Issue by medro25** [vgrem/Office365-REST-Python-Client#616]
from office365.sharepoint.client_context import ClientContext
from tests import test_user_credentials, test_team_site_url

ctx = ClientContext(test_team_site_url).with_credentials(test_user_credentials)

file_url = "/sites"/Campany Controlled Documents/LTE-BusProc(OBs)/09 - ALU Supporting Processes""
ctx.web.get_folder_by_server_relative_url(file_url).rename("ALU Supporting Processes").execute_query()

I am getting this error
 (None, None, "400 Client Error: Bad Request for url: https://company.sharepoint.com/sites/lte-a/_api/Web/getFolderByServerRelativePath(DecodedUrl='%22Company%20Controlled%20Documents%2FLTE-BusProc(OBs)%2F09%20-%20ALU%20Supporting%20Processes%22%0A')/ListItemAllFields")

**Comment by vgrem** [comment]
Hi there, 
seems it is no longer could be reproduced, at least in a _newer_ versions.

Or it might be a typo in file url:

`/sites"/Campany Controlled Documents/LTE-BusProc(OBs)/09 - ALU Supporting Processes`

where 

- site part is miising 
- extra double quote  is present
