### ISSUE TITLE
Shared link for OrganizationView

### ISSUE THREAD

**Issue by masics** [vgrem/Office365-REST-Python-Client#638]
When using get_sharing_information for files and folders I see a property related to the anonymous share links but not for the OrganizationView type. I also did not find anything in the examples too.
How I can extract shared link? Thank you.

**Comment by vgrem** [comment]
Greetings,

the following example demonstrates how to share a file with `OrganizationView` acess link:


```python
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.sharing.links.kind import SharingLinkKind

ctx = ClientContext(site_url).with_credentials(credentials)
file_url = "/sites/team/Shared Documents/SharePoint User Guide.docx"
target_file = ctx.web.get_file_by_server_relative_url(file_url)
result = target_file.share_link(SharingLinkKind.OrganizationView).execute_query()

```
