### ISSUE TITLE
How to read/write the cells in workbook (Excel file) in Office 365? 

### ISSUE THREAD

**Issue by hsluoyz** [vgrem/Office365-REST-Python-Client#64]
I have successfully authenticated with Office 365 with this library. But I still cannot figure out how to access the content of my Excel file stored in Office 365. Can you shed a little light on how to do it? Thanks.

**Comment by coderrambo007** [comment]
Can you please paste you code ?

**Comment by Destaq** [comment]
@hsluoyz Did you manage to figure out if the library supports this by any chance?

**Comment by vgrem** [comment]
Nowadays the library supports [Microsoft Graph REST API for Excel Services](https://learn.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0).  

###  REST API for Excel Services via SharePoint REST API v2

Example: read table rows


```python
from office365.graph_client import GraphClient
from office365.onedrive.workbooks.tables.rows.row import WorkbookTableRow

client = GraphClient(acquire_token_by_username_password)
worksheets = client.me.drive.root.get_by_path(file_name).workbook.worksheets.get().execute_query()
table = drive_item.workbook.worksheets["Sheet1"].tables["financials"].get().execute_query()
print(table.name)

# read table content
rows = table.rows.get().execute_query()
for r in rows:  # type: WorkbookTableRow
    print(r.values)

```

Example:  [`read_table.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/onedrive/excel/read_table.py)


### SharePoint REST API for Excel Services
  
Status:  [SharePoint REST API in Excel Services](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-rest-api-overview) is **not** supported  via library 

As of  [03/20/2023](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-rest-api-overview):

> The Excel Services REST API for SharePoint Online will no longer be supported for Microsoft 365 accounts from February 28th, 2022 forward. Instead, please use the REST API that’s part of the [Microsoft Graph](http://graph.microsoft.io/docs/api-reference/v1.0/resources/excel)
