### ISSUE TITLE
Version history per item

### ISSUE THREAD

**Issue by sant3e** [vgrem/Office365-REST-Python-Client#646]
I'm trying to get all the information that is stored in the version history of each item (it)
My SP List has several columns among which "Category" (which has several values). In time each id goes through different categories. I need to extract when this change happened (data and type). I've used suggested code:

```
list_title = "my_sp_list"
item_id = 263

file = ctx.web.lists.get_by_title(list_title).get_item_by_id(item_id)
file_with_versions = file.expand(["Versions"])  #retrieve file along with versions
ctx.load(file_with_versions)
ctx.execute_query()
for v in file_with_versions.versions:
    print(v.url)
```
Unfortunately, this print doesn't return anything. It does work with v.version_label (i mean i am getting the "number" allocated to each change), but i need more. Preferably everything... minimum i would like only those changes made to the "category" column (value and date of change). My List has about 3k items. Any suggestion on how to retrieve this information?
I apologize for opening a new issue (was not sure, if adding to one that is already closed, will come to your attention @vgrem )
Thank you.

**Comment by vgrem** [comment]
Hi there, 
thank you for reporting it!

It seems the issue is no longer could be reproduced, at least in version `2.5.1` or above the provided example returns the file versions as expected.
