### ISSUE TITLE
SharePoint Content Library Size

### ISSUE THREAD

**Issue by dvwyngaa** [vgrem/Office365-REST-Python-Client#647]
Hi,

How would I check for the content library size, the storage it has used?

Regards,

Dawid

**Comment by vgrem** [comment]
Greetings,

the library size could be determined via [`Folder.StorageMetrics` property](https://learn.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-csomspt/a9e296ef-3065-418b-82c0-0ddbac395f3f):  


```python
ctx = ClientContext(site_url).with_credentials(client_credentials)

lib = ctx.web.lists.get_by_title("Documents").root_folder.expand(["StorageMetrics"]).get().execute_query()
print("List size (in bytes): {0}".format(lib.storage_metrics.total_size))

```


 where [`TotalSize` property](https://learn.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-csomspt/fb1c205e-0bd9-4109-a6a1-9f2d97780e41) represents:

> Aggregate of total sizes in bytes for all items under the corresponding folder and its sub-folders. Total size for a file/folder includes stream, version, and metadata sizes.
