### ISSUE TITLE
401 Client Error: Unauthorized for url: https:/[tenant]sharepoint.com/sites/[my-site]/_api/Web

### ISSUE THREAD

**Issue by Divjyot** [vgrem/Office365-REST-Python-Client#648]
I followed Sharepoint App Registration guide [here](https://spblog.net/post/2018/08/24/SharePoint-lifehacks-create-SharePoint-app-registration-with-client-secret-which-never-expires), mixing it with Microsoft Guide for Sharepoint-Only [here](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs).

I can check and see the policies setup, with access granted.

<img width="896" alt="Screenshot 2023-02-10 at 4 18 09 pm" src="https://user-images.githubusercontent.com/14040664/218017294-7e6060c5-be2a-47c7-8c2f-ac2f3ab38def.png">

However, after running following code to authenticate using this library,

```
ctx_auth = AuthenticationContext(site_url)
if ctx_auth.acquire_token_for_app(client_id=app_principal['client_id'], client_secret=app_principal['client_secret']):
    ctx = ClientContext(site_url).with_credentials(ClientCredential(app_principal['client_id'], app_principal['client_secret']))
    web = ctx.web
    ctx.load(web)
    ctx.execute_query()
    print('Authenticated into sharepoint app for: ',web.properties['Title'])
else:
    print(ctx_auth.get_last_error())
```

I am getting `401 Client Error: Unauthorized for url: https:/[tenant]sharepoint.com/sites/[my-site]/_api/Web`

Traceback:

```

Traceback (most recent call last)



[/.venv/lib/python3.9/site-packages/office365/runtime/client_request.py:58]
(office365/runtime/client_request.py:58), in ClientRequest.execute_query(self, query)
     57 response = self.execute_request_direct(request)
---> 58 response.raise_for_status()
     59 self.process_response(response, query)

[/.venv/lib/python3.9/site-packages/requests/models.py:1021]
(requests/models.py:1021), in Response.raise_for_status(self)
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 401 Client Error: Unauthorized for url: https://[tenant].sharepoint.com/sites/[my-site]/_api/Web

During handling of the above exception, another exception occurred:

ClientRequestException                    Traceback (most recent call last)
Cell In[6], line 6
      4     web = ctx.web
      5     ctx.load(web)
----> 6     ctx.execute_query()
      7     print('Authenticated into sharepoint app for: ',web.properties['Title'])
      8 else:

[/.venv/lib/python3.9/site-packages/office365/runtime/client_runtime_context.py:162]
(office365/runtime/client_runtime_context.py:162), in ClientRuntimeContext.execute_query(self)
    160 while self.has_pending_request:
...
     60     self.afterExecute.notify(response)
     61 except HTTPError as e:
---> 62     raise ClientRequestException(*e.args, response=e.response)

ClientRequestException: (None, None, '401 Client Error: Unauthorized for url: https://[tenant].sharepoint.com/sites/[my-site]/_api/Web')
```

Side Ques. I noticed that there is `_api/Web` trailing the site url which is appended by the Office365-package ... Is it of concern in regards to getting Unauthorised Access Error?

**Comment by vgrem** [comment]
Greetings,

since the provided screenshot corresponds to application permissions granted via Azure AD, you would need to _utilize certificate_ credentials flow instead of _client credentials_  ([official documentation](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread))    

> Since SharePoint Add-ins uses the [low-trust authorization system](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization), client secrets flow trust is **not** supported, certificate app only trust needs to be utilized instead:


 ```python
cert_credentials = {
        'tenant': tenant,
        'client_id': '--AAD App Client Id--',
        'thumbprint': "--thumbprint--",
        'cert_path': './selfsigncert.pem'
    }

ctx = ClientContext(site_url).with_client_certificate(**cert_credentials)
```


### Option 2

Or permissions could be granted via ACS as explained [here](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs#setting-up-an-app-only-principal-with-tenant-permissions)

Grant page url: `https:/[tenant]sharepoint.com/sites/[my-site]/_layouts/15/appregnew.aspx`

Permissions request:

```
<AppPermissionRequests AllowAppOnlyPolicy="true">
     <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
</AppPermissionRequests>

```

Once granted, _client credentials flow_ should work as expected:  

```python
client_credentials = ClientCredential('client_id', 'client_secret')
ctx = ClientContext(site_url).with_credentials(client_credentials)
```

**Comment by Divjyot** [comment]
> Greetings,
> 
> since the provided screenshot corresponds to application permissions granted via Azure AD, you would need to _utilize certificate_ credentials flow instead of _client credentials_ ([official documentation](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread))
> 
> > Since SharePoint Add-ins uses the [low-trust authorization system](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization), client secrets flow trust is **not** supported, certificate app only trust needs to be utilized instead:
> 
> ```python
> cert_credentials = {
>        'tenant': tenant,
>        'client_id': '--AAD App Client Id--',
>        'thumbprint': "--thumbprint--",
>        'cert_path': './selfsigncert.pem'
>    }
> 
> ctx = ClientContext(site_url).with_client_certificate(**cert_credentials)
> ```
> 
> ### Option 2
> Or permissions could be granted via ACS as explained [here](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs#setting-up-an-app-only-principal-with-tenant-permissions)
> 
> Grant page url: `https:/[tenant]sharepoint.com/sites/[my-site]/_layouts/15/appregnew.aspx`
> 
> Permissions request:
> 
> ```
> <AppPermissionRequests AllowAppOnlyPolicy="true">
>      <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
> </AppPermissionRequests>
> ```
> 
> Once granted, _client credentials flow_ should work as expected:
> 
> ```python
> client_credentials = ClientCredential('client_id', 'client_secret')
> ctx = ClientContext(site_url).with_credentials(client_credentials)
> ```

Thanks @vgrem , Can you please elaborate on Option 1,

1. Where can I find 'thumbprint' ? 
2. Following the MS Docs, it generate certificate `.cer` file and a `.pfx` file, there is no `.pem` file. Where do that come from ?
_Uploaded `.cer` file to Azure portal acc to MS Docs._

**Comment by Divjyot** [comment]
Found similar issue here https://github.com/vgrem/Office365-REST-Python-Client/issues/540#issuecomment-1193501245

That converts .pfx file to .pem
