### ISSUE TITLE
get_items() of a view

### ISSUE THREAD

**Issue by mteesphawk** [vgrem/Office365-REST-Python-Client#65]
Is it possible to iterate through the items in a view like you can with a list ? 

Thanks

**Comment by vgrem** [comment]
Greetings!

The point is SharePoint APIs (CSOM/REST) does not support manipulating list items _directly_ via `View `object, instead _items of a view_ could be retrieved via list  [follow this answer ](https://stackoverflow.com/a/26891086/1375553) for a more details.


Having said that, the following example demonstrates how to retrieve list items of a view:

```
    list_object = ctx.web.lists.get_by_title(list_title)
    # 1.get View query
    view = list_object.views.get_by_title(view_title)
    ctx.load(view, "ViewQuery")
    ctx.execute_query()

    # 2.get items for View query
    qry = CamlQuery()
    qry.ViewXml = "<View><Where>{0}</Where></View>".format(view.properties["ViewQuery"])
    items = list_object.get_items(qry)
    ctx.load(items)
    ctx.execute_query()

    for item in items:
        print("Item title: {0}".format(item.properties["Title"]))
```



> Note: CAML queries support was introduced in [version 2.1.1](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.1.1) so please make sure to get the latest version.
