### ISSUE TITLE
Support for front_insert in request removed in current version

### ISSUE THREAD

**Issue by zoidw1** [vgrem/Office365-REST-Python-Client#657]
Pull request #430 has been negated from version 2.3.13 onwards.

front_insert method in EventHandler class was removed between these versions.
Issue as described by @juguerre is still present :
"When that internal event executes tries to make a request that fails because the set_proxy event is not processed a that moment. When I managed to put set_proxy "first", the internal event had no problem to make requests work."

I propose reintroducing the front_insert method from this PR.

**Comment by vgrem** [comment]
Greetings,

thank you for reporting it and providing the details, it appears to be related with #682 issue and has been addresed in [2.4.3 version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.4.3) version.
