### ISSUE TITLE
SharePoint document library managed metadata column value update/edit failure.

### ISSUE THREAD

**Issue by kamrunsumi** [vgrem/Office365-REST-Python-Client#658]
I want to update SharePoint online document library managed metadata column which has drop down menus. I want to select/update the existing value with the help of python. I tried the code below but did not update the column value. What am I missing here?

from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.taxonomy.field_value import TaxonomyFieldValue, TaxonomyFieldValueCollection
from office365.sharepoint.taxonomy.item import TaxonomyItem
from office365.runtime.auth.user_credential import UserCredential
from getpass import getpass

### Specify the SharePoint Online site URL
site_url = ""
username = getpass("Please enter your company email address:")
password = getpass("Please enter your password:")

### Create a client context for SharePoint Online
ctx = ClientContext(site_url).with_credentials(UserCredential(username, password))

### relative URL of the file
relative_url = ""

### Get the file from SharePoint Online
file = ctx.web.get_file_by_server_relative_path(relative_url).expand(["listItemAllFields"]).get().execute_query()

### Get the value of the column
current_value = file.listItemAllFields.get_property("R") # "R" is the internal name of the column in SharePoint.

new_dict = {"label":  "", "term": "", "WssId": 1}

### Create a new TaxonomyFieldValue object with the updated value
tax_field_value = TaxonomyFieldValue()
tax_field_value.Label = new_dict["label"]
tax_field_value.TermGuid = new_dict["term"]
tax_field_value.WssId = 1

### Update the "column
file.listItemAllFields.set_property("R", tax_field_value)
file.listItemAllFields.update().execute_query()
ctx.execute_query()

### Show the updated value of the column
updated_value = file.listItemAllFields.get_property("R")
print("The updated value of the column is:", updated_value.Label + '|' + updated_value.TermGuid + '|' + str(updated_value.WssId))
print("The previous value of the column is:", current_value["Label"] + '|' + current_value["TermGuid"] + '|' + str(current_value["WssId"]))

**Comment by kamrunsumi** [comment]
Is there any solution for that?

**Comment by vgrem** [comment]
Seems the issue is no longer could be reproduced, here is an example on how to set a single and multi taxonomy field values in a list item:

```python
custom_list = ctx.web.lists.get_by_title(list_title)

item = custom_list.add_item(
    {
        "Title": "New item",
        "Country": TaxonomyFieldValue(
            "Sweden", "f9a6dae9-633c-474b-b35e-b235cf2b9e73"
        ),
        "Countries": TaxonomyFieldValueCollection(
            [TaxonomyFieldValue("Sweden", "f9a6dae9-633c-474b-b35e-b235cf2b9e73")]
        ),
    }
).execute_query()
```
 where

- `Sweden` - term label 

- `f9a6dae9-633c-474b-b35e-b235cf2b9e73` - term guid
