### ISSUE TITLE
Do you support authentication with on premise IdP?  If yes, how to use?

### ISSUE THREAD

**Issue by hsipingw** [vgrem/Office365-REST-Python-Client#66]
Meaning, if the authentication takes route 4a in the article below.

https://support.office.com/en-us/article/SharePoint-Online-authentication-77965e8d-48ad-47bd-a656-57f17d6d1cc7

Thank you very much,

**Comment by vgrem** [comment]
The support for [Office 365 Single Sign-On for ADFS](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/set-up-adfs-for-single-sign-on) has been introduced in version` 2.1.7`, meaning authentication in Office 365 with ADFS configured should we working as expected now.

**Note**

> It is assumed Multi-factor authentication for a user is disabled
