### ISSUE TITLE
SharePoint: Hashtag in filename causes file content to be None

### ISSUE THREAD

**Issue by jmtts** [vgrem/Office365-REST-Python-Client#660]
Great Tool!

Ot works almost perfectly for me - I just ran into a simple problem / bug.

I seem unable to download files from sharepoint that contain '#' in their filename.

Here my code

```python
ctx = ClientContext(site_url).with_credentials(user_credentials)

def walk_directory(path):

    # enter the directory
    root = ctx.web.get_folder_by_server_relative_path(path)
    ctx.load(root).execute_query()

    # get the files
    files = root.files
    self.ctx.load(files).execute_query()
    if files is None:
        return

    # walk through the directory
    for c_file in files:
        path = c_file.properties.get("ServerRelativeUrl")
        if path is None:
            continue
        content = File.open_binary(self.ctx, path).content
        yield path, content
```

Whenever there is a '#' in the filename the content is empty. 

I was already playing around with urlencode - but that did not seem to solve the problem. 
Any ideas?

**Comment by dkuska** [comment]
It ain't pretty but in case everything fails, you can go through `RequestOptions` and manually encode your `#` and `%`

`path = path.replace('#', '%23')`
`path = path.replace('%', '%25')`
`request = RequestOptions(f"{base_url}/_api/Web/GetFileByServerRelativePath(decodedurl={path})/$value"`
`content = ctx.execute_request_direct(request).content`

Ressources: https://github.com/SharePoint/sp-dev-docs/issues/6673#issuecomment-772828486

**Comment by jmtts** [comment]
Thank you!

Worked for me with minor modifications:

```python

  path = path.replace('#', '%23')
  path = path.replace('%', '%25')
  url = f"{site_url}/_api/Web/GetFileByServerRelativePath(decodedurl='{path}')/$value"
  request = RequestOptions(url)
  response = ctx.pending_request().execute_request_direct(request)
  content = response.content

```
