### ISSUE TITLE
Sharepoint list - get_items extra colums

### ISSUE THREAD

**Issue by FBrusquetti** [vgrem/Office365-REST-Python-Client#662]
Hi, 
Im trying to get a shaerpoint list data with the following code:
 
my_sharepoint_list= ctx.web.lists.get_by_title('Sharepoint title')
l_items = my_sharepoint_list.get_items()
ctx.load(l_items)
ctx.execute_query()
print(l_items[0].properties)

But i see some kind of extra columns comming, for example:
FileSystemObjectType
Id
ServerRedirectedEmbedUrl
ComplianceAssetId

Those columns are not visible in the sharepoint list, how can i get only the visible ones?

**Comment by Danxx26hub** [comment]
Like any other database SharePoint uses that “Id” column to identify the each record/row, you will need that if you want your code to update the data. As far as getting only the columns you want, you can use a loop and then get the ‘column’ names using dictionary style code

**Comment by vgrem** [comment]
Greetings,

given the provided example, it could be adjusted like this:

```python
lib = ctx.web.lists.get_by_title(list_title)
items = lib.items
ctx.load(items, ["FileSystemObjectType", "ServerRedirectedEmbedUrl", "Id", "ComplianceAssetId"])
ctx.execute_query()

```

to retrieve the column values.
