### ISSUE TITLE
search weird result (?)

### ISSUE THREAD

**Issue by domdinicola** [vgrem/Office365-REST-Python-Client#666]
Hi @vgrem ,

not sure if there's a regression or something I'm missing with the latest upgrade...

![image](https://user-images.githubusercontent.com/2621572/230244392-cdbf909d-bce6-4fd5-917e-9337d7d4bfe3.png)

after the first query... relevant_results.Table.Rows retrieves wrong results but the relevant_results.TotalRows is correct....

        print(relevant_results.TotalRows) -->2
        print(len(relevant_results.Table.Rows)) --> 4
        
 not sure what is wrong here... i'm getting crazy 🈂️ 
 
 then if I stop the server and execute the query which was giving wrong results... it works fine

it seems it's adding the results to the query :/

**Comment by domdinicola** [comment]
I tried also to send a brand new context but seems the objects are summing up.

**Comment by vgrem** [comment]
@domdinicola, thanks for the insight and catching it,  will try to have a look into on weekend and get back to you

**Comment by domdinicola** [comment]
@vgrem any updates on this?

**Comment by vgrem** [comment]
@domdinicola, [per official](https://learn.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-qssws/4e1dfcea-817b-405c-8018-0fb4e0cd11de) documentation:

`TotalRows` - returns the  **total** number of results that match the conditions given in the search query 


while `relevant_results.Table.Rows` is expected to contain the the actual amount of _returned_ rows which might be affected by  `row_limit` property.

Meaning `relevant_results.TotalRows` is expected to be greater or equal to  `len(relevant_results.Table.Rows)`

**Comment by domdinicola** [comment]
@vgrem thanks for replying... my case is the opposite 
<img width="816" alt="Screen Shot 2023-04-20 at 2 19 38 PM" src="https://user-images.githubusercontent.com/2621572/233363926-fc5ae61b-052c-45ca-9ce6-4d39933d5ff5.png">
![Screen Shot 2023-04-20 at 12 48 13 PM](https://user-images.githubusercontent.com/2621572/233363928-9f2d0338-750d-4ea1-bb5c-a31ee6259211.png)

**Comment by vgrem** [comment]
@domdinicola, it appears to be a bug, namely `ClientResult` (return type)  was not resetting value between calls when passing to `execute_query` method. Thank you for catching and reporting it!

**Comment by vgrem** [comment]
Has been resolved in [`2.4.1` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.4.1)

**Comment by domdinicola** [comment]
Great!

Appreciated!

Il giorno sab 22 apr 2023 alle ore 10:45 Vadim Gremyachev <
***@***.***> ha scritto:
