### ISSUE TITLE
Updating a property on a SitePage

### ISSUE THREAD

**Issue by Jeremy-Code-F** [vgrem/Office365-REST-Python-Client#673]
Hi,

I'm trying to use this library to create a SitePage and then set some properties on the site page.

Specifically I am trying to set 'OriginalSourceUrl'

![image](https://user-images.githubusercontent.com/45114285/233401033-9bf2c794-f9cb-4972-a70d-f6684e42b839.png)

I'm not sure how to go about actually setting the property

I assumed that if I just use ```set_property``` with ```persist_changes=True``` it would both set the property and save the changes to SPOL, that doesn't seem to be the case though.

Looking at the page after running this

```
pages[12].set_property('OriginalSourceUrl', my_new_link, persist_changes=True)
pages[12].execute_query()
```

It is set correctly locally, but when I inspect the page on SPOL afterwards it looks like the change is not persisted. 
Am I missing some step to save the changes?

Thanks!

**Comment by dkuska** [comment]
How about if you add `.update()` before the `.execute_query()` like this:
`pages[12].set_property('OriginalSourceUrl', my_new_link, persist_changes=True).update().execute_query()` ?

**Comment by vgrem** [comment]
Closing the issue as considered resolved
