### ISSUE TITLE
Accessing FileObject Properties

### ISSUE THREAD

**Issue by darshpfz97** [vgrem/Office365-REST-Python-Client#676]
I am trying to check the properties a file on sharepoint to find if its locked or not

```
sp_context_file: SharepointFile = (
            self._context.web.get_file_by_server_relative_url(
                sharepoint_file_path
            ).execute_query()
        )

        print(file_name, sp_context_file, sp_context_file.properties)

```

The file object has no properties in them, returns an empty {}.  am I accessing it the wrong way?

**Comment by dkuska** [comment]
Try adding `.get()` before `.execute_query()`

**Comment by darshpfz97** [comment]
> Try adding `.get()` before `.execute_query()`
self._context.web.get_file_by_server_relative_url(
            sharepoint_file_path
        ).get().execute_query()
AttributeError: 'File' object has no attribute 'get'

**Comment by dkuska** [comment]
I was just following [this example](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/files/get_properties.py).

Your question does not contain enough details to further debug this. How is the ClientContext created and authenticated? What is the `SharepointFile` class you're referencing? Could you post a minimal code snippet to reproduce this error?

**Comment by darshpfz97** [comment]
Thanks for the response,

I am trying to see if a file is locked before updating it, multi.

I am actually authenticating using user credentials.

```
ctx_auth.acquire_token_for_user(self.user_name, self._password)
ctx: ClientContext = ClientContext(self.base_site_url, ctx_auth)

```
and I am using the ClientContext to perform 

```
        sp_context_file: SharepointFile = self._context.web.get_file_by_server_relative_url(
            sharepoint_file_path
        ).execute_query()
```

could it be due to that I am using user credentials unlike client credentials used in the example?

**Comment by dkuska** [comment]
Yes, that indeed could be an issue!
Organizations are able to disable authentication with user credentials and in these cases no exceptions are thrown.
I recommend checking back with the people administrating the SharePoint in question if that is the case.

**Comment by darshpfz97** [comment]
Okay, thank you :)
