### ISSUE TITLE
Unable to execute the Sharepoint Flow example

### ISSUE THREAD

**Issue by khodges42** [vgrem/Office365-REST-Python-Client#68]
Getting the following error: AttributeError: 'AuthenticationContext' object has no attribute 'acquire_token_for_app'

**Comment by jediknight31** [comment]
Same here. Don't see the acs_token_provider.py file in the installed package

**Comment by khodges42** [comment]
I had luck with cloning this repo, the pip version, as of the time this was posted, was behind and didn't contain the required code.
