### ISSUE TITLE
Disable SSL Verification not work on some function

### ISSUE THREAD

**Issue by AlanNggg** [vgrem/Office365-REST-Python-Client#682]
Disable SSL Verification not work on download function
```
def disable_ssl(request):
    request.verify = False  # Disable certification verification

host = 'https://abc.com'
site_url = f'{host}/sites/sections'
username = 'root'
password = 'password'
ctx = ClientContext(site_url).with_user_credentials(username, password, allow_ntlm=True)
ctx.pending_request().beforeExecute += disable_ssl

file_url = "/sites/team/Shared Documents/!2022/Financial Sample.xlsx"
download_path = os.path.join(tempfile.mkdtemp(), os.path.basename(file_url))
with open(download_path, "wb") as local_file:
    file = ctx.web.get_file_by_server_relative_url(file_url).download(local_file).execute_query()

```
<img width="508" alt="Screenshot 2023-05-18 at 11 34 26 AM" src="https://github.com/vgrem/Office365-REST-Python-Client/assets/41237850/d2c6ab18-c1a9-4bb2-b4c1-33029934bec9">

The bug is in ClientContext in client_context.py. 
```
    def _get_context_web_information(self):
        """Returns an ContextWebInformation object that specifies metadata about the site"""
        client = ODataRequest(JsonLightFormat())
        client.beforeExecute += self._authenticate_request
        request = RequestOptions("{0}/contextInfo".format(self.service_root_url()))
        request.method = HttpMethod.Post
        response = client.execute_request_direct(request)
        json_format = JsonLightFormat()
        json_format.function = "GetContextWebInformation"
        return_value = ContextWebInformation()
        client.map_json(response.json(), return_value, json_format)
        return return_value
```
The function here create new ODataRequest, but not use the ODataRequest returned by pending_request(). Therefore, adding event handler to pending_request().beforeExecute not work, such as ctx.pending_request().beforeExecute += disable_ssl

**Comment by vgrem** [comment]
Thank you for catching this error and reporting it, indeed it was the root cause.

In the [`2.4.3` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.4.3) this issue has been addressed to preserve event handlers from loosing when `_get_context_web_information` method called.
