### ISSUE TITLE
im trying to find a way to get the folder creators name in sharepoint

### ISSUE THREAD

**Issue by Lukawyn** [vgrem/Office365-REST-Python-Client#692]
so far ive tried this but it seems to return 'none' all the time or <office365.sharepoint.principal.users.user.User object at 0x000001F84DEA5CD0> which i suppose is a user object of somekind 

class SharePoint:
   def get_file_properties_from_folder(self, folder_name):
        files_list = self._get_files_list(folder_name)
        properties_list = []
        for file in files_list:
            file_dict = {
                'file_id': file.unique_id,
                'creator': file.author,
            }
            properties_list.append(file_dict)
            file_dict = {}
        return properties_list

files_properties = SharePoint().get_file_properties_from_folder(folder)
print('File count:', len(files_properties))
for file in files_properties:
    print(file)

i know this is for a file but im trying to see if i can get the creator of a file first and then of a folder any help would be appreciated

**Comment by Lukawyn** [comment]
ctx = ClientContext(sharesite).with_credentials(UserCredential(usr,passw))

version = ctx.web.get_file_by_server_relative_path(file_url).versions.get_by_id(1).expand(["CreatedBy"]).get().execute_query()
print(version.created_by.login_name)

this also always seems to return none

**Comment by vgrem** [comment]
The following example demonstrates how to retrieve `Folder` system metadata (namely `Author`, `Editor`) via ListItem endpoint: 


```python
list_title = "Documents"
folder_path = "Archive"  # folder relative path or name
folder_item = (
    ctx.web.lists.get_by_title(list_title)
    .get_item_by_url(folder_path)
    .select(["Author/Id", "Author/Title", "Author/Name", "Editor/Id", "Editor/Title", "Editor/Name"])
    .expand(["Author", "Editor"])
    .get()
    .execute_query()
)
```
