### ISSUE TITLE
Using app password

### ISSUE THREAD

**Issue by cj13579** [vgrem/Office365-REST-Python-Client#7]
I love this client and have been using it very successfully for a while now. However, my organization has just enabled multi-factor authentication for Office 365 which has broken my application - 👎. 

Do you have any examples you can share of using app passwords or other techniques for accessing O365 when multi-factor authentication is enabled?

Thanks!

**Comment by vgrem** [comment]
Hi, first of all, glad to hear that you find this client useful.
Regarding multi-factor authentication, let me investigate it, will get back to you shortly.

**Comment by cj13579** [comment]
Hey, I think I have got this working fine using app passwords. I was doing some extra encoding in my application which I had forgotten about. No changes needed to this code! I'll close this issue.
