### ISSUE TITLE
Cannot updated multiple multivalued Mananged meta data columns 

### ISSUE THREAD

**Issue by prathamPote** [vgrem/Office365-REST-Python-Client#705]
I'm Using the follwoing code to update these fields and some Columns are updated whereas others aren't.

       var= TaxonomyFieldValue(Filters['Document Type'],Tax['Document Type'][Filters['Document Type']])
        item_to_update.set_property('Document_x0020_Type',TaxonomyFieldValueCollection([var])).update().execute_query()

        var= TaxonomyFieldValue(Filters['Region'],Tax['Region'][Filters['Region']])
        item_to_update.set_property('Region',TaxonomyFieldValueCollection([var])).update().execute_query()

         item_to_update.set_property('Content_x0020_Accessibility',TaxonomyFieldValueCollection([ 
                  TaxonomyFieldValue('Employee',Tax['Content Accessibility']['Employee']),                  
                   TaxonomyFieldValue('Partner',Tax['Content Accessibility']['Partner'])
              ])).update().execute_query()

 Similarly have a total of 7 columns and only 3 of them get updated.

The code is the same for the rest of these columns and if you re arrange the order in which they are written, different columns get updated everytime.

**Comment by vgrem** [comment]
Thanks for reporting it, in the latest version (`2.4.3`) a few bugs including setting taxonomy field values have been resolved, here is an example for setting multiple taxonomy field value:   

```python
item.set_property("--field name--",
                  TaxonomyFieldValueCollection([TaxonomyFieldValue("--term label--", "--term guid--")]))
item.update().execute_query()
```


Example: [`update_field_value.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/taxonomy/update_field_value.py)
