### ISSUE TITLE
How to download and upload from / to folder that are shared with me?

### ISSUE THREAD

**Issue by HenDGS** [vgrem/Office365-REST-Python-Client#710]
I started using Office365-REST-Python-Client, and it's working good with my personal files. But I need to access important files from the company that are in shared folders. Even tho they appear as shortcuts in Documents or Shared Documents, I get this error when trying to access files in them:

(<class 'office365.runtime.client_request_exception.ClientRequestException'>, ClientRequestException('-2130575338, Microsoft.SharePoint.SPException', 'The file XXX does not exist.', "404 Client Error: Not Found for url: XXX')?$select=ServerRelativePath,Id"), <traceback object at 0x00000246FA0BB040>).

**Comment by vgrem** [comment]
If the folder has been shared, it could be retrieved, for instance via` Web.get_folder_by_guest_url(guest_url)` method, where 
`guest_url` is _the tokenized sharing link URL for the folder_

Refer [`share_folder.py` example](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/sharing/share_folder.py) for a details.
