### ISSUE TITLE
Documentation Update Required 

### ISSUE THREAD

**Issue by HHabit** [vgrem/Office365-REST-Python-Client#712]
Documentation listed at the following link requires update: https://github.com/vgrem/Office365-REST-Python-Client/wiki/How-to-connect-to-SharePoint-Online-and-and-SharePoint-2013-2016-2019-on-premises--with-app-principal

Line 5 - from office365.runtime.auth.Client_Credential import ClientCredential - results in the following error with latest version (2.4.2):

ModuleNotFoundError: No module named 'office365.runtime.auth.Client_Credential'

I would like to fix this issue with a pull-request specifying the version and correct resolution.

**Comment by HHabit** [comment]
Is your wiki produced from code? If so, would like to make a pull request to update

**Comment by SnakeHughes** [comment]
The same question. The code worked fine when I tested it, but when I created a dag for the schedule in airflow, aiflow can't find the module. I checked the python path but puth is correct.

**Comment by vgrem** [comment]
Thanks for catching this typo, it appears this particular issue has already been fixed recently. Anyway, wiki could be edited by any account on GitHub.com and you are welcome to contribute!
