### ISSUE TITLE
Support Device code flow authentication

### ISSUE THREAD

**Issue by DanielMrowca** [vgrem/Office365-REST-Python-Client#713]
Is there a way to authenticate access to the SharePoint API using the `device flow code`?
I want to use this library as an Azure function on behalf of an authenticated user and there is no way to use `interactive` authentication.

**Comment by vgrem** [comment]
Greetings,

the support for [device code flow auth](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#device-code) has been introduced in [2.4.3 version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.4.3), here is an example:

```python
from office365.sharepoint.client_context import ClientContext

tenant = "contoso.onmicrosoft.com"

ctx = ClientContext(site_url).with_device_flow(tenant, client_id)
me = ctx.web.current_user.get().execute_query()
print(me.login_name)
```
