### ISSUE TITLE
Getting ValueError: Acquire app-only access token failed.

### ISSUE THREAD

**Issue by shivkatira** [vgrem/Office365-REST-Python-Client#718]
Hello @vgrem , 
I am getting ValueError: Acquire app-only access token failed. in secured corporate environment. Below is my code:

```
from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext

client_credentials = ClientCredential(<client_id>, <client_secret>)
ctx = ClientContext(<url>).with_credentials(client_credentials)
web = ctx.web
ctx.load(web)
ctx.execute_query()
print("Web title: {0}".format(web.properties['Title']))
```

**Comment by vgrem** [comment]
Hey,

perhaps ACS app-only access token is _disabled_ in your tenant ([docs](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs))?

Have a look [this example](https://github.com/vgrem/Office365-REST-Python-Client/blob/2b603f5c9643ece12b40cfcaf1e4005cbca141e1/examples/sharepoint/tenant/enable_app_only_authentication.py) which demonstrates how to determine if it is disabled and enable it (requires SharePoint admin role permissions). 

Alternative option (recommended) to switch to [ Azure AD app-only model], refer [this wiki](https://github.com/vgrem/Office365-REST-Python-Client/wiki/How-to-connect-to-SharePoint-Online-with-certificate-credentials) for a more details

**Comment by vgrem** [comment]
Closed due to inactivity
