### ISSUE TITLE
Update packages on pypi on releases 

### ISSUE THREAD

**Issue by JesperKrogh** [vgrem/Office365-REST-Python-Client#721]
Hi. I was just bitten by the fact that the most recent package on pypi is 2.2.0 (3 years old). Is there good reasons those are not in sync with releases on github?

**Comment by vgrem** [comment]
Greetings,

according to  [package index url](https://pypi.org/project/Office365-REST-Python-Client/ https://pypi.org/project/Office365-REST-Python-Client/) it appears to be in sync with the latest version, which is `2.4.3` atm.  Perhaps this old version (which is indeed way too outdated) refers to some alternative url?

**Comment by JesperKrogh** [comment]
It is this one: 
https://pypi.org/project/office365-rest-client/

Guess that should just be deleted to avoid confusion then?

**Comment by vgrem** [comment]
Outdated and alternative project [office365-rest-client/](https://pypi.org/project/office365-rest-client/)  has been (finally) deleted
