### ISSUE TITLE
404 error with get_file_by_server_relative_path in version 2.4.2 onwards

### ISSUE THREAD

**Issue by dslemusp** [vgrem/Office365-REST-Python-Client#722]
It seems there is a regression in version 2.4.3 using the `get_file_by_server_relative_path`

using 

```python
relative_path = "/sites/mysite/folder/filename.ext"
ctx = ClientContext(site_url).with_credentials(credentials)
file = ctx.web.get_file_by_server_relative_path(relative_path).get().execute_query()
```

with 2.4.1 gave no problems and updating to 2.4.3 get the error HTTPError: 404 Client Error: Resource Not Found for url... It seems the url that is being requested is wrongly parsed (now including twice the `"/sites/mysite"`), which I think is related to changes introduced in [2.4.2](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.4.2)

**Comment by helingai** [comment]
Can confirm. Downgrading to 2.4.1 fixes this issue.

**Comment by vgrem** [comment]
Thank you for catching and reporting this bug, it has been addressed in a new version [`2.4.4`](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.4.4)

**Comment by helingai** [comment]
I can confirm it's fixed. Thanks very much!

**Comment by dslemusp** [comment]
thx! guys!
