### ISSUE TITLE
InvalidClientQueryException for add_dependent_lookup_field (sharepoint.fields.collection)

### ISSUE THREAD

**Issue by pclasen-eb** [vgrem/Office365-REST-Python-Client#723]
Hi,
After successfully adding a LookupField to a SharePoint List using **add_lookup_field**, I would also like to display another column from that lookup list using **add_dependent_lookup_field** in version 2.4.3.

However, with **add_dependent_lookup_field**, I get **ClientRequestException**
'-1, Microsoft.SharePoint.Client.InvalidClientQueryException', ... 

Essentially, the error says that the parameter "primaryLookupField" does not exist in "AddDependentLookupField".

Did the parameter names change?
https://learn.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj245299(v=office.15)

When changing the keys in the parameter dictionary (as shown below) in add_dependent_lookup_field (office365.sharepoint.fields.collection.py > FieldCollection), it works:
```        
parameters = {
"displayName": display_name,
#"primaryLookupField": primary_lookup_field,
"primaryLookupFieldId": primary_lookup_field,
#"lookupField": lookup_field
"showField": lookup_field
}
```

With some hints what else to consider (e.g. changing argument names according to parameters), I might be able to help creating a pull request.

Cheers!

**Comment by vgrem** [comment]
Greetings,

thank you for catching this bug and providing the detailed analysis!

The pull request is more than welcomed for the proposed changes (and preferably also changing argument name from `lookup_field` into `show_field `).

**Comment by vgrem** [comment]
Thank you for PR! It has been released with a [new version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.4.4).
