### ISSUE TITLE
Error Uploading File to SharePoint List Item

### ISSUE THREAD

**Issue by SatchinM** [vgrem/Office365-REST-Python-Client#729]
Hi @vgrem!

Firstly, a big thank you for this package. It is absolutely awesome. 
I am able to do some much, simple automation, with the SharePoint options.

On a new piece of work I am busy with, is adding an attachment to a SharePoint list item and 
I am experiencing an error when trying to upload (attach) a file to a SharePoint list item.

I am using: Office365-REST-Python-Client Version 2.4.3
In an Azure Databricks Environment.

On the execution of this command:
task_item.attachment_files.add(attachment_file_information).execute_query()

#################################################################################################

AttributeError: 'FileCreationInformation' object has no attribute 'filename'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File <command-4486711600691265>:27
     23     file_content = content_file.read()
     24 attachment_file_information = FileCreationInformation(os.path.basename(attachment_path), file_content)
---> 27 task_item.attachment_files.add(attachment_file_information).execute_query()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/office365/sharepoint/attachments/collection.py:32, in AttachmentCollection.add(self, attachment_file_information)
     27 return_type = Attachment(self.context)
     28 self.add_child(return_type)
     29 qry = ServiceOperationQuery(self,
     30                             "add",
     31                             {
---> 32                                 "filename": attachment_file_information.filename,
     33                             },
     34                             attachment_file_information.content,
     35                             None,
     36                             return_type)
     37 self.context.add_query(qry)
     38 return return_type

#################################################################################################

This is my code:

#################################################################################################

from office365.sharepoint.attachments.collection import Attachment
from office365.sharepoint.files.creation_information import FileCreationInformation
from office365.sharepoint.client_context import ClientContext

list_title = "REGO_TMR"
tasks_list = ctx.web.lists.get_by_title(list_title)

##### 1. create a new list item
task_item = tasks_list.add_item({
    "Title": "New Task"
}).execute_query()

attachment_path = '/tmp/' + v_our_rego_num + '.png'

##### 2. upload attachment into list item
with open(attachment_path, 'rb') as content_file:
    file_content = content_file.read()
attachment_file_information = FileCreationInformation(os.path.basename(attachment_path), file_content)

task_item.attachment_files.add(attachment_file_information).execute_query()

#################################################################################################

The 'New Task' is added to my list successfully.  When trying to add an attachment, I get these issues.

## As additional information:
I used the sample code provided here:
https://github.com/vgrem/Office365-REST-Python-Client/issues/422

When running this command:
from office365.sharepoint.attachments.attachmentfile_creation_information import AttachmentfileCreationInformation

I got the error:
#################################################################################################

ModuleNotFoundError: No module named 'office365.sharepoint.attachments.attachmentfile_creation_information'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File <command-4051518900502651>:1
----> 1 from office365.sharepoint.attachments.attachmentfile_creation_information import AttachmentfileCreationInformation

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

ModuleNotFoundError: No module named 'office365.sharepoint.attachments.attachmentfile_creation_information'
#################################################################################################

So after browsing through the available methods, I tried to use: 
from office365.sharepoint.attachments.collection import Attachment
which is generating the current error above:  AttributeError: 'FileCreationInformation' object has no attribute 'filename'.

Please can you assist or provide an example of how to add an attachment to a SharePoint List item for Version 2.4.3?

Thanks in advance for all your efforts and support.

**Comment by vgrem** [comment]
Greetings,

it appears the module name is misspelled here, it is expected to be: 
`from office365.sharepoint.attachments.creation_information import AttachmentCreationInformation`
instead of 
`from office365.sharepoint.attachments.attachmentfile_creation_information import AttachmentfileCreationInformation`

**Comment by SatchinM** [comment]
Thank you so much vgrem, this works.
