### ISSUE TITLE
How to lookup item Value from SharePoint List with lookup column

### ISSUE THREAD

**Issue by inmasierra** [vgrem/Office365-REST-Python-Client#736]
Hi,

I would like to lookup an item from a Sharepoint List in which there are lookup columns. I had found the class FieldLookupValue but I don't know how to use it. I need to lookup the referenced fields and show the Value directly. Do you have any code snippet to perform it?

Using this example How to get data from lookup column #361 (https://github.com/vgrem/Office365-REST-Python-Client/issues/361 
) I have the column  **Title** but in my case the referenced lookup column is different and I don't know how to retrieve it directly with Python.

Thanks in advance

**Comment by vgrem** [comment]
Hi there,

the following example demonstrates how to retieve lookup field values from a SharePoint List


```python
ctx = ClientContext(site_url).with_credentials(client_credentials)

list_tasks = ctx.web.lists.get_by_title("Tasks")
items = (
    list_tasks.items.get()
    .select(
        [
            "*",
            "AssignedTo/Id",
            "AssignedTo/Title",
            "Predecessors/Id",
            "Predecessors/Title",
        ]
    )
    .expand(["AssignedTo", "Predecessors"])
    .top(10)
    .execute_query()
)

for item in items:
    assigned_to = item.properties.get("AssignedTo", {}).get("Id", None)
    predecessors_ids = [v.get("Id", None) for k, v in item.properties.get("Predecessors", {}).items()]
    print("AssignedTo Id: {0}, Predecessors Ids: {1}".format(assigned_to, predecessors_ids))
```

A few comments:

- `AssignedTo` a single valued lookup field and `Predecessors` a multi valued lookup field
-  to reteieve a lookup field value, both `select` and `expand` query options needs to be  specied where the expression `{LookupFieldName}/{LookupListFieldName}` determines which properties needs to be retuned from a _lookup_ list
