### ISSUE TITLE
Office365-REST-Python-Client and GCC High 

### ISSUE THREAD

**Issue by borisiliev0** [vgrem/Office365-REST-Python-Client#737]
Does this package work with the GCC High environment?

**Comment by vgrem** [comment]
Greetings,

the support for SharePoint authentication with GCC High Environments has been introduced in [`2.5.4` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.4).  
Refer [Support for non-standard SharePoint Online Environments section](https://github.com/vgrem/Office365-REST-Python-Client?tab=readme-ov-file#support-for-non-standard-sharepoint-online-environments) for the details.
