### ISSUE TITLE
'NoneType' object has no attribute 'add_child' when use copy_to_using_path

### ISSUE THREAD

**Issue by bhurivaj** [vgrem/Office365-REST-Python-Client#740]
Scenario: When I create record on ERP. I want the system create folder with sub folders and files inside automatically.

Problem: when I created record. It shown that "object has no attribute 'add_child' when use copy_to_using_path"

here: the sample of my code:
```
        sharepoint_tenant = "https://tenant_name.sharepoint.com/sites/sandbox"

        cert_settings = {
            'client_id': xxxxxxx-xxxxxxxxxxx-xxxxxxxxxxxxx,
            'thumbprint': "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            'cert_path': /path/to/cert.pem
        }

        ctx = ClientContext(sharepoint_tenant).with_client_certificate(tenant_name.onmicrosoft.com, **cert_settings)

        from_url = "/".join(["Document Templates", "project_folder"])
        to_url = "/".join(["Shared Documents", new_name])

        src_folder = ctx.web.get_folder_by_server_relative_url(from_url)
        dest_folder = ctx.web.default_document_library().root_folder.folders
        src_folder.copy_to_using_path(dest_folder, True).execute_query()

```

on Project folder template
   project_folder
   -- 01 quotation
   -- 02 purchasing order
   -- 03 project documents
        |-- img
        |-- old revision

I have done it on previous version 2.3.3. But when I updated to current version. It made me change to "client certificate"'s way. After that I am getting that problem. Please correct my code if I'm wrong.

Thanks.

**Comment by vgrem** [comment]
Hi there,

thank you for catching and reporting this issue, it has been addresed in [`2.5.0` release](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.0)
