### ISSUE TITLE
self._cached_token = token_func() TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by rohithbhumar** [vgrem/Office365-REST-Python-Client#741]
import msal
from office365.graph_client import GraphClient
import requests
import json
from office365.sharepoint.client_context import ClientContext

client_id = "clientid"
authority = "https://login.microsoftonline.com/{tentant-id}"
client_secret = "secret"
scopes = ["https://tenant.sharepoint.com/.default"]
redirect_uri = "http://localhost:5000"
site_url = "https://pqatesting.sharepoint.com/sites/Testbot"

app = msal.ConfidentialClientApplication(client_id, client_credential=client_secret, authority=authority)

result = app.initiate_auth_code_flow(scopes=scopes)

if not result:
    result = app.acquire_token_for_client(scopes=scopes)

if "access_token" in result:
    access_token = result["access_token"]
    print(access_token)

else:
    print("Authentication failed")

ctx = ClientContext(site_url).with_access_token(access_token)
web = ctx.web
ctx.load(web)
ctx.execute_query()

headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json",
}

response = requests.get(
    url="https://graph.microsoft.com/v1.0/",
    headers=headers,
)

print(json.dumps(response.json(), indent=4))

I get the access_token for the valid client_ids, client_secret. However, I'm stuck with this error - 

line 129, in _authenticate
    self._cached_token = token_func()
                         ^^^^^^^^^^^^
TypeError: 'str' object is not callable

**Comment by rohithbhumar** [comment]
@vgrem Kindly look into it and assist me. Thanks very much in advance

**Comment by vgrem** [comment]
Hi there,

SharePoint REST API (`ClientContext`)  does **not** accept app with a client secret. Per official [ MS documentation](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#faq). 

> ### Can I use other means besides certificates for realizing app-only access for my Azure AD app?
> 
> No, all other options are blocked by SharePoint Online and will result in an Access Denied message.



For app the access tokens needs to be requested with a client certificate](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#second-case-access-token-request-with-a-certificate), refer [`connect_with_client_certificate.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/connect_with_client_certificate.py)  for a details.   



Another option would be moving to [MS Graph for SharePoint API aka SharePoint REST API v2](https://learn.microsoft.com/en-us/sharepoint/dev/apis/sharepoint-rest-graph) For this API it is supported to[ request access tokens with _client secrets_](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret).

**Comment by rohithbhumar** [comment]
Thanks @vgrem.
