### ISSUE TITLE
Read values from a Workbook range

### ISSUE THREAD

**Issue by kellerza** [vgrem/Office365-REST-Python-Client#745]
How would one get the cell values from a range in the GraphClient?

The workbook only allows access to named-ranges or tables

```
class Workbook(Entity):
    """The top-level object that contains related workbook objects such as worksheets, tables, and ranges."""
````
The `WorkbookWorksheet` also seems to lack any range property

A direct call to MS graph would be:

```
https://graph.microsoft.com/v1.0/sites/__siteId__/lists/__listId__/items/__itemId__/driveitem/workbook/worksheets('Sheet1')/range(address='B4:N1000')?select=values
```

**Comment by vgrem** [comment]
Greetings,

a new version ([`2.5.5`](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.5)) has been released with a better support for [Range](https://learn.microsoft.com/en-us/graph/api/worksheet-range?view=graph-rest-1.0&tabs=http) in OneDrive API, here is an example:  


```python
client = GraphClient.with_username_and_password(
    tenant_name, client_id, username, password
)
drive_item = client.me.drive.root.get_by_path("Financial Report.xlsx")
worksheet_range = drive_item.workbook.worksheets["Sheet1"].range(address="A1:B3").execute_query()
```
