### ISSUE TITLE
how to get the list of files stored in sharepoint folder

### ISSUE THREAD

**Issue by kenil-samyak** [vgrem/Office365-REST-Python-Client#753]
I have gone through the whole respository of Office365-REST-Python-Client to find out the way to get the list of files using URL, but I didnt't get any code yet. Help me find out the solution for this or if anyone knows how to get the list of files from folder shared link, then let me know

**Comment by TomPughe** [comment]
The example [/examples/onedrive/folders/list_with_files.py](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/onedrive/folders/list_with_files.py) might help, this shows how to get a list of the contents of OneDrive / SharePoint folder from a driveItem class instance if that's what you're after. 

(see line `drive_items = root_folder.children.get().execute_query()`)

If you need an example of how to get a DriveItem from a URL, I've been using the following:
`drive_item = client.shares.by_url(share_point_url).drive_item.get().execute_query()`

**Comment by vgrem** [comment]
Hi there, 

in addition to @TomPughe  answer which covers `SharePoint V2/OneDrive` API, in case of `SharePoint V1` API,  `Web.get_folder_by_guest_url(link_url)` could be utilized to retrieve a folder from a sharing link url, for example:


`shared_folder = ctx.web.get_folder_by_guest_url(sharing_link_url).execute_query() `
