### ISSUE TITLE
array of items retuning empty from list in Sharepoint

### ISSUE THREAD

**Issue by CaioSoaresBrazil** [vgrem/Office365-REST-Python-Client#754]
Hi,

I'm able to access the sharepoint page using client id / secret. I can list the columns and properties from the list. In the properties shows that it has more then 1000 items. However, when doing get_items, it's coming empty. I did heaps of researchs and troubleshootings, but no luck.

`from pprint import pprint
from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.user_credential import UserCredential
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.lists.list import ListItem

site_url = "HIDDEN"

client_credentials = ClientCredential(client_id, client_secret)
ctx = ClientContext(site_url).with_credentials(client_credentials)

list_object = ctx.web.lists.get_by_title('Journal Requests')

items = list_object.get_items()

ctx.load(items)
ctx.execute_query()
pprint(items)
`

I appreciate your help.

client id and secret are in a few lines above this script.

**Comment by CaioSoaresBrazil** [comment]
realised that I didn't have "All Items" view created. I have created and ensured that it has all the items.

array still returning empty :(

**Comment by CaioSoaresBrazil** [comment]
Found the problem... missing permissions in the sharepoint side... after the adjustment in the sharepoint side the items started to come up.

it's funny why the module didn't return any permission error when trying to fetch these items while I didn't have the proper permission.

**Comment by Xeyow** [comment]
@CaioSoaresBrazil I am having the same issue... I can access the list, but the items array is empty. What permissions did you add, and where? Thanks!

**Comment by Babak28** [comment]
> Found the problem... missing permissions in the sharepoint side... after the adjustment in the sharepoint side the items started to come up.
> 
> it's funny why the module didn't return any permission error when trying to fetch these items while I didn't have the proper permission.

We are having the same issue, could you elaborate more on what and where the missing permissions were?
