### ISSUE TITLE
`typing_extensions` required for v2.5.0 but not included in `install_requires`?

### ISSUE THREAD

**Issue by ignaciocabeza** [vgrem/Office365-REST-Python-Client#755]
We are having the following error with the latest version:

```
Traceback (most recent call last):
  File "/builds/XXX/sharepoint-sync-script/sharepoint_sync_script.py", line 5, in <module>
    from office365.sharepoint.client_context import ClientContext
  File "/usr/lib/python3.10/site-packages/office365/sharepoint/client_context.py", line 5, in <module>
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'
```

Probably because `typing_extensions` is not included in `install_requires`:
https://github.com/vgrem/Office365-REST-Python-Client/blob/master/setup.py#L22C5-L22C21

**Comment by vgrem** [comment]
@ignaciocabeza, thank you for catching this error, `2.5.1` version  addresses this issue

**Comment by alecVincentMedscint** [comment]
> @ignaciocabeza, thank you for catching this error, `2.5.1` version addresses this issue

The problem is still present with Python 3.11 and the 2.5.1 version. The problem can be found in many places but here's an example:

![image](https://github.com/vgrem/Office365-REST-Python-Client/assets/126795826/ec592aa0-b8ae-4eb7-a214-7ad39bee5fd7)
