### ISSUE TITLE
time_last_modified property pf SharePoint file as datetime

### ISSUE THREAD

**Issue by ferokko** [vgrem/Office365-REST-Python-Client#761]
Hi, 
is it possible that time_last_modified property of a SP file is now get as datatime object and no more as string? 

code:

```
def get_files_list(web,libraries):
for lib in libraries:
        library = web.get_folder_by_server_relative_url(lib).execute_query()
        for f in library.files.get().execute_query():
              return files
              
files =  get_files_list(web,libraries) 
for lib,files_list  in files.items() :
          files = [{'url':f.serverRelativeUrl, 'time_last_modified':f.time_last_modified.strftime('%Y-%m-%dT%H:%M:%SZ') } for f in files_list]
```

time_last_modified always got back as str obj but now as datetime, I am the only one experiencing it? 
Thanks

**Comment by TaeaLambert** [comment]
You are not the only one experiencing it.
Just found the time created of a file (`file.time_created` ) is now a datetime. 
However, the FileVersions are a string type

**Comment by vgrem** [comment]
Greetings,

from 2.5.0 version, date specific data types (namely `Edm.DateTime` and `Edm.DateTimeOffset` are represented as properties of `datetime.datetime` type
