### ISSUE TITLE
Can’t share file with password Sharepoint API

### ISSUE THREAD

**Issue by lastorder999** [vgrem/Office365-REST-Python-Client#766]
Sharepoint API 
My code base on example “examples/sharepoint/sharing/share_file_with_password.py”
I can share without password
Error when I share with password 
`Office365.runtime.client_request_exception.ClientRequestsExeception: (‘-1, System.Invalid OperationException’, ‘cannot have password protection on a non-supported share’, “400 Client Error:Bad Request for url: https://mysite.sharepoint.com/sites/ShareDocument/_api/web/getFileByServerRelativePath(DecodedUrl=‘url_myfile.zip’/listItemAllFields/ShareLink”)`

**Comment by vgrem** [comment]
Thank you for catching and reporting it, indeed, the specified error could be encountered when password were passed (due a few mandatory properties were missing in request)

It has been addresed in [`2.5.2` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.2)
