### ISSUE TITLE
Instance of 'EmailIdentify' has no 'properties' member 

### ISSUE THREAD

**Issue by TomPughe** [vgrem/Office365-REST-Python-Client#773]
Commit https://github.com/vgrem/Office365-REST-Python-Client/commit/4b62b646c4f124227e53d8367099d2627bb99966 introduces `email` property for `EmailIdentify` (office365/directory/permissions/email_identity.py). However, this uses `properties` which pylint highlights "Instance of 'EmailIdentity' has no 'properties' member".

**Comment by TomPughe** [comment]
Made a suggestion for a basic fix to this in pull request https://github.com/vgrem/Office365-REST-Python-Client/pull/774 that undoes the changes to email_identify.py. If a better solution is to refactor email_identity to allow the `email` property to be retained, then feel free to change and/or ignore this Pull request

**Comment by vgrem** [comment]
Thank you for catching it and providing the resolution! 
Propose to consider it resolved since the change is included in [`2.5.2` release ](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.2)
