### ISSUE TITLE
unable to read the meta data of a file using Sharepoint API function get_file_by_server_relative_url

### ISSUE THREAD

**Issue by karges612** [vgrem/Office365-REST-Python-Client#775]
Below is my code 
from office365.runtime.auth.client_credential import ClientCredential
from office365.sharepoint.client_context import ClientContext

```
def get_share_point_context () :
    sharepoint_url = "https://xxxx.sharepoint.com/sites/rpa/"
    client_id = 'yyyy'
    client_scret = 'zzzz'
    ctx = ClientContext(sharepoint_url).with_client_credentials(client_secret=client_scret,client_id=client_id)
    relative_url = "/sites/rpa/Bl_Upload_test/"
    libraryRoot = ctx.web.get_folder_by_server_relative_url(relative_url)
    ctx.load(libraryRoot)
    ctx.execute_query()
    files = libraryRoot.files
    ctx.load(files)
    ctx.execute_query()
    for file in files :
        print(file.properties['Name'])
        print(file.author.email)
    with open (file.properties['Name'],"wb") as local_file :
         ctx.web.get_file_by_server_relative_url(relative_url + file.properties['Name']).download(local_file).execute_query()

get_share_point_context()
```

The above code just returns none. for the auther name but it downloads file  and more over i do not want author name i want the email id of the person who has uploaded the file to sharepoint. ie Modified by, that property is not coming up. even the "listitemfeilds" its not helping.  all the other meta data like versions  everything is returning none . 

i referred to the[ similar github issue](https://github.com/vgrem/Office365-REST-Python-Client/issues/362) and @vgrem  comment on it . but so far am not able to get the right answer
Also , am not sure that this is an issue or question.

**Comment by vgrem** [comment]
Greetings,

regarding `ModifiedBy` field value, `User` field type values are not getting returned _by default_ (by API design), it needs to be explicitly requested via `expand` query option, in the provided example the folllowing line needs to be adjusted from:

```python
ctx.load(files)
```

into 

```python
ctx.load(files, ["ModifiedBy", "Author", "TimeCreated", "TimeLastModified"])
```

**Comment by Venkatesh-ds** [comment]
I have created custom columns in share point, but while retrieving meta data am still getting info like Name, Title but not custom defined columns. Tried with approach ctx.load(files, ["ModifiedBy", "Author", "TimeCreated", "TimeLastModified"]) but still am getting same issue. Please help me in fixing this
