### ISSUE TITLE
[examples/listitems_operations_alt.py] I can't find method named 'execute_request_direct' which was used in this py. file

### ISSUE THREAD

**Issue by DuiduiLi** [vgrem/Office365-REST-Python-Client#78]
'execute_request_direct' method can't be found

**Comment by DuiduiLi** [comment]
@jimr @mirontoli @Toilal @vgrem @tomkcook  is the code in example folder too old?
Why I can't find method 'execute_request_direct'?
Thanks.

**Comment by vaderj** [comment]
Try updating 
      `execute_request_direct`
to
    `execute_query_direct`

[office365.runtime.auth.saml_token_provider.SamlTokenProvider.acquire_authentication_cookie #71](https://github.com/vgrem/Office365-REST-Python-Client/issues/71)

**Comment by vgrem** [comment]
`Examples` section have been updated to reflect the latest changes, `execute_request_direct`  method is exposed via `ClientRuntimeContext` class, here is an example on how to read `Web` resource:

```
ctx = ClientContext.connect_with_credentials(url, UserCredential(username,password))
request = RequestOptions("web")
response = ctx.execute_request_direct(request)
json = json.loads(response.content)
web_title = json['d']['Title']
```
