### ISSUE TITLE
Acquire_token function lacks parameter support

### ISSUE THREAD

**Issue by payalshah2304** [vgrem/Office365-REST-Python-Client#780]
We have been working with office 365 rest python client and encountered a limitation while using acquire_token method. Currently it appears that function does not accept any parameters. We are using AWS lambda function to connect to sharepoint using with_access_token(acquire_token) method. In this authentication scenario we need to pass additional parameters, such as client_id and client_assertion . As we are not able to pass parameters in this method, we tried to save these details in AWS storage and use it as global variable, but this will raise an issue while running concurrent lambda executions (as global variable might use same value for running multiple sessions).
We referred below code snippet
https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/connect_with_app_principal_aad.py

Can you please provide guidance on how to pass these necessary parameters? We would also appreciate any workaround that you can suggest.

**Comment by payalshah2304** [comment]
Can you please let us know any workaround meanwhile?

**Comment by vgrem** [comment]
Hi there,
the followings example demonstrates how to pass extra parameters in `acquire_token `callback:

```python 
def acquire_token_and_save_in_cache():
    import adal

    client_id = "--client_id goes here--"
    thumbprint = "--thumbprint goes here--"
    certificate_path = "./selfsigncert.pem"
    authority_url = "https://login.microsoftonline.com/{0}".format(tenant)
    auth_ctx = adal.AuthenticationContext(authority_url)
    with open(certificate_path, "r") as file:
        key = file.read()

    json_token = get_token_from_cache()
    if  json_token is None:
        json_token = auth_ctx.acquire_token_with_client_certificate(site_url, client_id, key, thumbprint)
        set_token_in_cache(json_token)

 
    return TokenResponse(**json_token)


ctx = ClientContext(test_site_url).with_access_token(acquire_token)

```

Or perhaps i misunderstood your question, could please elaborate abit more?

**Comment by vgrem** [comment]
Considered as resolved
