### ISSUE TITLE
ImportError: cannot import name 'TypedDict' from 'typing' on Python 3.7

### ISSUE THREAD

**Issue by eacherkan-aternity** [vgrem/Office365-REST-Python-Client#781]
Executing `from office365.sharepoint.client_context import ClientContext` results in `ImportError: cannot import name 'TypedDict' from 'typing' (/usr/local/lib/python3.7/typing.py)`.
The problem reproduces for versions 2.5.0-2.5.2, on Python 3.7. It does not reproduce for versions <= 2.4.4, or on Python >= 3.8.

Test case:
```
$ docker run --rm python:3.7 bash -c 'pip install Office365-REST-Python-Client; python -c "from office365.sharepoint.client_context import ClientContext"'
```
Actual result:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/office365/sharepoint/client_context.py", line 7, in <module>
    from office365.runtime.auth.authentication_context import AuthenticationContext
  File "/usr/local/lib/python3.7/site-packages/office365/runtime/auth/authentication_context.py", line 3, in <module>
    from typing import Any, Callable, TypedDict
ImportError: cannot import name 'TypedDict' from 'typing' (/usr/local/lib/python3.7/typing.py)
```
Full output: [ImportError.txt](https://github.com/vgrem/Office365-REST-Python-Client/files/13281799/ImportError.txt)

**Comment by vgrem** [comment]
Greetings,

thank you for catching this issue and providing the test case, it ha been addresed  in a new [`2.5.3` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.3).
