### ISSUE TITLE
 "TypeError: 'dict' object is not callable." 

### ISSUE THREAD

**Issue by oarthurcarvalho** [vgrem/Office365-REST-Python-Client#783]
I successfully uploaded a file to SharePoint using the office365.graph_client library in Python. However, on subsequent attempts, I encountered the error:

> "TypeError: 'dict' object is not callable." 

This error prevents further successful uploads.

The Azure AD application, Client ID, and Client Secret have been properly configured, and the initial upload worked as expected.

The error occurs consistently when I attempt to upload additional files to SharePoint using the `drive.upload_file(f).execute_query()` method. It seems that the `execute_query()` method is expecting a callable object, but it receives a dictionary, causing a `TypeError`.

Here is the code:
```python
import glob

import msal
from decouple import config
from office365.graph_client import GraphClient


class SharepointUploader:
    """
    A class for uploading files to SharePoint using the Microsoft Graph API.
    """

    def __init__(self):
        """
        Initialize the SharepointUploader with configuration parameters.
        """
        self.SITE_NAME = config('site_name')
        self.SHAREPOINT_HOST_NAME = config('sharepoint_host_name')
        self.TENANT_ID = config('tenant_id')
        self.CLIENT_ID = config('client_id')
        self.CLIENT_SECRET = config('client_secret')
        self.UPLOAD_PATH = config('upload_path')
        self.FILE_PATH = config('file_path')

        # Used with 'get_by_url' in GraphClient calls
        self.tenant_url = f'https://{self.SHAREPOINT_HOST_NAME}' \
            f'/sites/{self.SITE_NAME}'

        # We're running this in actions, so we'll only ever have one .md file
        self.local_files = glob.glob(self.FILE_PATH)

        self.client = self._initialize_graph_client()

    def _initialize_graph_client(self):
        """
        Initialize and acquire token via MSAL, and create a GraphClient.
        """
        authority_url = f'https://login.microsoftonline.com/{self.TENANT_ID}'
        app = msal.ConfidentialClientApplication(
            authority=authority_url,
            client_id=self.CLIENT_ID,
            client_credential=self.CLIENT_SECRET
        )
        token = app.acquire_token_for_client(
            scopes=["https://graph.microsoft.com/.default"])

        client = GraphClient(token)
        return client

    def upload_files(self):
        """
        Upload files to SharePoint.
        """
        drive = self.client.sites.get_by_url(
            self.tenant_url).drive.root.get_by_path(self.UPLOAD_PATH)

        for f in self.local_files:
            remote_file = drive.upload_file(f).execute_query()
            try:
                remote_file = drive.upload_file(f).execute_query()
            except Exception as e:
                print(e)
                print(f"Unexpected error occurred: {e}, {type(e)}")
            finally:
                if remote_file is not None:
                    print(f"File {remote_file.web_url} has been uploaded")


if __name__ == '__main__':
    sh = SharepointUploader()
    sh.upload_files()
```
I'm seeking guidance on how to resolve this `TypeError` issue. Has anyone encountered a similar problem or can offer insights into why this error occurs and how to ensure consistent successful uploads? Any help is appreciated. 

 I was expecting consistent successful file uploads and need guidance on resolving the error.

    Traceback (most recent call last):
      File "/home/artbdr/Documents/tmk-data/main.py", line 28, in <module>
        uploader.upload_files()
      File "/home/artbdr/Documents/tmk-data/upload_file.py", line 58, in upload_files
        remote_file = drive.upload_file(f).execute_query()
      File "/home/artbdr/.pyenv/versions/tmk/lib/python3.10/site-packages/office365/runtime/client_object.py", line 62, in execute_query
        self.context.execute_query()
      File "/home/artbdr/.pyenv/versions/tmk/lib/python3.10/site-packages/office365/runtime/client_runtime_context.py", line 191, in execute_query
        self.pending_request().execute_query(qry)
      File "/home/artbdr/.pyenv/versions/tmk/lib/python3.10/site-packages/office365/runtime/client_request.py", line 37, in execute_query
        response = self.execute_request_direct(request)
      File "/home/artbdr/.pyenv/versions/tmk/lib/python3.10/site-packages/office365/runtime/client_request.py", line 47, in execute_request_direct
        self.beforeExecute.notify(request)
      File "/home/artbdr/.pyenv/versions/tmk/lib/python3.10/site-packages/office365/runtime/types/event_handler.py", line 42, in notify
        listener(*args, **kwargs)
      File "/home/artbdr/.pyenv/versions/tmk/lib/python3.10/site-packages/office365/graph_client.py", line 187, in _authenticate_request
        token_json = self._acquire_token_callback()
    TypeError: 'dict' object is not callable

It might same error bellow issue but I can't solved this error. 
https://github.com/vgrem/Office365-REST-Python-Client/issues/397
https://github.com/vgrem/Office365-REST-Python-Client/issues/442

I'm sorry for the question, but it's the first time I'm using this lib.

**Comment by Fynis96** [comment]
Hey there, it looks like when you create the client object using the GraphClient() constructor, you are passing in a token dict directly, whereas the GraphClient constructor is expecting a function that returns a token.

For example

`
def acquire_token(app):
    token = app.acquire_token_for_client(
            scopes=["https://graph.microsoft.com/.default"])
    return token
client = GraphClient(acquire_token(app))
`

**Comment by vgrem** [comment]
Greetings, 

as @Fynis96 correctly pointed out and given the provided example, it could be adjusted like this:  


```python
 def _initialize_graph_client(self):
        """
        Initialize and acquire token via MSAL, and create a GraphClient.
        """
        authority_url = f'https://login.microsoftonline.com/{self.TENANT_ID}'
        app = msal.ConfidentialClientApplication(
            authority=authority_url,
            client_id=self.CLIENT_ID,
            client_credential=self.CLIENT_SECRET
        )

        def _acquire_token_callback():
              return app.acquire_token_for_client(scopes=["https://graph.microsoft.com/.default"])

        return GraphClient(_acquire_token_callback)
```


Another option would be to utilize the library _built-in_ method: `GraphClient.with_client_secret(tenant, client_id, client_secret)`, refer [this example](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/directory/roles/list.py) for a details.
