### ISSUE TITLE
Get user properties from Person or Group Lookup field in list

### ISSUE THREAD

**Issue by ryandenvergov** [vgrem/Office365-REST-Python-Client#784]
When I pull data from my different People Lookup columns, I only get the Id number for that person. I want to be able to pull their name, title, email, etc. I haven't found what I need in this repo or elsewhere (I think), but it seems so possible, what am I missing? Right now I'm trying to just pull all users to reference when looking for the Ids I get out of my list. But maybe I could get the user properties directly from the list query?

```
def get_users(basesite):
    baseurl = 'https://url.sharepoint.com'
    username = 'username'
    password = 'password'
    siteurl = baseurl + basesite 
    
    user_credentials = UserCredential(username,password)
    ctx = ClientContext(siteurl).with_credentials(user_credentials)
    
    group_users = ctx.web.associatedMemberGroup.users.get().execute_query()
    users_emails = {u.properties["Id"]:u.properties["Email"] for u in group_users}
    
    print(users_emails)
```
    
The error I get with this is `AttributeError: 'Web' object has no attribute 'associatedMemberGroup'`
   
Should this be connected to the list? How? The Lookup column for the list isn't using list-specific users.

**Comment by vgrem** [comment]
Greetings,

the property name is expected to be [`Web.associated_member_group`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/office365/sharepoint/webs/web.py#L2033), [here](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/groups/expand_to_principals.py) is an example.


Regarding the question;

> I want to be able to pull their name, title, email, etc. I haven't found what I need in this repo or elsewhere (I think), but it seems so possible, what am I missing?

indeed user field values are not getting retuned _by default_, they need to be explicitly requested (namely via [`expand` query option](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)), for example:   


```python
items = (
    list_tasks.items.get()
    .select(
        [
            "*",
            "CreatedBy/Id",
            "CreatedBy/Title",
            "ModifiedBy/Id",
            "ModifiedBy/Title"
        ]
    )
    .expand(["CreatedBy", "ModifiedBy"])
    .top(10)
    .execute_query()
)
```


where `CreatedBy `and `ModifiedBy `user field names


Example: [`get_lookup_field_value.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/listitems/get_lookup_field_value.py)
