### ISSUE TITLE
ModuleNotFoundError: No module named 'office365.runtime.paths.builder'

### ISSUE THREAD

**Issue by Kickdak** [vgrem/Office365-REST-Python-Client#786]
Got a new PC and installed python 3.11 and the module here.

Now I get this error: "ModuleNotFoundError: No module named 'office365.runtime.paths.builder'"

Any thoughts?

![image](https://github.com/vgrem/Office365-REST-Python-Client/assets/44496037/4d33b268-c9d2-436c-ad03-3b493b9ff7c1)

![image](https://github.com/vgrem/Office365-REST-Python-Client/assets/44496037/ed85d3af-7411-407f-b277-0692a3d1498a)

**Comment by vgrem** [comment]
Greetings,

perhaps you installed the latest version from github? It appears with the last commit a few imports have been broken, would suggest to install the package from pip instead:

`pip install Office365-REST-Python-Client`

**Comment by Kickdak** [comment]
Yeah, i installed the latest from github. 
By using the `pip install Office365-REST-Python-Client` the imports where solved.
Thanks :)
