### ISSUE TITLE
Downloading PDF's from sharepoint

### ISSUE THREAD

**Issue by quaid281** [vgrem/Office365-REST-Python-Client#789]
My code is working, but I keep getting the following error when opening the pdf files downloaded:
'Adobe Acrobat Reader could not open 'Filename' because it is either not a supported file type or because the file has been damaged (for example, it was sent as an email attachment and wasn't correctly decoded).

Here is my code

# Load the items in the list
items = reports_list.get_items()

ctx.load(items)
ctx.execute_query()

# Set up NTLM authentication
session = requests.Session()
session.auth = HttpNtlmAuth(username, password)

for item in items:
    # Use EncodedAbsUrl or ServerRelativeUrl to get the file URL
    file_url = item.properties['ServerRedirectedEmbedUrl']  # or item.properties['ServerRelativeUrl']
    file_name = item.properties['Title'].strip() + '.pdf'
    
    # Sanitize the file name to remove invalid characters
    file_name = re.sub(r'[<>:"/\\|?*]', '', file_name)
    
    download_path = os.path.join(r'C:\Users\Downloads\', file_name)
    
    # Get the file
    file = File.open_binary(ctx, file_url)
    
    # Write the file to the local folder
    with open(download_path, "wb") as local_file:
        local_file.write(file.content)
    print(f"Downloaded file: {file_name}")
else:
    print(f"Item does not have a 'FileRef' property: {item.properties['Title']}")

**Comment by vgrem** [comment]
Seems like a file gets damaged or corrupted while downloading.
But this issue is no longer could be reproduced, at least the downloading a file with standard example:

```python
with open(download_path, "wb") as local_file:
    file = (
        ctx.web.get_file_by_server_relative_url(file_url)
        .download(local_file)
        .execute_query()
    )

```
 
Note:  `File.open_binary` method is considered deprecated nowadays
