### ISSUE TITLE
Getting more than 100 items from a list

### ISSUE THREAD

**Issue by mjmaisey** [vgrem/Office365-REST-Python-Client#79]
I've been using examples/listitem_operations.py read_list_items() as a basis for a project I'm working on, and have hit a problem in that only the first 100 items in my list are returned.

[This](https://sharepoint.stackexchange.com/questions/74777/list-api-get-all-items-limited-to-100-rows) suggests that the underlying issue is that the underlying Sharepoint REST API is limited to returning 100 items at a time by default as a protection measure. There are some nasty hacks with $top= to increase the limit, but it appears the right way of retrieving an arbitrary number of items is to look for the existence of a link of the following form: 

```xml
<feed>
   ...
   <link rel="next" href=".../items?%24skiptoken=Paged%3dTRUE%26p_ID%3d100" />
</feed> 
```

on each set of results (the ... above is a contraction of the REST resource URI). This indicates that there are additional results, and provides a link to the next page.

Is accessing paged results possible with this client? Apologies if I'm missing something, but I can't find anything immediately obvious.

**Comment by timurgen** [comment]
@mjmaisey , You may want to use items = list_object.get_items(CamlQuery.create_all_items_query())
But in my situation it results in returning item duplicates where only difference is timezone in dates.

**Comment by vgrem** [comment]
Greetings!

Propose to close it since this feature has already been implemented and released.  All the credit goes to @Aisbergg for this feature implementation! 


**Examples**

Assume the following standard example for retrieving list items: 

```
large_list = ctx.web.lists.get_by_title(list_title)
items = large_list.get_items()
ctx.execute_query()

```

As correctly mentioned only `100` items gets retrieved by _default_  (although it could be controlled via [`$top` query option](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-odata/505b6322-c57f-4c37-94ef-daf8b6e2abd3) ), `len()` built-in function 

`items_count =  len(items)`

will return the actual amount of list items in list ( `items` stored in  list-like structure which implemented as a lazy load collection  behind the scene)

Same goes to enumeration of list items,  the following example demonstrates how to print `Title `property of all list items in a list:

```
for idx, item in enumerate(paged_items):
    print("{0}: {1}".format(idx, item.properties['Title']))
```

**Comment by ricsonchua** [comment]
Hi, 

I know this is clsoed but I would like to understand how get_items() in the example works? I can see that even though it is a user defined function it is able to work as if it is a member/method of office365.sharepoint.lists.list.List 

I am still learning Python so this is still something new to me. 
Overall my question is why is it
 `
items = large_list.get_items()
`
and not
`
items = get_items(large_list)
`

**Comment by tomfranken** [comment]
Answer for above - that's just the syntax <what you are working on>.<what you want>()

NOTE: the old is list.items.get() which gives the 100 results.  The new is list.get_items().  'Took me a few looks to see that...

**Comment by andresgd7** [comment]
im having the same problem and all seems fine in my code. I use this def to get the list into a dataframe

```
def dataframeSP(lista):
    ctx = ClientContext(site_url).with_credentials(ClientCredential(client_id, client_secret))
    sp_list = lista
    sp_lists = ctx.web.lists
    s_list = sp_lists.get_by_title(sp_list)
    l_items = s_list.get_items()
    ctx.load(l_items)
    ctx.execute_query()

    columnas=list(pd.DataFrame.from_dict(l_items[0].properties.items()).iloc[:,0])
    valores=list()

    for item in l_items:
        data=list(pd.DataFrame.from_dict(item.properties.items()).iloc[:,1])
        valores.append(data)
    resultado=pd.DataFrame(valores,columns=columnas)

    return resultado
```

**Comment by andresgd7** [comment]
Nevermind, i changed the method and now its working.

```
def dfSp2(lista):
    target_list = ctx.web.lists.get_by_title(lista)
    paged_items = target_list.items.get_all().execute_query()
    columnas=list(pd.DataFrame.from_dict(paged_items[0].properties.items()).iloc[:,0])
    valores=list()
    for index, item in enumerate(paged_items):
        data=list(pd.DataFrame.from_dict(item.properties.items()).iloc[:,1])
        valores.append(data)
    resultado=pd.DataFrame(valores,columns=columnas)
    return resultado

dfList = dfSp2("Plan de desarrollo")
```
