### ISSUE TITLE
Uploading file to driveItem does not work

### ISSUE THREAD

**Issue by 3vap** [vgrem/Office365-REST-Python-Client#799]
I use this example: https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/onedrive/files/upload.py

The only different is I extract driveItem in a different way:

folder_drive_item=client.shares.by_url(shared_url).drive_item.get().execute_query()

folder_drive_item.upload_file(local_path_to_file).execute_query()

I get error:

'BadRequest', "Resource not found for the segment 'driveItem:'.", '400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/shares/

**Comment by vgrem** [comment]
It has been addresed in [2.5.4 release](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.4)

Similar to #801
