### ISSUE TITLE
How to add modules

### ISSUE THREAD

**Issue by mirontoli** [vgrem/Office365-REST-Python-Client#8]
It would be great with a simple installation guide! I appreciate your work!

**Comment by mirontoli** [comment]
Right now I am running this before executing python scripts:

```bash
PYTHONPATH="$PYTHONPATH:~/Workspace/Office365-REST-Python-Client"
```

**Comment by vgrem** [comment]
Greetings,

regarding the installation guide the  README page has been updated that contains the installation section.

The following command will install the latest version of a module and its dependencies from the Python Packaging Index:

`python -m pip install Office365-REST-Python-Client`
