### ISSUE TITLE
Uploading file doing direct http request does not work

### ISSUE THREAD

**Issue by 3vap** [vgrem/Office365-REST-Python-Client#800]
After the official example was found not working I tried to upload my file using direct http request as described here:
https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0

url=f"https://graph.microsoft.com/v1.0/drives/{drive_id}/items/{item_id}:/uploded-file.txt/:content"

headers = {"Authorization": f"Bearer {access_token['access_token']}" }

with open(local_path, 'r') as file_data:
  requests.put( url,   headers=headers, data=file_data)

This failed with error "Write requests (excluding DELETE) must contain the Content-Type header declaration."

Adding "Content-Type":"text/plain"  to headers generate another error: "Entity only allows writes with a JSON Content-Type header"

So I changed the content type to: "Content-Type":"application/json"
And got another error: 
"Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format"

Changing payload to json using json.dumps/loads does not help neither... just a chain of errors....

**Comment by vgrem** [comment]
Hi,

it seems the example provided below works as expected:

```python
client = GraphClient.with_client_secret(tenant_name_or_id, client_id, client_secret)
remote_folder = client.users.get_by_principal_name(user_principal_name).drive.root  # get user's documents library 

local_path = "../../data/Financial Sample.xlsx"
file = folder.upload_file(local_path).execute_query()
```
 


Verified for different file types againts [`2.5.5` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.5)
