### ISSUE TITLE
Reading workbook example does not work

### ISSUE THREAD

**Issue by 3vap** [vgrem/Office365-REST-Python-Client#801]
drive_item=client.shares.by_url(shared_url).drive_item.get().execute_query()
worksheets = drive_item.workbook.worksheets.get().execute_query()

Gives error:
office365.runtime.client_request_exception.ClientRequestException: ('InternalServerError', 'Unable to find target address', '500 Server Error: Internal Server Error for url: https://graph.mic

**Comment by vgrem** [comment]
Thank you for reporting this bug, it has been addresed in [`2.5.4` release](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.4)
