### ISSUE TITLE
Get permissions of drive item

### ISSUE THREAD

**Issue by ArunJRK** [vgrem/Office365-REST-Python-Client#803]
Hello All, 
I am trying to replicate the below behavior using the graph client but not able to find it in the documentation. Can any of you please help.
`https://graph.microsoft.com/v1.0/drives/{drive_id}/items/{item_id}/permissions`
________________

For a work around I am trying like below

```
async def get_drives_of_site(self, site_url: str) -> EntityCollection[Drive]:
    drives = self.client.sites.get_by_url(site_url).drives.get().execute_query()
    return drives
```

```
async def get_drive_items_of_drive(drive: Drive) -> EntityCollection[DriveItem]:
    items = drive.items.filter("").get().execute_query()
    return items
```

But getting the error filter query missing while getting items

**Comment by vgrem** [comment]
Hi,

instead of filtering a single drive item could be addressed by file path,  here is excerpt from [official documentation](https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0):


> There are two primary ways of addressing a driveItem resource:
> 
> -    By the driveItem unique identifier using `drive/items/{item-id}` 
> 
> -    By file system path using `/drive/root:/path/to/file`
> 


Here is an example on how to list sharing permissions on a driveItem:


```python
client = GraphClient.with_username_and_password(
    test_tenant, test_client_id, test_username, test_password
)
file_path = "Archive/Financial Sample.xlsx"
file_item = client.me.drive.root.get_by_path(file_path)
permissions = file_item.permissions.get().execute_query()
```
