### ISSUE TITLE
Limit threshold exceeded while retrieving list items

### ISSUE THREAD

**Issue by inkyguy** [vgrem/Office365-REST-Python-Client#804]
Hi, I was using ClientObjectCollection.get_all(), ClientObjectCollection.paged(n) method along with filter and select queries on a large list in sharepoint(15K items) but is failing with below exception:

Error Message - ('-2147024860 Microsoft.SharePoint.SPQueryThrottledException' 'The attempted operation is prohibited because it exceeds the list view threshold.' "500 Server Error: Internal Server Error for url: _sharepointurl here_

query I was trying to execute is:
`list_items= listobj.items.get_all(1000, print_progress).filter(filter_query).select(select_column_list).execute_query()`
filter_query = query for filter (string query and there could be multiple conditions with and and or)
select column list  = =[list of columns to be selected]

version Im using is 2.5.4 Office365-REST-Python-Client
kindly help me resolve this issue.

**Comment by inkyguy** [comment]
Hi There, i found the issue, if i use filter query along with pagenation as mentioned below its raising causing the issue, if i remove filter query its retrieving 20K odd records. Can you help me apply filter query here?

`list_items= listobj.items.get_all(1000, print_progress).**filter(filter_query)**.select(select_column_list).execute_query()`

**Comment by felipependragon** [comment]
Hello guys, I have faced something like this and for me the resolution was create a index in sharepoint related to the field I want to filter, example:

My list has 43k rows and I needed to filter data by the DESC_STATUS, this column was crated with no index, so I created an Index in the sharepoint list for this column, after that the filter started working properly. 

It might be a solution.

**Comment by inkyguy** [comment]
Thanks for that, after enabling the index it worked. One more limitation i found was the column on which we are filtering should have index enabled, in addition to that the value on which we are filtering should not have more than 5000 occurrences in that specific column. 
EX: let's say I have 20k records with one of the columns named item. I'm trying to apply the item=='book', filter. but if the book is occurring in more than 5k rows, even with indexing enabled, it will throw the same limit exceeded error.
