### ISSUE TITLE
How to do combined filter

### ISSUE THREAD

**Issue by slyin87** [vgrem/Office365-REST-Python-Client#805]
How do I filter with AND / OR ?

Example

.filter("ID eq 46")

how do I filter...

.filter("ID eq 46 AND RequestType eq Bug")

or

.filter("RequestType eq Bug OR RequestType eq Change Request")

?

**Comment by vgrem** [comment]
Greetings,

the valid expression is expected to be `ID eq 46 and RequestType eq 'Change Request'`

where 

- `and` operator has to be lowercase  
- `RequestType` value is wrapped in single quotes in case of  text  type field  


Example:

```python
result = (
    ctx.web.lists.get_by_title("Site Pages").items
    .filter("ID eq 46 AND RequestType eq 'Change Request'")
    .get()
    .execute_query()
)

```
