### ISSUE TITLE
Query Sharepoint List drop duplicates

### ISSUE THREAD

**Issue by slyin87** [vgrem/Office365-REST-Python-Client#806]
is it possible to query a sharepoint list that contains multiple columns but I just want to query 1 column and return the unique (drop duplicates / distinct) result of that column?

**Comment by vgrem** [comment]
Greetings,

the following example demonstrates how to return distinct column values: 

```python
import json

from office365.sharepoint.client_context import ClientContext


view_xml = """
   <View>
       <Query>
          <GroupBy Collapse="TRUE" GroupLimit="100">
             <FieldRef Name="Author"/>
          </GroupBy>
       </Query>
       <ViewFields>
           <FieldRef Name="Author"/>
       </ViewFields>
       <RowLimit Paged="TRUE">100</RowLimit>
   </View>
   """

ctx = ClientContext(test_team_site_url).with_credentials(test_client_credentials)
lib = ctx.web.lists.get_by_title("Site Pages")
result = lib.render_list_data(view_xml).execute_query()
data = json.loads(result.value)
for item in data.get("Row"):
    print(item.get("Author.title"))
```

where:

- `Author` is the name of column for which to return _distinct_ values 
-  `view_xml` contains  [CAML Query](https://learn.microsoft.com/en-us/sharepoint/dev/schema/groupby-element-query) and `Collapse="TRUE"` flag instructs to return grouped items only
