### ISSUE TITLE
Get items from a specified folder in Lists

### ISSUE THREAD

**Issue by zhenyamorozov** [vgrem/Office365-REST-Python-Client#810]
Hello and hope you are having a wonderful day.

We are planning to migrate to Sharepoint Lists from another tool and therefore an automation we're using must be migrated too.  The functionality is fairly simple, but I couldn't figure it out yet.

I need to read list items from a specified lists folder. I can identify the folder I need like this. I am using CAML to retrieve top-level folders.
```python
# get the list
target_list = ctx.web.lists.get_by_title("My List").get().execute_query()

# prepare the CAML query
qry = CamlQuery()
qry.ViewXml = """
<View Scope='DefaultValue'>
    <Query>
        <Where>
            <BeginsWith>
              <FieldRef Name='ContentTypeId' />
              <Value Type='ContentTypeId'>0x0120</Value>
            </BeginsWith>
          </Where>
    </Query>
</View>    
"""

# get folders
folders = target_list.get_items(qry).execute_query()
workingFolder = next(i for i in folders if i.properties['Title']=="My Working Folder")
```
and I am not sure where to go from here to pull all the items from this specific folder. I've tried a few approaches, including another CAML query and setting qry.FolderServerRelativeUrl attribute but nothing works. Also, I expect it should not be that complicated.

Many thanks

**Comment by vgrem** [comment]
Greetings,

the provided code look legitimate, my guess `FolderServerRelativeUrl` is not honored since it is specied in non supported format. It could be either server or site relative url:

- _site relative url_: `qry.FolderServerRelativeUrl = "Shared Documents/Archive"`
-  _server relative url_ : `qry.FolderServerRelativeUrl = "/sites/mysite/Shared Documents/Archive"`

where `Archive` is the name of top folder under `Documents` library


### Example with CamlQuery.FolderServerRelativeUrl

```python
def create_custom_query():
    qry = CamlQuery()
    qry.FolderServerRelativeUrl = "Shared Documents/Archive"
    return qry


ctx = ClientContext(test_team_site_url).with_credentials(test_client_credentials)
lib = ctx.web.lists.get_by_title("Documents")
result = lib.get_items(create_custom_query()).execute_query()
```

**Comment by zhenyamorozov** [comment]
Many thanks, Vadim. It works for me. Just a couple things to note:
- I would so much prefer to receive an exception should incorrect ```FolderServerRelativeUrl``` be provided, rather than it simply being ignored.
- The _server relative URL_ from your example works great. But the _site relative URL_ for **a Lists folder** should start with "lists/": ```Lists/My List/MyFolder1```
