### ISSUE TITLE
Upload CSV with hebrew do not work

### ISSUE THREAD

**Issue by DavidEzrets** [vgrem/Office365-REST-Python-Client#817]
when uploading file csv to sharepoint with Hebrew it do not work (do work with xlsx and xml files)

  with open(dbfs_file_path, "rb") as content_file:
        file_content = content_file.read()
        target_folder = ctx.web.get_folder_by_server_relative_url(folder_2_save)
        target_folder.upload_file(file_name, file_content).execute_query()

**show:** ×©×ž×™ ×“×•×“ ×”×’×“×•×œ

    with open(dbfs_file_path, "rb") as content_file:
        file_content = content_file.read()
        target_folder = ctx.web.get_folder_by_server_relative_url(folder_2_save)
        file_content = file_content.decode('utf-8')
        target_folder.upload_file(file_name, file_content).execute_query()

**show**: Column1,Column2,Column3\n1,\u05e9\u05de\u05d9 \u05d3\u05d5\u05d3 \u05d4\u05d2\u05d3\u05d5\u05dc,1.1\n2,\u05e0\u05e0/\u05de\u05de,2.2\n3,\u05e0\u05e0\\\u05de\u05de,3.3\n4,\\u05e0\u05e0\"\"\u05de\u05de\"

Thank you !!
David

**Comment by vgrem** [comment]
Greetings,
 
it seems `utf-8-sig` encoding should do the trick, it generates CSV file in the following format:

[BOM](https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding)+Text

and allows to properly deptermine language for which the encoding is used.


```python
with open(path, "r") as content_file:
    file_content = content_file.read().encode("utf-8-sig")
file = folder.upload_file(os.path.basename(path), file_content).execute_query() 
```

**Comment by DavidEzrets** [comment]
Solved:

utf-8-sig did not worked, added the BOM manually:
        csv_string = io.StringIO()

        if header == True:
            df.to_csv(csv_string, index=False, encoding="utf-8")
        else:
            df.to_csv(csv_string, header=None, index=False, encoding="utf-8")
 
        csv_string = b'\xef\xbb\xbf' + csv_string.getvalue().encode('utf-8')
