### ISSUE TITLE
Filter to get deleted items/files

### ISSUE THREAD

**Issue by ssmails** [vgrem/Office365-REST-Python-Client#821]
I use the below code and filter to get created/updated items based on a certain date. However, this will not return deleted items. Is there a filter query or another mechanism to get the deleted items other than getting them from recycle bin and filtering them by date ?
The MS graph Api provides the delta query. Can you please add an example of using it with sharepoint as part of this library as well ?
@vgrem 
```
items = (
    ctx.web.lists.get_by_title(doc_lib)
    .items.select(["FileSystemObjectType"]).filter("Modified gt '2024-02-10T08:23:03Z'").expand(["File", "Folder"])
    .get_all()
    .execute_query()
)
```

**Comment by vgrem** [comment]
Hi there,

one option to consider is to query a changes from a change log. The following example demonstrates how to retrieve _deleted_ item change that have occurred within the list: 



```python
client = ClientContext(site_url).with_credentials(credentials)
query = ChangeQuery(
    item=True,
    add=False,
    update=False,
    system_update=False,
    delete_object=True,
    role_assignment_add=False,
    role_assignment_delete=False
)

list_title = "Documents"
result = client.web.lists.get_by_title(list_title).get_changes(query).execute_query()
```
