### ISSUE TITLE
Filter on list item file name property

### ISSUE THREAD

**Issue by samer1977** [vgrem/Office365-REST-Python-Client#826]
Hi ,
This works fine:
`items = large_list.get_items().expand(["File/Name"]).get()`

However when I try to do filter on the file name like this:

`items = large_list.get_items().expand(["File/Name"]).filter("File/Name ne 'Banner.png'").get()`

I get Invalid Column Name File!
Can someone help please.

**Comment by vgrem** [comment]
Hi there,

filtering document items per file name  could be performed like this:

```
result = (
    ctx.web.lists.get_by_title("Documents")
    .items.get()
    .filter("FileLeafRef eq 'report.csv'")
    .execute_query()
)

```

where [`FileLeafRef`](https://learn.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-commcsom/c9b65947-bd96-4b3a-9420-ba44b9940743):  

> Specifies the name of the document.



Although the query in your example and the expression `filter("File/Name ne 'Banner.png'")` looks legitimate, the reason why the error ccours rather related with SharePoint API OData implementation.

**Comment by samer1977** [comment]
Thank you so much
