### ISSUE TITLE
Is it possible to delete files?

### ISSUE THREAD

**Issue by ck3mp** [vgrem/Office365-REST-Python-Client#83]
I'm trying to use this to delete a file but without OAuth I believe the DELETE request requires "X-RequestDigest" header to be added to the request however this doesn't seem to do it? Is there a possible solution or planned OAuth?

```
import yaml

from office365.sharepoint.file import File
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext

with open("config.yml", 'r') as ymlfile:
    cfg = yaml.load(ymlfile)

url = f"https://xxx.sharepoint.com/sites/Site1"

relative_url = "/sites/Site1/Shared Documents/Video 1.mp4"

ctx_auth = AuthenticationContext(url)
ctx_auth.acquire_token_for_user(cfg['Office365']['Username'], cfg['Office365']['Password'])

ctx = ClientContext(url, ctx_auth)

response = File.delete_binary(ctx, relative_url)

print(response.content)
```

**Comment by lihtiandxc** [comment]
+1

**Comment by vgrem** [comment]
Hey guys!

Method `delete_binary` seems to be redundant, i recommend to utilize  `File.delete_object` method instead:

```
ctx = ClientContext(url, ctx_auth)
file_rel_url = "/sites/teamsite/Shared Documents/Video 1.mp4"
file_to_delete = ctx.web.get_file_by_server_relative_url(file_rel_url)  
file_to_delete.delete_object()
ctx.execute_query()

```
Sorry for the late response,
Vadim

**Comment by khihort** [comment]
Not work

**Comment by gregory-dan** [comment]
Hi

I wonder if there is a way to delete a **folder** and all it's content ?

Thanks!

**Comment by sivad-kr** [comment]
> Hey guys!
> 
> Method `delete_binary` seems to be redundant, i recommend to utilize `File.delete_object` method instead:
> 
> ```
> ctx = ClientContext(url, ctx_auth)
> file_rel_url = "/sites/teamsite/Shared Documents/Video.mp4"
> file_to_delete = ctx.web.get_file_by_server_relative_url(file_rel_url)  
> file_to_delete.delete_object()
> ctx.execute_query()
> ```
> 
> Sorry for the late response, Vadim

delete_object does not through any error but also does not delete the file. Could you please help

**Comment by Amal5187** [comment]
> > Hey guys!
> > Method `delete_binary` seems to be redundant, i recommend to utilize `File.delete_object` method instead:
> > ```
> > ctx = ClientContext(url, ctx_auth)
> > file_rel_url = "/sites/teamsite/Shared Documents/Video.mp4"
> > file_to_delete = ctx.web.get_file_by_server_relative_url(file_rel_url)  
> > file_to_delete.delete_object()
> > ctx.execute_query()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Sorry for the late response, Vadim
> 
> delete_object does not through any error but also does not delete the file. Could you please help

Hi @sivad-kr ,
In ur code replace get_file_by_server_relative_url to get_file_by_server_relative_path. It solved the problem for me.
