### ISSUE TITLE
Change displayName of users in batch query throws an Exception

### ISSUE THREAD

**Issue by wolfgang-302** [vgrem/Office365-REST-Python-Client#835]
I have a list of users where i have to change the displayName.
Doing this user by user works. I tried to do this using a batch-query like this.

`app_client` is of type office365.graph_client.GraphClient

`users_tkl31` is a list of 28 users found by
```python3
users_tkl31 = app_client.users.select(cols).filter("department eq 'tkl31'").get().execute_query()
```

with some given cols.

`displaynames` is a list of 28 displaynames found by
```python
trans = {ord(';'):','}
displaynames = [u.properties['displayName'].translate(trans) for u in users_tkl31]
```

The batch-query ist defined by

```python
for u,n in zip(users_tkl31,displaynames):
    print(u,n,end='\n')
    u.set_property('displayName',n).update()

app_client.execute_batch(items_per_batch=28)
```

This leads to the error message
```python
ClientRequestException: ('BadRequest', 'Number of requests inside batch exceed the limit.', '400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/$batch')
```

This is strange, because the length of `users_tkl31` and `displaynames` is 28 and this is given in `app_client.execute_batch(items_per_batch=28)` as parameter and 28 is smaller then 100.

I tried to change the size of items_per_batch to 7. Then i get another error:
```python
ClientRequestException: ('BadRequest', 'Write request id : 0 does not contain Content-Type header or body.', '400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/$batch')
```
Maybe i missunderstand the concept of batch-query but i think this should work.

**Comment by vgrem** [comment]
Thank you for catching and reporting this issue!

Along with few another issues for JSON batching implemntation, it has been addressed  in [`2.5.13` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.13).

By default `items_per_batch` is set to `20`  adhering to  [JSON batch requests limit](https://learn.microsoft.com/en-us/graph/json-batching#batch-size-limitations).


Here is an example: 


```python
users = client.users.get().filter("startswith(displayName, 'testuser')").top(50).execute_query()

for u in users:
    u.set_property('officeLocation', "18/2111").update()

client.execute_batch()
```
