### ISSUE TITLE
Certificate with Passphrase Error

### ISSUE THREAD

**Issue by DanialZohairen** [vgrem/Office365-REST-Python-Client#836]
I have a certificate with passphrase. I wanted to authenticate myself using certificate, but both providing the path and the private key are giving me this error:
![image](https://github.com/vgrem/Office365-REST-Python-Client/assets/98127526/6f5c38ed-8af8-46d2-bc17-e2b1e3a9a0eb)

**Comment by DanialZohairen** [comment]
@vgrem I tried to authenticate myself using 

site_url = 'https://contoso.sharepoint.com',  

cert_settings = {
    'client_id': client_id, 
    'thumbprint':thumbprint,
    'cert_path': 'mycert.pem'
}

ctx = ClientContext(site_url).with_client_certificate('contoso.onmicrosoft.com', **cert_settings)

**Comment by vgrem** [comment]
Hi there,

the support for passing a passphrase via `ClientContext.with_client_certificate `method  has been intoduced in [`2.5.7` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.7):


```python
cert_credentials = {
    "tenant": tenant_name,
    "client_id": client_id,
    "thumbprint": cert_thumbprint,
    "cert_path": "selfsignkeyenc.pem",
    "passphrase": "Password",
}
ctx = ClientContext(test_site_url).with_client_certificate(**cert_credentials)
current_web = ctx.web.get().execute_query()
```
