### ISSUE TITLE
Sites with on-premise STS does not authenticate (AADSTS70002)

### ISSUE THREAD

**Issue by shaycohen** [vgrem/Office365-REST-Python-Client#84]
Hi, 

When trying to migrate my application from an evaluation tenant (fully online Sharepoint Tenant) to  our production tenant, where the STS is on-premise, I get an authentication error. 

Code: 
```
import logging
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.runtime.client_request import ClientRequest
from office365.runtime.utilities.request_options import RequestOptions
logging.basicConfig()
api_url = "https://MYTENANT.sharepoint.com/teams/MYSITE/"
uri = "_api/lists"
username = "user@domain.com"
password = "P@SsW)rD"
print("testing with " + api_url + "/" + uri)
ctx_auth = AuthenticationContext(api_url)
print(ctx_auth)
if ctx_auth.acquire_token_for_user(username, password):
    request = ClientRequest(ctx_auth)
    options = RequestOptions("{0}/{1}".format(api_url, uri))
    options.set_header('Accept', 'application/json')
    options.set_header('Content-Type', 'application/json')
    print(options)
    data = request.execute_query_direct(options)
    print(data)
else:
    print("Error", ctx_auth.get_last_error())

```

Result: 
```
testing with https://MYTENANT.sharepoint.com/teams/MYSITE/_api/lists
<office365.runtime.auth.authentication_context.AuthenticationContext object at 0x7f910633aad0>
ERROR:office365.runtime.auth.saml_token_provider.SamlTokenProvider.process_service_token_response:An error occurred while retrieving token: AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password
ERROR:office365.runtime.auth.saml_token_provider.SamlTokenProvider.acquire_authentication_cookie:An error occurred while retrieving auth cookies
<office365.runtime.utilities.request_options.RequestOptions object at 0x7f910633ae50>
Traceback (most recent call last):
  File "auth_prod.py", line 32, in <module>
    data = request.execute_query_direct(options)
AttributeError: 'ClientRequest' object has no attribute 'execute_query_direct'
```

This tenant / site configuration was tested with node-sp-auth (to make sure the setup supports unattended authentication) and was working as expected. 

Any help will be greatly appreciated.

**Comment by Cesaaar** [comment]
I solved a similar issue in this way: https://github.com/vgrem/Office365-REST-Python-Client/issues/76

**Comment by vgrem** [comment]
Greetings!

In the latest release ([`2.1.10.1` ](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.1.10.1)at the moment) the support for SAML-based federated authentication with SharePoint Online has been improved and a bunch issues have been resolved, among them:

- #210 - Unable to connect to SharePoint(acquire_authentication_cookie error if federated) 
- #170 - An error occurred while retrieving token: AADSTS50126: Error validating credentials due to invalid username or password
- #85 - Using Office-365-REST with ADFS?

so, propose to close this one.
