### ISSUE TITLE
OnPremise SharePoint 

### ISSUE THREAD

**Issue by lathakris** [vgrem/Office365-REST-Python-Client#849]
Can I use the 'Office365-REST-Python-Client' for an OnPremise SharePoint. I need to do operations like listing the document libraries, downloading files, tagging files etc.

I am able to successfully use this for Online SharePoint.

Thank you.

**Comment by lathakris** [comment]
I think I am able to use this by passsing 'allow_ntlm' flag as below. thank you

ctx = ClientContext(site_url).with_user_credentials(username, password, allow_ntlm=True)
        web = ctx.web.get().execute_query()
        print(web.url)

**Comment by developer992** [comment]
does this not work anymore ? 

>TypeError: ClientContext.with_user_credentials() got an unexpected keyword argument 'allow_ntlm'
