### ISSUE TITLE
Using shares.by_url no longer works in version 2.5.10

### ISSUE THREAD

**Issue by jmolinacruz** [vgrem/Office365-REST-Python-Client#872]
The following snippet works fine for 2.5.9 but stopped working for 2.5.10:

```
result = client.shares.by_url(path).drive_item.get().execute_query()
print(result.get_content().execute_query().value)
```

The `result.get_content()` is what raises an error for Bad Url:

Exception has occurred: ClientRequestException
('BadRequest', "Resource not found for the segment '<<file_id>>'.", '400 Client Error: Bad Request for url: 

The resource path for the `result` is different between both versions:, shortened

1.  2.5.9 ----> /drives/ b!2nr9 / items / <<file_id>>
2. 2.5.10 ---> /shares/ u!aHR0cHM6 / <<file_id>>

**Comment by vgrem** [comment]
Hi, 
thank you for repotring it! 
It has been addressed in [`2.5.11` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.11).
