### ISSUE TITLE
How to switch from ACS to AD/ Microsoft Entra ID

### ISSUE THREAD

**Issue by salebs** [vgrem/Office365-REST-Python-Client#878]
Hi,

Our Django app is using ACS app-only access to authenticate user credentials in order to access SharePoint. However, due to its close end-of-life date, we want to switch to an Azure AD (now known as Microsoft Entra ID) app-only access method to do this.

In addition to the coming end-of-life date, we want to switch to AD because with our current configuration with ACS, when we go to the _layouts/15/appregnew.aspx page, we receive the following warning message:
_Starting April 2, 2026, Azure Access Control service (ACS) usage will be retired for SharePoint in Microsoft 365 and users will no longer be able to create or use Azure ACS principals to access SharePoint. [Learn more about the Access Control retirement](https://aka.ms/retirement/acs/support)_

So, when we move from ACS to AD, how would you recommend utilizing the client context? With client credentials or a certificate? We are seeing different ways to do so on this page. The ReadMe.md file shows AD using credentials; whereas, the **How to connect to SharePoint Online with certificate credentials** Wiki page shows AD using certificates.

Thanks!

**Comment by ederfdias** [comment]
To do it we need to use certificate: like mentioned here.
https://www.youtube.com/watch?v=jNKX6qos8ZI&list=PLR9nK3mnD-OXJLA29Q0Xk7psbAUqzQZwe&index=10

But i am not sure if that lib are able to use certificates. Is enable @vgrem ?

**Comment by vgrem** [comment]
@ederfdias,  surely it is supported, please refer [How to connect to SharePoint Online with certificate credentials](https://github.com/vgrem/Office365-REST-Python-Client/wiki/How-to-connect-to-SharePoint-Online-with-certificate-credentials) for the details.


More examples:

- [`auth_client_certificate.py` ](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/auth_client_certificate.py) -
- [`auth_client_certificate_passphrase`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/auth_client_certificate_passphrase.py) 
-  [`auth_client_certificate_private_key.py`](https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/auth_client_certificate_private_key.py)
