### ISSUE TITLE
AttributeError: 'ClientRequest' object has no attribute 'execute_query_direct'

### ISSUE THREAD

**Issue by hproba** [vgrem/Office365-REST-Python-Client#88]
I installed Office365 using `pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git` and it's currently on version 2.1.1
And when I converted my scripts from Python2 to Python3 I'm getting this error:
`AttributeError: 'ClientRequest' object has no attribute 'execute_query_direct'`

Thanks in advance for any help.

**Comment by vgrem** [comment]
Greetings!

`execute_query_direct`  has been renamed to `execute_request_direct`, sorry for the inconvenience and here is an example how to utilize it to get list items: 

```
ctx = ClientContext(site_url, ctx_auth)
options = RequestOptions("{0}/_api/web/lists/getbyTitle('{1}')/items".format(site_url, list_title))
options.set_header('Accept', 'application/json; odata=nometadata')
response = ctx.pending_request.execute_request_direct(options)
data = json.loads(response.content)
for item in data['value']:
    print("Item title: {0}".format(item["Title"]))
    
```

**Comment by Jaya-sys** [comment]
This is not working as well
