### ISSUE TITLE
An error occurred while retrieving auth cookies from sharepoint sign in 1.0, worked fine last week

### ISSUE THREAD

**Issue by WoutervanZeijl** [vgrem/Office365-REST-Python-Client#904]
Trying to update a sharepoint list with data. Worked fine last week, however this error from 2018 seems to reoccur. 

`from io import BytesIO 
from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.client_context import ClientContext
from office365.runtime.auth.authentication_context import AuthenticationContext
username = "my@username.nl"
password = "my_password"
#ctx = ClientContext(site_url).with_credentials(UserCredential(username, password))

baseurl = 'firms_sharepoint'
basesite = 'reference_to_sharepoint_list'
siteurl = baseurl + basesite

# Authentication
ctx_auth = AuthenticationContext(siteurl)
ctx_auth.acquire_token_for_user(username, password)
ctx = ClientContext(siteurl, ctx_auth)

# Access the list by title
list_title = 'WOZobjecten'
list_obj = ctx.web.lists.get_by_title(list_title)

# Create a new item or update an existing one
item_properties = {
    'Title': str(444)
}

# For creating a new item
new_item = list_obj.add_item(item_properties)
ctx.execute_query()
print(f"New item created with ID: {new_item.id}")
`

An error occurred while retrieving auth cookies from https://resources.my_firm.com/_forms/default.aspx?wa=wsignin1.0

**Comment by marielamunozo** [comment]
i have same problem from yesterday :/

**Comment by matt-davis27** [comment]
Why not use the `UserCredentials` line you have commented out to authenticate (since you're using username and password anyways)?

Replace your Authentication section with:

```python
ctx = ClientContext(siteurl).with_credentials(UserCredential(username, password))
```

**Comment by Felopo** [comment]
Same problem here. Please help!

**Comment by WoutervanZeijl** [comment]
Seems to work again.
