### ISSUE TITLE
How to upload a file in a subfolder of the Shared Documents folder?

### ISSUE THREAD

**Issue by mangano** [vgrem/Office365-REST-Python-Client#91]
Hello, 
Great python client. I'm now using it regularly to load files from my linux box to a Sharepoint website. 

I'm just unable to write into specific *subfolders* of the Shared Documents folder? 

The example in file_operations.py seems to write only in the root folder:

In upload_file() there is:
`file = upload_file_into_library(library, os.path.basename(path), file_content)`

Note the 'basename' part

And then in upload_file_into_library we have:

`target_file = target_library.root_folder.files.add(info)`

Note the 'root_folder' part. 

Any example on how to write into something like ShareDocuments/my_specific_folder ?
 
Thank you

**Comment by Bachatero** [comment]
Hi, 
try this instead:

#target_file = targetLibrary.root_folder.files.add(info)
folder = ctx.web.get_folder_by_server_relative_url(app_settings['urlrel'])
target_file = folder.files.add(info)

where urlel is a path to your subfolder, e.g. '/sites/FRAReporting/Shared Documents/TEST'

Hope it helps.

m.

**Comment by Bachatero** [comment]
I mean, 
app_settings = {
'urlrel': '/sites/FRAReporting/Shared Documents/TEST'
}

**Comment by mangano** [comment]
Fantastic. It worked!

Thank you,
Boris

**Comment by Kimjunkuk** [comment]
Fantastic. It worked!

Thank you,
Boris
