### ISSUE TITLE
Unable to query createdByAppId of group(s)

### ISSUE THREAD

**Issue by tuesdayMike** [vgrem/Office365-REST-Python-Client#917]
Hello,

I'm querying entra groups and users and am unable to get the createdByAppId Attribut (in beta release) of a group.

Code to query:

`ctx = GraphClient("https://graph.microsoft.com/beta").with_client_secret(tenant_id, client_id, client_secret)

groups = ctx.groups.get().select(["id,displayName,description,securityEnabled,onPremisesSecurityIdentifier,createdByAppId"]).top(999).execute_query()`

it makes no difference when I try to request the attribute for a given group (with ctx.groups[group_id]....) . The result always misses the attribute. In Graph Explorer it works fine.

Any hints?

Thank you!

**Comment by vgrem** [comment]
Greetings,

The `select` method expects a field names to be provided as list of strings: 


`groups = ctx.groups.get().select(["id", "displayName"]).top(999).execute_query()` `

**Comment by tuesdayMike** [comment]
@vgrem I tried that but it made no difference
