### ISSUE TITLE
taxonomy term_guid

### ISSUE THREAD

**Issue by realboom** [vgrem/Office365-REST-Python-Client#927]
There isn't a method to translate the term_guid into the actual string value.

               <d:OData__x0050_AL2 m:type="SP.Taxonomy.TaxonomyFieldValue">
                   <d:Label>4</d:Label>
                   <d:TermGuid>15dc69a8-8ede-4a22-9ec0-19ca980d9643</d:TermGuid>
                   <d:WssId m:type="Edm.Int32">4</d:WssId>
               </d:OData__x0050_AL2>

I need to get the actual value that shows in the list on the UI.

**Comment by vgrem** [comment]
It could be retrieved, for instance, via `TaxonomyHiddenList`, which represents a special list that stores the mapping between taxonomy term IDs and their corresponding values. 

For example:

```python
ctx = ClientContext(test_team_site_url).with_credentials(credentials)
term_guid = "--term-guid-goes-here--"
taxonomy_list = ctx.web.lists.get_by_title("TaxonomyHiddenList")
result = taxonomy_list.items.first("IdForTerm eq '{0}'".format(term_guid)).get().execute_query()
print(result.properties.get("Title"))  # print term title
```
