### ISSUE TITLE
How to download SharePoint files to AWS S3?

### ISSUE THREAD

**Issue by AakashBasu** [vgrem/Office365-REST-Python-Client#95]
Till now, the script for listing any given folder content and downloading iteratively works like a charm from my local machine and saving in local disk using python's "with open as local_file".

Now, I want to do the same to save it to AWS S3, which is an object store and uses Object("bucket", "path/filename.ext").put(Body=csv_buffer.getvalue())

eg:
`csv_buffer = io.StringIO()`
`dataframe.to_csv(csv_buffer, index=False)`
`s3_resource.Object("tb-us-east-1-regular-aakash", "Processed/sample.csv").put(Body=csv_buffer.getvalue())`

Will this be compatible with the following:

`response = File.open_binary(context, "/sites/abc/Shared Documents/"+fold_name+"/"+file_name)
with open(r"C:\Users\aakashb\Downloads\test\\"+file_name, "wb") as local_file:
    local_file.write(response.content)`

If not, how to go about it? Has anyone done it before? If yes, please share your views.

**Comment by AakashBasu** [comment]
I could solve it by writing the data temporarily to the /tmp/ of Lambda's container and then simply run:

`s3 = boto3.resource('s3')`
`bucket = s3.Bucket(bucket_name)`
`bucket.upload_file(tmp_file_path, key)`

This does the job.

**Comment by christian-warjri** [comment]
Hi @AakashBasu , can you please provide the code here.
