### ISSUE TITLE
Need to download Excel file (XLSX) from Sharepoint

### ISSUE THREAD

**Issue by aroc725** [vgrem/Office365-REST-Python-Client#97]
I'm trying to download an Excel (XLSX) file from Sharepoint using Python 3.7.

I've tried using the 'Office365-REST-Python-Client' module, without success. I'm unable to open the downloaded file using Excel, the error message indicates that the file extension or the file format is invalid.

When I change the file extension to 'XLS', I see the error message 'A potentially dangerous Request.Path value was detected from the client (?).' within the file.

It seems the problem is that the URL for the spreadsheet I'm trying to download contains a question mark (due to there being query parameters):

...doc.aspx?sourcedoc=...&file=...&action=default

(The method I'm using to download the file is the static 'open_binary' method of the 'File' class.)

**Comment by AakashBasu** [comment]
`def download_file(context, fold_name, file_name):
    try:
        t1 = time()
        print('Downloading file: ', "/sites/abc/Shared Documents/"+fold_name+"/"+file_name)
        response = File.open_binary(context, "/sites/abc/Shared Documents/"+fold_name+"/"+file_name)
        t2 = time()
        print('Time taken to download: ', "/sites/abc/Shared Documents/"+fold_name+"/"+file_name, ' is ', t2-t1, 'secs.')
        with open(r"C:\Users\ab\Downloads\test\\"+file_name, "wb") as local_file:
            local_file.write(response.content)
    except Exception as e:
        print('Problem downloading file '+file_name+', error: ', e)

if __name__ == '__main__':
    folder_name = 'Alpha_Test'
    url = credential['url']
    ctx_auth = AuthenticationContext(url=url)
    if ctx_auth.acquire_token_for_user(username=credential['user_id'], password=credential['pass']):
        contx = ClientContext(url, ctx_auth)
    download_file(contx, folder_name, file_name)
`

While calling the download_file method, pass the entire file name as an argument. This should work, it is working for not only .xlsx files but all types.

My indentation may be affected after posting, just ensure it is correct while you copy and run.

**Comment by aroc725** [comment]
Thanks for responding, but again, the Sharepoint URL for the Excel file I'm trying to download specifies query-string parameters:

...doc.aspx?sourcedoc=...&file=...&action=default

and seems to invoke some kind of .NET script, 'doc.aspx'.

So the URL really isn't specifying a direct folder path to the Excel file.

**Comment by AakashBasu** [comment]
I think I understand where you went wrong. The doc.aspx is a url path, not the actual file path. The Document Library files in SharePoint as per my understanding are always stored in "/sites/site_name/Shared Documents/folder_name/file_name" and if it is in root, just remove the folder_name from the path. That should work for you.

**Comment by aroc725** [comment]
Aakash, thanks for responding, much appreciated. I got the file path from my company's SharePoint admin, so I'm good to go now.

**Comment by vipish2804** [comment]
> I think I understand where you went wrong. The doc.aspx is a url path, not the actual file path. The Document Library files in SharePoint as per my understanding are always stored in "/sites/site_name/Shared Documents/folder_name/file_name" and if it is in root, just remove the folder_name from the path. That should work for you.


Am also Facing similar issue while download .xlsx from share point link which i have access to

this the folder structure : "Files/Projects/HBG/Development" and  filename="Template - Example.xlsx"" and URL is something like this : https://abc-my.sharepoint.com/personal/XYZ_com/_layouts/15/onedrive.aspx

**Comment by joshi2403** [comment]
Am also having the same issue, URL is not clean as you suggest.
