### ISSUE TITLE
How to get the datetime created and datetime updated from a Doc Lib file in SharePoint?

### ISSUE THREAD

**Issue by AakashBasu** [vgrem/Office365-REST-Python-Client#99]
I want to sync file edits, by simply checking if update datetime changes. Is there a way to capture datetime created and datetime updated? @vgrem @Bachatero

**Comment by vgrem** [comment]
Greetings!

If you are after [`List.LastItemModifiedDate` property](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee542409(v%3Doffice.15)) which 

> Gets a value that specifies the last time a list item, field, or property of the list was modified.

then the following example demonstrates how to accomplish it:

```
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext

user_credentials = os.environ['Office365_Python_Sdk_Credentials'].split(';')
site_url = "https://mediadev88.sharepoint.com/"
username = "--username--"
password = "--password--"

ctx_auth = AuthenticationContext(url=site_url)
ctx_auth.acquire_token_for_user(username=username, password=password)
ctx = ClientContext(site_url, ctx_auth)
list_obj = ctx.web.lists.get_by_title("Documents")
ctx.load(list_obj)
ctx.execute_query()

print("List title: {0}".format(list_obj.properties["LastItemModifiedDate"]))
```

**Comment by AakashBasu** [comment]
I am not sure what a SharePoint list is, I want the metadata of a file (modified date to be precise). Can I get it?

![image](https://user-images.githubusercontent.com/26522682/55536710-12cf2200-56d8-11e9-8489-491a3972f9a9.png)

**Comment by vgrem** [comment]
For a specific File the folllwing example will return the last modified time: 

```
ctx = ClientContext(site_url, ctx_auth)
target_file = ctx.web.get_file_by_server_relative_url("/Shared Documents/Guide.docx")
ctx.load(target_file)
ctx.execute_query()
```

Note: 
`Web.get_file_by_server_relative_url` method accepts **server relative file url** stored in SharePoint/OneDrive, which needs to be provided in the following format `/{library url}/{folder}/{sub- folder}/{file-name}`

**Comment by AakashBasu** [comment]
You are awesome!

Will run the experiment soon and reply. Thanks a ton!

**Comment by AakashBasu** [comment]
And how will I get the metadata out of the file? Is it in the properties dict? If yes, they what is the key to fetch the value?

Will this code work?

`ctx = ClientContext(site_url, ctx_auth)`
`target_file = ctx.web.get_file_by_server_relative_url("/Shared Documents/Guide.docx")`
`ctx.load(target_file)`
`ctx.execute_query()`
`target_file.properties["__metadata"])`

**Comment by AakashBasu** [comment]
It worked. Thank you!

**Comment by brake21** [comment]
@vgrem Can I use the library to get the list of all files modified last few minutes ? If so, could you please guide me. 

Thanks

**Comment by yashwanthreddy1828** [comment]
@AakashBasu @vgrem 
I have tried the same code for the file but it's not working.
Could you please help me with the below code. I want to get the file modified date using python code where the file is stored in SharePoint site. 
Please find the below code.

def modifiedDate(context):   
    target_file = context.web.get_file_by_server_relative_url("/Shared Documents/foldername/filename.xlsm")
    ctx.load(target_file)
    ctx.execute_query()
    print("List title: {0}".format(target_file.properties["LastItemModifiedDate"]))

I am facing the bad request error

error: HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for URL:

**Comment by soumyabehura** [comment]
@vgrem
I am trying with the above code to get the Modified date for a file present in Sharepoint site but i am getting below error.
    print("List title: {0}".format(target_file.properties['LastItemModifiedDate']))
KeyError: 'LastItemModifiedDate'
Below is the sample code
ctx =ClientContext(SITE_URL).with_user_credentials(USERNAME, PASSWORD) 
target_file = ctx.web.get_file_by_server_relative_url(file_url)
ctx.load(target_file)
print("List title: {0}".format(target_file.properties['LastItemModifiedDate']))
Could you please help me over here?

**Comment by vgrem** [comment]
@soumyabehura, in your example the method which submits query to the server is missing:

```python 
target_file = ctx.web.get_file_by_server_relative_url(file_url)
ctx.load(target_file)
ctx.execute_query()   #   <- submit query to the server
```

**Comment by soumyabehura** [comment]
Hi,

I am a bit new to Python so could you please let me know what would be the
method we need to use?

Actually, I am able to connect to the SharePoint site and read the data
from the file. But now my requirement is to get the last modified date of
the file. Could you please help me here?

*Thanks & Regards*
*Soumya S Behura*
*9742286034*

**Comment by soumyabehura** [comment]
@vgrem 
I added the the execute_query method into the code but still getting the same issue
ctx =ClientContext(SP_SITE_URL).with_user_credentials(USERNAME, PASSWORD) 
target_file = ctx.web.get_file_by_server_relative_url(file_url)
ctx.load(target_file)
print(ctx.execute_query())
print("List title: {0}".format(target_file.properties['LastItemModifiedDate']))

Output is as below:

![image](https://user-images.githubusercontent.com/58953230/130541941-de050ada-9f22-423c-9c06-6d2810444e0a.png)

**Comment by lukehamil55** [comment]
@soumyabehura I was able to print out the entire payload of target_file properties- it seems the **'LastItemModifiedDate' tag changed to 'TimeLastModified'**. If you want to be able to print all available file parameters, simply replace `.properties['<file_parameter>']` with `.properties`
